export const ANALYTICS_WIDGET_CATALOG = [
  {
    id: 'revenueTrend',
    metricName: 'revenue_total',
    chartType: 'area',
    size: 'large',
    titleKey: 'analytics.sections.revenue',
    descriptionKey: 'analytics.builder.widgets.revenue',
  },
  {
    id: 'appointmentTrend',
    metricName: 'appointment_count',
    chartType: 'bar',
    size: 'medium',
    titleKey: 'analytics.sections.appointments',
    descriptionKey: 'analytics.builder.widgets.appointments',
  },
  {
    id: 'patientGrowth',
    metricName: 'patient_count',
    chartType: 'line',
    size: 'medium',
    titleKey: 'analytics.patients.growthTitle',
    descriptionKey: 'analytics.builder.widgets.patients',
  },
  {
    id: 'collectionGauge',
    metricName: 'collection_rate',
    chartType: 'gauge',
    size: 'small',
    titleKey: 'dashboard.health.collection',
    descriptionKey: 'analytics.builder.widgets.collection',
  },
  {
    id: 'utilizationGauge',
    metricName: 'utilization_rate',
    chartType: 'gauge',
    size: 'small',
    titleKey: 'dashboard.health.utilization',
    descriptionKey: 'analytics.builder.widgets.utilization',
  },
  {
    id: 'branchComparison',
    metricName: 'branch_revenue',
    chartType: 'bar',
    size: 'large',
    titleKey: 'analytics.sections.branches',
    descriptionKey: 'analytics.builder.widgets.branches',
  },
  {
    id: 'providerPerformance',
    metricName: 'staff_productivity',
    chartType: 'bar',
    size: 'medium',
    titleKey: 'analytics.sections.doctors',
    descriptionKey: 'analytics.builder.widgets.staff',
  },
  {
    id: 'inventoryHealth',
    metricName: 'inventory_stock_health',
    chartType: 'pie',
    size: 'medium',
    titleKey: 'analytics.inventory.summaryTitle',
    descriptionKey: 'analytics.builder.widgets.inventory',
  },
] as const;
