export const TENANT_RESOLVER = 'TENANT_RESOLVER';
export const EVENT_PUBLISHER = 'EVENT_PUBLISHER';
export const PATIENT_REPOSITORY = 'PATIENT_REPOSITORY';
export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY';
export const ENCOUNTER_REPOSITORY = 'ENCOUNTER_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TENANT_REPOSITORY = 'TENANT_REPOSITORY';
export const AUDIT_ENTRY_REPOSITORY = 'AUDIT_ENTRY_REPOSITORY';
export const DENTAL_RECORD_REPOSITORY = 'DENTAL_RECORD_REPOSITORY';
export const INVENTORY_ITEM_REPOSITORY = 'INVENTORY_ITEM_REPOSITORY';
export const INVENTORY_CATEGORY_REPOSITORY = 'INVENTORY_CATEGORY_REPOSITORY';
export const INVENTORY_SUPPLIER_REPOSITORY = 'INVENTORY_SUPPLIER_REPOSITORY';
export const PURCHASE_ORDER_REPOSITORY = 'PURCHASE_ORDER_REPOSITORY';
export const INVENTORY_WAREHOUSE_REPOSITORY = 'INVENTORY_WAREHOUSE_REPOSITORY';
export const STOCK_TRANSFER_REPOSITORY = 'STOCK_TRANSFER_REPOSITORY';
export const STOCK_COUNT_REPOSITORY = 'STOCK_COUNT_REPOSITORY';
export const STOCK_REQUEST_REPOSITORY = 'STOCK_REQUEST_REPOSITORY';
export const INVOICE_REPOSITORY = 'INVOICE_REPOSITORY';
export const COMMISSION_REPOSITORY = 'COMMISSION_REPOSITORY';
export const COMMISSION_RULE_REPOSITORY = 'COMMISSION_RULE_REPOSITORY';
export const LOYALTY_ACCOUNT_REPOSITORY = 'LOYALTY_ACCOUNT_REPOSITORY';
export const LOYALTY_REWARD_REPOSITORY = 'LOYALTY_REWARD_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const REPORT_REPOSITORY = 'REPORT_REPOSITORY';
export const OUTBOX_REPOSITORY = 'OUTBOX_REPOSITORY';
export const QUEUE_REPOSITORY = 'QUEUE_REPOSITORY';

// Analytics Domain Repositories
export const METRIC_REPOSITORY = 'METRIC_REPOSITORY';
export const DASHBOARD_REPOSITORY = 'DASHBOARD_REPOSITORY';
export const ANALYTICS_REPORT_REPOSITORY = 'ANALYTICS_REPORT_REPOSITORY';
export const SUBSCRIPTION_REPOSITORY = 'SUBSCRIPTION_REPOSITORY';
export const WORKFLOW_REPOSITORY = 'WORKFLOW_REPOSITORY';
export const AI_MODEL_REPOSITORY = 'AI_MODEL_REPOSITORY';

// Media Domain
export const MEDIA_ASSET_REPOSITORY = 'MEDIA_ASSET_REPOSITORY';

// Patient Portal Domain
export const PORTAL_ACCOUNT_REPOSITORY = 'PORTAL_ACCOUNT_REPOSITORY';
export const PORTAL_AUDIT_LOG = 'PORTAL_AUDIT_LOG';

// Super Admin Platform Domain
export const PLATFORM_TENANT_REPOSITORY = 'PLATFORM_TENANT_REPOSITORY';
export const PLATFORM_ADMIN_AUDIT_LOG = 'PLATFORM_ADMIN_AUDIT_LOG';

// Auth Domain
export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const LOGIN_ATTEMPT_REPOSITORY = 'LOGIN_ATTEMPT_REPOSITORY';
export const PASSWORD_RESET_TOKEN_REPOSITORY = 'PASSWORD_RESET_TOKEN_REPOSITORY';
export const EMAIL_VERIFICATION_TOKEN_REPOSITORY = 'EMAIL_VERIFICATION_TOKEN_REPOSITORY';
export const MFA_BACKUP_CODE_REPOSITORY = 'MFA_BACKUP_CODE_REPOSITORY';
export const TRUSTED_DEVICE_REPOSITORY = 'TRUSTED_DEVICE_REPOSITORY';
export const JWT_CONFIG = 'JWT_CONFIG';
