import { BRANCH_CONTRIBUTION_SCHEMA_VERSION, type CanonicalBranchSurface } from './branch-types';

const PROVIDER = 'branch.builtin';

export const CANONICAL_BRANCH_WHITE_LABEL_SURFACES: readonly CanonicalBranchSurface[] = [
  {
    surfaceId: 'settings-branch-branding-logo',
    localId: 'branch-branding-logo',
    moduleId: 'settings',
    surface: 'whiteLabel',
    categoryId: 'branch-white-label',
    configurationCategory: 'branch-white-label',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branding#branch-logo',
    deepLinkTemplate: '/settings/branding#branch-logo',
    requiredFeature: 'customBranding',
    labelKey: 'modules.settings.branch.brandingLogo',
    descriptionKey: 'modules.settings.branch.brandingLogoDesc',
    sortOrder: 180,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-branding-accent',
    localId: 'branch-branding-accent',
    moduleId: 'settings',
    surface: 'whiteLabel',
    categoryId: 'branch-white-label',
    configurationCategory: 'branch-white-label',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branding#branch-accent',
    deepLinkTemplate: '/settings/branding#branch-accent',
    requiredFeature: 'customBranding',
    labelKey: 'modules.settings.branch.brandingAccent',
    descriptionKey: 'modules.settings.branch.brandingAccentDesc',
    sortOrder: 190,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-display-name',
    localId: 'branch-display-name',
    moduleId: 'settings',
    surface: 'whiteLabel',
    categoryId: 'branch-white-label',
    configurationCategory: 'branch-white-label',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branding#branch-display-name',
    deepLinkTemplate: '/settings/branding#branch-display-name',
    requiredFeature: 'customBranding',
    labelKey: 'modules.settings.branch.displayName',
    descriptionKey: 'modules.settings.branch.displayNameDesc',
    sortOrder: 200,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-email-sender',
    localId: 'branch-email-sender',
    moduleId: 'settings',
    surface: 'whiteLabel',
    categoryId: 'branch-white-label',
    configurationCategory: 'branch-white-label',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branding#branch-email',
    deepLinkTemplate: '/settings/branding#branch-email',
    requiredFeature: 'whiteLabel',
    labelKey: 'modules.settings.branch.emailSender',
    descriptionKey: 'modules.settings.branch.emailSenderDesc',
    sortOrder: 210,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-pdf-header',
    localId: 'branch-pdf-header',
    moduleId: 'settings',
    surface: 'whiteLabel',
    categoryId: 'branch-white-label',
    configurationCategory: 'branch-white-label',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branding#branch-pdf',
    deepLinkTemplate: '/settings/branding#branch-pdf',
    requiredFeature: 'customBranding',
    labelKey: 'modules.settings.branch.pdfHeader',
    descriptionKey: 'modules.settings.branch.pdfHeaderDesc',
    sortOrder: 220,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-portal-brand',
    localId: 'branch-portal-brand',
    moduleId: 'settings',
    surface: 'whiteLabel',
    categoryId: 'branch-white-label',
    configurationCategory: 'branch-white-label',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branding#branch-portal',
    deepLinkTemplate: '/settings/branding#branch-portal',
    requiredFeature: 'customBranding',
    labelKey: 'modules.settings.branch.portalBrand',
    descriptionKey: 'modules.settings.branch.portalBrandDesc',
    sortOrder: 230,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-login-brand',
    localId: 'branch-login-brand',
    moduleId: 'settings',
    surface: 'whiteLabel',
    categoryId: 'branch-white-label',
    configurationCategory: 'branch-white-label',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branding#branch-login',
    deepLinkTemplate: '/settings/branding#branch-login',
    requiredFeature: 'customBranding',
    labelKey: 'modules.settings.branch.loginBrand',
    descriptionKey: 'modules.settings.branch.loginBrandDesc',
    sortOrder: 240,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_BRANCH_WHITE_LABEL_SURFACE_COUNT = CANONICAL_BRANCH_WHITE_LABEL_SURFACES.length;
