import { BRANCH_CONTRIBUTION_SCHEMA_VERSION, type CanonicalBranchSurface } from './branch-types';

const PROVIDER = 'branch.builtin';

export const CANONICAL_BRANCH_CLINICAL_SURFACES: readonly CanonicalBranchSurface[] = [
  {
    surfaceId: 'scheduling-branch-hours',
    localId: 'branch-hours',
    moduleId: 'scheduling',
    surface: 'clinical',
    categoryId: 'branch-clinical',
    configurationCategory: 'branch-clinical',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.scheduling',
    adminAction: 'update',
    settingsPath: '/settings/scheduling#branch-hours',
    deepLinkTemplate: '/settings/scheduling#branch-hours',
    labelKey: 'modules.scheduling.branch.hours',
    descriptionKey: 'modules.scheduling.branch.hoursDesc',
    sortOrder: 60,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'scheduling-branch-defaults',
    localId: 'branch-defaults',
    moduleId: 'scheduling',
    surface: 'clinical',
    categoryId: 'branch-clinical',
    configurationCategory: 'branch-clinical',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.scheduling',
    adminAction: 'update',
    settingsPath: '/settings/scheduling#branch-defaults',
    deepLinkTemplate: '/settings/scheduling#branch-defaults',
    labelKey: 'modules.scheduling.branch.defaults',
    descriptionKey: 'modules.scheduling.branch.defaultsDesc',
    sortOrder: 70,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'queue-branch-settings',
    localId: 'branch-queue',
    moduleId: 'queue',
    surface: 'clinical',
    categoryId: 'branch-clinical',
    configurationCategory: 'branch-clinical',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.queue',
    adminAction: 'update',
    settingsPath: '/settings/queue#branch',
    deepLinkTemplate: '/settings/queue#branch',
    labelKey: 'modules.queue.branch.settings',
    descriptionKey: 'modules.queue.branch.settingsDesc',
    sortOrder: 80,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_BRANCH_CLINICAL_SURFACE_COUNT = CANONICAL_BRANCH_CLINICAL_SURFACES.length;
