import { BRANCH_CONTRIBUTION_SCHEMA_VERSION, type CanonicalBranchSurface } from './branch-types';

const PROVIDER = 'branch.builtin';

export const CANONICAL_BRANCH_FINANCIAL_SURFACES: readonly CanonicalBranchSurface[] = [
  {
    surfaceId: 'billing-branch-sequences',
    localId: 'branch-sequences',
    moduleId: 'billing',
    surface: 'financial',
    categoryId: 'branch-financial',
    configurationCategory: 'branch-financial',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.billing',
    adminAction: 'update',
    settingsPath: '/settings/billing#branch-sequences',
    deepLinkTemplate: '/settings/billing#branch-sequences',
    labelKey: 'modules.billing.branch.sequences',
    descriptionKey: 'modules.billing.branch.sequencesDesc',
    sortOrder: 90,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'billing-branch-tax',
    localId: 'branch-tax',
    moduleId: 'billing',
    surface: 'financial',
    categoryId: 'branch-financial',
    configurationCategory: 'branch-financial',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.billing',
    adminAction: 'update',
    settingsPath: '/settings/billing#branch-tax',
    deepLinkTemplate: '/settings/billing#branch-tax',
    labelKey: 'modules.billing.branch.tax',
    descriptionKey: 'modules.billing.branch.taxDesc',
    sortOrder: 100,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-financial',
    localId: 'branch-financial',
    moduleId: 'settings',
    surface: 'financial',
    categoryId: 'branch-financial',
    configurationCategory: 'branch-financial',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branches#financial',
    deepLinkTemplate: '/settings/branches#financial',
    labelKey: 'modules.settings.branch.financial',
    descriptionKey: 'modules.settings.branch.financialDesc',
    sortOrder: 110,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_BRANCH_FINANCIAL_SURFACE_COUNT = CANONICAL_BRANCH_FINANCIAL_SURFACES.length;
