import { BRANCH_CONTRIBUTION_SCHEMA_VERSION, type CanonicalBranchSurface } from './branch-types';

const PROVIDER = 'branch.builtin';

export const CANONICAL_BRANCH_IDENTITY_SURFACES: readonly CanonicalBranchSurface[] = [
  {
    surfaceId: 'settings-branch-identity',
    localId: 'branch-identity',
    moduleId: 'settings',
    surface: 'identity',
    categoryId: 'branch-identity',
    configurationCategory: 'branch-identity',
    branchScoped: true,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-override',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    settingsPath: '/settings/branches#identity',
    deepLinkTemplate: '/settings/branches#identity',
    labelKey: 'modules.settings.branch.identity',
    descriptionKey: 'modules.settings.branch.identityDesc',
    sortOrder: 10,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-list',
    localId: 'branch-list',
    moduleId: 'settings',
    surface: 'administration',
    categoryId: 'branch-identity',
    configurationCategory: 'branch-identity',
    branchScoped: false,
    crossBranchAllowed: true,
    inheritanceMode: 'branch-only',
    adminResourceId: 'api.settings',
    adminAction: 'view',
    settingsPath: '/settings/branches',
    deepLinkTemplate: '/settings/branches',
    labelKey: 'modules.settings.branch.list',
    descriptionKey: 'modules.settings.branch.listDesc',
    sortOrder: 20,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branch-create',
    localId: 'branch-create',
    moduleId: 'settings',
    surface: 'administration',
    categoryId: 'branch-identity',
    configurationCategory: 'branch-identity',
    branchScoped: false,
    crossBranchAllowed: false,
    inheritanceMode: 'branch-only',
    adminResourceId: 'api.settings',
    adminAction: 'manage',
    settingsPath: '/settings/branches#create',
    deepLinkTemplate: '/settings/branches#create',
    labelKey: 'modules.settings.branch.create',
    descriptionKey: 'modules.settings.branch.createDesc',
    sortOrder: 30,
    providerKey: PROVIDER,
    schemaVersion: BRANCH_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_BRANCH_IDENTITY_SURFACE_COUNT = CANONICAL_BRANCH_IDENTITY_SURFACES.length;
