import type { CanonicalReportTemplate } from './reporting-types';

/**
 * Canonical report template vocabulary (Phase 33a).
 * SSOT for builtin manifests and STATIC_REPORT_CATALOG.
 *
 * Source of truth is the Phase 33 architecture + current production `REPORT_TEMPLATES` list.
 * No aliases. Stable `reportId` values only.
 */
export const CANONICAL_REPORT_TEMPLATES: CanonicalReportTemplate[] = [
  {
    reportId: 'executive-dashboard',
    moduleId: 'analytics',
    categoryId: 'executive',
    categoryKey: 'reports.executive',
    dataDomain: 'executive',
    titleKey: 'reports.templates.executiveDashboard.title',
    descriptionKey: 'reports.templates.executiveDashboard.desc',
    featured: true,
    tags: ['kpi', 'overview'],
    sortOrder: 0,
    delivery: 'view',
    route: '/analytics?metric=all',
    deepLinkTemplate: '/reports/executive-dashboard',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'executive-export',
    moduleId: 'analytics',
    categoryId: 'executive',
    categoryKey: 'reports.executive',
    dataDomain: 'executive',
    titleKey: 'reports.templates.executiveSummary.title',
    descriptionKey: 'reports.templates.executiveSummary.desc',
    featured: true,
    sortOrder: 10,
    delivery: 'generate',
    deepLinkTemplate: '/reports/executive-export',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'executive',
    defaultFormat: 'pdf',
    supportedFormats: ['pdf', 'excel', 'csv', 'json'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'patient-growth',
    moduleId: 'analytics',
    categoryId: 'patients',
    categoryKey: 'reports.patients',
    dataDomain: 'patients',
    titleKey: 'reports.templates.patientGrowth.title',
    descriptionKey: 'reports.templates.patientGrowth.desc',
    featured: true,
    sortOrder: 20,
    delivery: 'view',
    route: '/analytics?metric=patients',
    deepLinkTemplate: '/reports/patient-growth',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'patient-list-export',
    moduleId: 'analytics',
    categoryId: 'patients',
    categoryKey: 'reports.patients',
    dataDomain: 'patients',
    titleKey: 'reports.templates.patientStatistics.title',
    descriptionKey: 'reports.templates.patientStatistics.desc',
    sortOrder: 30,
    delivery: 'generate',
    deepLinkTemplate: '/reports/patient-list-export',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'clinical',
    defaultFormat: 'excel',
    supportedFormats: ['pdf', 'excel', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'appointment-summary',
    moduleId: 'analytics',
    categoryId: 'appointments',
    categoryKey: 'reports.appointments',
    dataDomain: 'appointments',
    titleKey: 'reports.templates.appointmentSummary.title',
    descriptionKey: 'reports.templates.appointmentSummary.desc',
    featured: true,
    sortOrder: 40,
    delivery: 'view',
    route: '/analytics?metric=appointments',
    deepLinkTemplate: '/reports/appointment-summary',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'scheduling-analytics',
    moduleId: 'scheduling',
    categoryId: 'scheduling',
    categoryKey: 'reports.scheduling',
    dataDomain: 'scheduling',
    titleKey: 'reports.templates.schedulingPerformance.title',
    descriptionKey: 'reports.templates.schedulingPerformance.desc',
    sortOrder: 50,
    delivery: 'view',
    route: '/appointments',
    deepLinkTemplate: '/reports/scheduling-analytics',
    permissionAction: 'view',
    permissionResource: 'api.scheduling',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'queue-performance',
    moduleId: 'queue',
    categoryId: 'queue',
    categoryKey: 'reports.queue',
    dataDomain: 'queue',
    titleKey: 'reports.templates.queuePerformance.title',
    descriptionKey: 'reports.templates.queuePerformance.desc',
    featured: true,
    sortOrder: 60,
    delivery: 'view',
    route: '/queue/analytics',
    deepLinkTemplate: '/reports/queue-performance',
    permissionAction: 'view',
    permissionResource: 'api.queue',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'clinical-activity',
    moduleId: 'analytics',
    categoryId: 'emr',
    categoryKey: 'reports.emr',
    dataDomain: 'emr',
    titleKey: 'reports.templates.clinicalActivity.title',
    descriptionKey: 'reports.templates.clinicalActivity.desc',
    sortOrder: 70,
    delivery: 'generate',
    deepLinkTemplate: '/reports/clinical-activity',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'clinical',
    defaultFormat: 'pdf',
    supportedFormats: ['pdf', 'excel', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'dental-treatment-plans',
    moduleId: 'dental',
    categoryId: 'dental',
    categoryKey: 'reports.dental',
    dataDomain: 'dental',
    titleKey: 'reports.templates.dentalProcedures.title',
    descriptionKey: 'reports.templates.dentalProcedures.desc',
    sortOrder: 80,
    delivery: 'view',
    route: '/dental/treatment-plans',
    deepLinkTemplate: '/reports/dental-treatment-plans',
    permissionAction: 'view',
    permissionResource: 'api.dental',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'beauty-sessions',
    moduleId: 'beauty',
    categoryId: 'beauty',
    categoryKey: 'reports.beauty',
    dataDomain: 'beauty',
    titleKey: 'reports.templates.beautySessions.title',
    descriptionKey: 'reports.templates.beautySessions.desc',
    sortOrder: 90,
    delivery: 'view',
    route: '/beauty',
    deepLinkTemplate: '/reports/beauty-sessions',
    permissionAction: 'view',
    permissionResource: 'api.beauty',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'inventory-status',
    moduleId: 'inventory',
    categoryId: 'inventory',
    categoryKey: 'reports.inventory',
    dataDomain: 'inventory',
    titleKey: 'reports.templates.inventoryStatus.title',
    descriptionKey: 'reports.templates.inventoryStatus.desc',
    featured: true,
    sortOrder: 100,
    delivery: 'view',
    route: '/inventory/reports',
    deepLinkTemplate: '/reports/inventory-status',
    permissionAction: 'view',
    permissionResource: 'api.inventory',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'inventory-analytics-export',
    moduleId: 'inventory',
    categoryId: 'inventory',
    categoryKey: 'reports.inventory',
    dataDomain: 'inventory',
    titleKey: 'reports.templates.inventoryConsumption.title',
    descriptionKey: 'reports.templates.inventoryConsumption.desc',
    sortOrder: 110,
    delivery: 'export',
    route: '/inventory/reports',
    deepLinkTemplate: '/reports/inventory-analytics-export',
    permissionAction: 'export',
    permissionResource: 'api.inventory',
    exportFormats: ['pdf', 'csv', 'xlsx'],
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'billing-summary',
    moduleId: 'billing',
    categoryId: 'billing',
    categoryKey: 'reports.billing',
    dataDomain: 'billing',
    titleKey: 'reports.templates.billingSummary.title',
    descriptionKey: 'reports.templates.billingSummary.desc',
    featured: true,
    sortOrder: 120,
    delivery: 'view',
    route: '/billing/reports',
    deepLinkTemplate: '/reports/billing-summary',
    permissionAction: 'view',
    permissionResource: 'api.billing',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'outstanding-invoices',
    moduleId: 'billing',
    categoryId: 'finance',
    categoryKey: 'reports.finance',
    dataDomain: 'billing',
    titleKey: 'reports.templates.outstandingInvoices.title',
    descriptionKey: 'reports.templates.outstandingInvoices.desc',
    featured: true,
    sortOrder: 130,
    delivery: 'view',
    route: '/billing/outstanding',
    deepLinkTemplate: '/reports/outstanding-invoices',
    permissionAction: 'view',
    permissionResource: 'api.billing',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'revenue-summary',
    moduleId: 'analytics',
    categoryId: 'revenue',
    categoryKey: 'reports.revenue',
    dataDomain: 'revenue',
    titleKey: 'reports.templates.revenueSummary.title',
    descriptionKey: 'reports.templates.revenueSummary.desc',
    featured: true,
    sortOrder: 140,
    delivery: 'view',
    route: '/analytics?metric=revenue',
    deepLinkTemplate: '/reports/revenue-summary',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'financial-export',
    moduleId: 'analytics',
    categoryId: 'finance',
    categoryKey: 'reports.finance',
    dataDomain: 'finance',
    titleKey: 'reports.templates.financialSummary.title',
    descriptionKey: 'reports.templates.financialSummary.desc',
    sortOrder: 150,
    delivery: 'generate',
    deepLinkTemplate: '/reports/financial-export',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'financial',
    defaultFormat: 'excel',
    supportedFormats: ['pdf', 'excel', 'csv', 'json'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'commission-summary',
    moduleId: 'commission',
    categoryId: 'commission',
    categoryKey: 'reports.commission',
    dataDomain: 'commission',
    titleKey: 'reports.templates.commissionSummary.title',
    descriptionKey: 'reports.templates.commissionSummary.desc',
    sortOrder: 160,
    delivery: 'view',
    route: '/billing/commissions',
    deepLinkTemplate: '/reports/commission-summary',
    permissionAction: 'view',
    permissionResource: 'api.commission',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'operational-export',
    moduleId: 'analytics',
    categoryId: 'operations',
    categoryKey: 'reports.operations',
    dataDomain: 'operations',
    titleKey: 'reports.templates.operationsSummary.title',
    descriptionKey: 'reports.templates.operationsSummary.desc',
    sortOrder: 170,
    delivery: 'generate',
    deepLinkTemplate: '/reports/operational-export',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'operational',
    defaultFormat: 'pdf',
    supportedFormats: ['pdf', 'excel', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'custom-report',
    moduleId: 'analytics',
    categoryId: 'custom',
    categoryKey: 'reports.custom',
    dataDomain: 'custom',
    titleKey: 'reports.templates.customReport.title',
    descriptionKey: 'reports.templates.customReport.desc',
    sortOrder: 180,
    delivery: 'generate',
    deepLinkTemplate: '/reports/custom-report',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'custom',
    defaultFormat: 'excel',
    supportedFormats: ['pdf', 'excel', 'csv', 'json'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'doctor-productivity',
    moduleId: 'analytics',
    categoryId: 'staff',
    categoryKey: 'reports.staff',
    dataDomain: 'staff',
    titleKey: 'reports.templates.doctorProductivity.title',
    descriptionKey: 'reports.templates.doctorProductivity.desc',
    tags: ['doctor', 'productivity'],
    sortOrder: 190,
    delivery: 'view',
    route: '/analytics?metric=appointments',
    deepLinkTemplate: '/reports/doctor-productivity',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'department-performance',
    moduleId: 'analytics',
    categoryId: 'staff',
    categoryKey: 'reports.staff',
    dataDomain: 'staff',
    titleKey: 'reports.templates.departmentPerformance.title',
    descriptionKey: 'reports.templates.departmentPerformance.desc',
    sortOrder: 200,
    delivery: 'generate',
    deepLinkTemplate: '/reports/department-performance',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'operational',
    defaultFormat: 'pdf',
    supportedFormats: ['pdf', 'excel', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'branch-performance',
    moduleId: 'analytics',
    categoryId: 'operations',
    categoryKey: 'reports.operations',
    dataDomain: 'operations',
    titleKey: 'reports.templates.branchPerformance.title',
    descriptionKey: 'reports.templates.branchPerformance.desc',
    tags: ['branch'],
    sortOrder: 210,
    delivery: 'view',
    route: '/',
    deepLinkTemplate: '/reports/branch-performance',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'low-stock',
    moduleId: 'inventory',
    categoryId: 'inventory',
    categoryKey: 'reports.inventory',
    dataDomain: 'inventory',
    titleKey: 'reports.templates.lowStock.title',
    descriptionKey: 'reports.templates.lowStock.desc',
    sortOrder: 220,
    delivery: 'view',
    route: '/inventory/catalog?stock=low',
    deepLinkTemplate: '/reports/low-stock',
    permissionAction: 'view',
    permissionResource: 'api.inventory',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'expiring-products',
    moduleId: 'inventory',
    categoryId: 'inventory',
    categoryKey: 'reports.inventory',
    dataDomain: 'inventory',
    titleKey: 'reports.templates.expiringProducts.title',
    descriptionKey: 'reports.templates.expiringProducts.desc',
    sortOrder: 230,
    delivery: 'view',
    route: '/inventory/expiry',
    deepLinkTemplate: '/reports/expiring-products',
    permissionAction: 'view',
    permissionResource: 'api.inventory',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'supplier-performance',
    moduleId: 'inventory',
    categoryId: 'inventory',
    categoryKey: 'reports.inventory',
    dataDomain: 'inventory',
    titleKey: 'reports.templates.supplierPerformance.title',
    descriptionKey: 'reports.templates.supplierPerformance.desc',
    sortOrder: 240,
    delivery: 'view',
    route: '/inventory/suppliers',
    deepLinkTemplate: '/reports/supplier-performance',
    permissionAction: 'view',
    permissionResource: 'api.inventory',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'cash-flow',
    moduleId: 'billing',
    categoryId: 'finance',
    categoryKey: 'reports.finance',
    dataDomain: 'finance',
    titleKey: 'reports.templates.cashFlow.title',
    descriptionKey: 'reports.templates.cashFlow.desc',
    sortOrder: 250,
    delivery: 'view',
    route: '/billing/cashbox',
    deepLinkTemplate: '/reports/cash-flow',
    permissionAction: 'view',
    permissionResource: 'api.billing',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'payment-collection',
    moduleId: 'billing',
    categoryId: 'billing',
    categoryKey: 'reports.billing',
    dataDomain: 'billing',
    titleKey: 'reports.templates.paymentCollection.title',
    descriptionKey: 'reports.templates.paymentCollection.desc',
    sortOrder: 260,
    delivery: 'view',
    route: '/billing',
    deepLinkTemplate: '/reports/payment-collection',
    permissionAction: 'view',
    permissionResource: 'api.billing',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'subscription-overview',
    moduleId: 'analytics',
    categoryId: 'subscriptions',
    categoryKey: 'reports.subscriptions',
    dataDomain: 'subscriptions',
    titleKey: 'reports.templates.subscriptionOverview.title',
    descriptionKey: 'reports.templates.subscriptionOverview.desc',
    sortOrder: 270,
    delivery: 'generate',
    deepLinkTemplate: '/reports/subscription-overview',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'financial',
    defaultFormat: 'excel',
    supportedFormats: ['pdf', 'excel', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'treatment-plans',
    moduleId: 'dental',
    categoryId: 'dental',
    categoryKey: 'reports.dental',
    dataDomain: 'dental',
    titleKey: 'reports.templates.treatmentPlans.title',
    descriptionKey: 'reports.templates.treatmentPlans.desc',
    sortOrder: 280,
    delivery: 'view',
    route: '/dental',
    deepLinkTemplate: '/reports/treatment-plans',
    permissionAction: 'view',
    permissionResource: 'api.dental',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'security-audit',
    moduleId: 'reporting',
    categoryId: 'audit',
    categoryKey: 'reports.audit',
    dataDomain: 'audit',
    titleKey: 'reports.templates.securityAudit.title',
    descriptionKey: 'reports.templates.securityAudit.desc',
    sortOrder: 290,
    delivery: 'generate',
    deepLinkTemplate: '/reports/security-audit',
    permissionAction: 'create',
    permissionResource: 'api.reporting',
    featureId: 'reports',
    analyticsType: 'operational',
    defaultFormat: 'pdf',
    supportedFormats: ['pdf', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'user-activity',
    moduleId: 'settings',
    categoryId: 'audit',
    categoryKey: 'reports.audit',
    dataDomain: 'audit',
    titleKey: 'reports.templates.userActivity.title',
    descriptionKey: 'reports.templates.userActivity.desc',
    sortOrder: 300,
    delivery: 'view',
    route: '/settings/security/sessions',
    deepLinkTemplate: '/reports/user-activity',
    permissionAction: 'view',
    permissionResource: 'api.auth',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'appointment-export',
    moduleId: 'reporting',
    categoryId: 'appointments',
    categoryKey: 'reports.appointments',
    dataDomain: 'appointments',
    titleKey: 'reports.templates.appointmentExport.title',
    descriptionKey: 'reports.templates.appointmentExport.desc',
    sortOrder: 310,
    delivery: 'generate',
    deepLinkTemplate: '/reports/appointment-export',
    permissionAction: 'create',
    permissionResource: 'api.reporting',
    featureId: 'reports',
    analyticsType: 'operational',
    defaultFormat: 'excel',
    supportedFormats: ['pdf', 'excel', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'patient-export',
    moduleId: 'reporting',
    categoryId: 'patients',
    categoryKey: 'reports.patients',
    dataDomain: 'patients',
    titleKey: 'reports.templates.patientExport.title',
    descriptionKey: 'reports.templates.patientExport.desc',
    sortOrder: 320,
    delivery: 'generate',
    deepLinkTemplate: '/reports/patient-export',
    permissionAction: 'create',
    permissionResource: 'api.reporting',
    featureId: 'reports',
    analyticsType: 'clinical',
    defaultFormat: 'csv',
    supportedFormats: ['pdf', 'excel', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'revenue-export',
    moduleId: 'analytics',
    categoryId: 'revenue',
    categoryKey: 'reports.revenue',
    dataDomain: 'revenue',
    titleKey: 'reports.templates.revenueExport.title',
    descriptionKey: 'reports.templates.revenueExport.desc',
    sortOrder: 330,
    delivery: 'generate',
    deepLinkTemplate: '/reports/revenue-export',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'financial',
    defaultFormat: 'excel',
    supportedFormats: ['pdf', 'excel', 'csv', 'json'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'notification-delivery',
    moduleId: 'reporting',
    categoryId: 'notifications',
    categoryKey: 'reports.notifications',
    dataDomain: 'notifications',
    titleKey: 'reports.templates.notificationDelivery.title',
    descriptionKey: 'reports.templates.notificationDelivery.desc',
    sortOrder: 340,
    delivery: 'generate',
    deepLinkTemplate: '/reports/notification-delivery',
    permissionAction: 'create',
    permissionResource: 'api.reporting',
    featureId: 'reports',
    analyticsType: 'operational',
    defaultFormat: 'csv',
    supportedFormats: ['csv', 'excel', 'pdf'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'notification-failures',
    moduleId: 'notifications',
    categoryId: 'notifications',
    categoryKey: 'reports.notifications',
    dataDomain: 'notifications',
    titleKey: 'reports.templates.notificationFailures.title',
    descriptionKey: 'reports.templates.notificationFailures.desc',
    sortOrder: 350,
    delivery: 'view',
    route: '/settings/notifications/delivery',
    deepLinkTemplate: '/reports/notification-failures',
    permissionAction: 'view',
    permissionResource: 'api.notifications',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'platform-tenants',
    moduleId: 'settings',
    categoryId: 'platform',
    categoryKey: 'reports.platform',
    dataDomain: 'platform',
    titleKey: 'reports.templates.platformTenants.title',
    descriptionKey: 'reports.templates.platformTenants.desc',
    sortOrder: 360,
    delivery: 'view',
    route: '/platform-admin',
    deepLinkTemplate: '/reports/platform-tenants',
    permissionAction: 'view',
    permissionResource: 'api.platform-admin',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'platform-usage',
    moduleId: 'settings',
    categoryId: 'platform',
    categoryKey: 'reports.platform',
    dataDomain: 'platform',
    titleKey: 'reports.templates.platformUsage.title',
    descriptionKey: 'reports.templates.platformUsage.desc',
    sortOrder: 370,
    delivery: 'generate',
    deepLinkTemplate: '/reports/platform-usage',
    permissionAction: 'view',
    permissionResource: 'api.platform-admin',
    analyticsType: 'executive',
    defaultFormat: 'pdf',
    supportedFormats: ['pdf', 'excel', 'csv'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'system-usage',
    moduleId: 'analytics',
    categoryId: 'system',
    categoryKey: 'reports.system',
    dataDomain: 'system',
    titleKey: 'reports.templates.systemUsage.title',
    descriptionKey: 'reports.templates.systemUsage.desc',
    sortOrder: 380,
    delivery: 'generate',
    deepLinkTemplate: '/reports/system-usage',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    analyticsType: 'operational',
    defaultFormat: 'csv',
    supportedFormats: ['csv', 'json'],
    scheduleAllowed: true,
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'api-audit-log',
    moduleId: 'settings',
    categoryId: 'system',
    categoryKey: 'reports.system',
    dataDomain: 'audit',
    titleKey: 'reports.templates.apiAuditLog.title',
    descriptionKey: 'reports.templates.apiAuditLog.desc',
    sortOrder: 390,
    delivery: 'view',
    route: '/settings/audit',
    deepLinkTemplate: '/reports/api-audit-log',
    permissionAction: 'view',
    permissionResource: 'api.audit',
    providerKey: 'reporting.builtin',
  },
];

export const CANONICAL_REPORT_TEMPLATE_COUNT = CANONICAL_REPORT_TEMPLATES.length;

