import type { CanonicalReportHub } from './reporting-types';

export const CANONICAL_REPORT_HUBS: CanonicalReportHub[] = [
  {
    reportId: 'catalog',
    moduleId: 'reporting',
    categoryId: 'platform',
    categoryKey: 'platform.reporting',
    dataDomain: 'reporting',
    titleKey: 'modules.reporting.catalog',
    descriptionKey: 'modules.reporting.catalog',
    sortOrder: 0,
    delivery: 'view',
    route: '/reports',
    deepLinkTemplate: '/reports',
    permissionAction: 'view',
    permissionResource: 'api.reporting',
    permissionResources: ['api.reporting', 'api.analytics', 'api.billing', 'api.inventory'],
    featureId: 'reports',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'builder',
    moduleId: 'reporting',
    categoryId: 'custom',
    categoryKey: 'platform.reporting',
    dataDomain: 'reporting',
    titleKey: 'modules.reporting.builder',
    descriptionKey: 'modules.reporting.builder',
    sortOrder: 10,
    delivery: 'view',
    route: '/reports/builder',
    deepLinkTemplate: '/reports/builder',
    permissionAction: 'create',
    permissionResource: 'api.reporting',
    permissionResources: ['api.reporting', 'api.analytics'],
    featureId: 'reports',
    providerKey: 'reporting.builtin',
  },
  {
    reportId: 'export-center',
    moduleId: 'reporting',
    categoryId: 'operations',
    categoryKey: 'platform.reporting',
    dataDomain: 'reporting',
    titleKey: 'modules.reporting.exportCenter',
    descriptionKey: 'modules.reporting.exportCenter',
    sortOrder: 20,
    delivery: 'view',
    route: '/reports/export',
    deepLinkTemplate: '/reports/export',
    permissionAction: 'export',
    permissionResource: 'api.reporting',
    permissionResources: ['api.reporting', 'api.analytics'],
    featureId: 'reports',
    providerKey: 'reporting.builtin',
  },
];

export const CANONICAL_REPORT_HUB_COUNT = CANONICAL_REPORT_HUBS.length;

