-- ============================================================
-- Permission System Seeds
-- Generated: 2026-06-15T19:50:36.293Z
-- Matrix version: 2026-06-15.enterprise.v2
-- ============================================================

-- Roles
INSERT INTO "Role" (key, name, description) VALUES
  ('super_admin', 'Super Admin', 'Full platform access — cross-tenant control plane'),
  ('owner', 'Owner', 'Clinic owner — full access within tenant'),
  ('general_manager', 'General Manager', 'General manager — operational control within tenant'),
  ('doctor', 'Doctor', 'Licensed physician — clinical access'),
  ('dentist', 'Dentist', 'Licensed dentist — dental clinical access'),
  ('specialist', 'Specialist', 'Specialist clinician — specialized clinical access'),
  ('nurse', 'Nurse', 'Nursing staff — care coordination access'),
  ('assistant', 'Assistant', 'Clinical/administrative assistant'),
  ('receptionist', 'Receptionist', 'Front-desk reception — scheduling and check-in'),
  ('accountant', 'Accountant', 'Finance and billing management'),
  ('inventory_manager', 'Inventory Manager', 'Inventory and supply chain management'),
  ('patient', 'Patient', 'Self-service patient portal access')
ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

-- Permissions (resource × action)
INSERT INTO "Permission" (id, resource, action, resource_kind, resource_name) VALUES
  ('api.identity:view', 'api.identity', 'view', 'api', 'Identity / User Management API'),
  ('api.identity:create', 'api.identity', 'create', 'api', 'Identity / User Management API'),
  ('api.identity:update', 'api.identity', 'update', 'api', 'Identity / User Management API'),
  ('api.identity:delete', 'api.identity', 'delete', 'api', 'Identity / User Management API'),
  ('api.identity:approve', 'api.identity', 'approve', 'api', 'Identity / User Management API'),
  ('api.identity:export', 'api.identity', 'export', 'api', 'Identity / User Management API'),
  ('api.identity:manage', 'api.identity', 'manage', 'api', 'Identity / User Management API'),
  ('api.patients:view', 'api.patients', 'view', 'api', 'Patients API'),
  ('api.patients:create', 'api.patients', 'create', 'api', 'Patients API'),
  ('api.patients:update', 'api.patients', 'update', 'api', 'Patients API'),
  ('api.patients:delete', 'api.patients', 'delete', 'api', 'Patients API'),
  ('api.patients:approve', 'api.patients', 'approve', 'api', 'Patients API'),
  ('api.patients:export', 'api.patients', 'export', 'api', 'Patients API'),
  ('api.patients:manage', 'api.patients', 'manage', 'api', 'Patients API'),
  ('api.scheduling:view', 'api.scheduling', 'view', 'api', 'Scheduling / Appointments API'),
  ('api.scheduling:create', 'api.scheduling', 'create', 'api', 'Scheduling / Appointments API'),
  ('api.scheduling:update', 'api.scheduling', 'update', 'api', 'Scheduling / Appointments API'),
  ('api.scheduling:delete', 'api.scheduling', 'delete', 'api', 'Scheduling / Appointments API'),
  ('api.scheduling:approve', 'api.scheduling', 'approve', 'api', 'Scheduling / Appointments API'),
  ('api.scheduling:export', 'api.scheduling', 'export', 'api', 'Scheduling / Appointments API'),
  ('api.scheduling:manage', 'api.scheduling', 'manage', 'api', 'Scheduling / Appointments API'),
  ('api.queue:view', 'api.queue', 'view', 'api', 'Queue API'),
  ('api.queue:create', 'api.queue', 'create', 'api', 'Queue API'),
  ('api.queue:update', 'api.queue', 'update', 'api', 'Queue API'),
  ('api.queue:delete', 'api.queue', 'delete', 'api', 'Queue API'),
  ('api.queue:approve', 'api.queue', 'approve', 'api', 'Queue API'),
  ('api.queue:export', 'api.queue', 'export', 'api', 'Queue API'),
  ('api.queue:manage', 'api.queue', 'manage', 'api', 'Queue API'),
  ('api.emr:view', 'api.emr', 'view', 'api', 'EMR / Encounters API'),
  ('api.emr:create', 'api.emr', 'create', 'api', 'EMR / Encounters API'),
  ('api.emr:update', 'api.emr', 'update', 'api', 'EMR / Encounters API'),
  ('api.emr:delete', 'api.emr', 'delete', 'api', 'EMR / Encounters API'),
  ('api.emr:approve', 'api.emr', 'approve', 'api', 'EMR / Encounters API'),
  ('api.emr:export', 'api.emr', 'export', 'api', 'EMR / Encounters API'),
  ('api.emr:manage', 'api.emr', 'manage', 'api', 'EMR / Encounters API'),
  ('api.dental:view', 'api.dental', 'view', 'api', 'Dental API'),
  ('api.dental:create', 'api.dental', 'create', 'api', 'Dental API'),
  ('api.dental:update', 'api.dental', 'update', 'api', 'Dental API'),
  ('api.dental:delete', 'api.dental', 'delete', 'api', 'Dental API'),
  ('api.dental:approve', 'api.dental', 'approve', 'api', 'Dental API'),
  ('api.dental:export', 'api.dental', 'export', 'api', 'Dental API'),
  ('api.dental:manage', 'api.dental', 'manage', 'api', 'Dental API'),
  ('api.beauty:view', 'api.beauty', 'view', 'api', 'Beauty / Aesthetic Services API'),
  ('api.beauty:create', 'api.beauty', 'create', 'api', 'Beauty / Aesthetic Services API'),
  ('api.beauty:update', 'api.beauty', 'update', 'api', 'Beauty / Aesthetic Services API'),
  ('api.beauty:delete', 'api.beauty', 'delete', 'api', 'Beauty / Aesthetic Services API'),
  ('api.beauty:approve', 'api.beauty', 'approve', 'api', 'Beauty / Aesthetic Services API'),
  ('api.beauty:export', 'api.beauty', 'export', 'api', 'Beauty / Aesthetic Services API'),
  ('api.beauty:manage', 'api.beauty', 'manage', 'api', 'Beauty / Aesthetic Services API'),
  ('api.inventory:view', 'api.inventory', 'view', 'api', 'Inventory API'),
  ('api.inventory:create', 'api.inventory', 'create', 'api', 'Inventory API'),
  ('api.inventory:update', 'api.inventory', 'update', 'api', 'Inventory API'),
  ('api.inventory:delete', 'api.inventory', 'delete', 'api', 'Inventory API'),
  ('api.inventory:approve', 'api.inventory', 'approve', 'api', 'Inventory API'),
  ('api.inventory:export', 'api.inventory', 'export', 'api', 'Inventory API'),
  ('api.inventory:manage', 'api.inventory', 'manage', 'api', 'Inventory API'),
  ('api.billing:view', 'api.billing', 'view', 'api', 'Billing / Invoices API'),
  ('api.billing:create', 'api.billing', 'create', 'api', 'Billing / Invoices API'),
  ('api.billing:update', 'api.billing', 'update', 'api', 'Billing / Invoices API'),
  ('api.billing:delete', 'api.billing', 'delete', 'api', 'Billing / Invoices API'),
  ('api.billing:approve', 'api.billing', 'approve', 'api', 'Billing / Invoices API'),
  ('api.billing:export', 'api.billing', 'export', 'api', 'Billing / Invoices API'),
  ('api.billing:manage', 'api.billing', 'manage', 'api', 'Billing / Invoices API'),
  ('api.commission:view', 'api.commission', 'view', 'api', 'Commission API'),
  ('api.commission:create', 'api.commission', 'create', 'api', 'Commission API'),
  ('api.commission:update', 'api.commission', 'update', 'api', 'Commission API'),
  ('api.commission:delete', 'api.commission', 'delete', 'api', 'Commission API'),
  ('api.commission:approve', 'api.commission', 'approve', 'api', 'Commission API'),
  ('api.commission:export', 'api.commission', 'export', 'api', 'Commission API'),
  ('api.commission:manage', 'api.commission', 'manage', 'api', 'Commission API'),
  ('api.subscription:view', 'api.subscription', 'view', 'api', 'Subscription API'),
  ('api.subscription:create', 'api.subscription', 'create', 'api', 'Subscription API'),
  ('api.subscription:update', 'api.subscription', 'update', 'api', 'Subscription API'),
  ('api.subscription:delete', 'api.subscription', 'delete', 'api', 'Subscription API'),
  ('api.subscription:approve', 'api.subscription', 'approve', 'api', 'Subscription API'),
  ('api.subscription:export', 'api.subscription', 'export', 'api', 'Subscription API'),
  ('api.subscription:manage', 'api.subscription', 'manage', 'api', 'Subscription API'),
  ('api.notifications:view', 'api.notifications', 'view', 'api', 'Notifications API'),
  ('api.notifications:create', 'api.notifications', 'create', 'api', 'Notifications API'),
  ('api.notifications:update', 'api.notifications', 'update', 'api', 'Notifications API'),
  ('api.notifications:delete', 'api.notifications', 'delete', 'api', 'Notifications API'),
  ('api.notifications:approve', 'api.notifications', 'approve', 'api', 'Notifications API'),
  ('api.notifications:export', 'api.notifications', 'export', 'api', 'Notifications API'),
  ('api.notifications:manage', 'api.notifications', 'manage', 'api', 'Notifications API'),
  ('api.audit:view', 'api.audit', 'view', 'api', 'Audit Log API'),
  ('api.audit:create', 'api.audit', 'create', 'api', 'Audit Log API'),
  ('api.audit:update', 'api.audit', 'update', 'api', 'Audit Log API'),
  ('api.audit:delete', 'api.audit', 'delete', 'api', 'Audit Log API'),
  ('api.audit:approve', 'api.audit', 'approve', 'api', 'Audit Log API'),
  ('api.audit:export', 'api.audit', 'export', 'api', 'Audit Log API'),
  ('api.audit:manage', 'api.audit', 'manage', 'api', 'Audit Log API'),
  ('api.loyalty:view', 'api.loyalty', 'view', 'api', 'Loyalty API'),
  ('api.loyalty:create', 'api.loyalty', 'create', 'api', 'Loyalty API'),
  ('api.loyalty:update', 'api.loyalty', 'update', 'api', 'Loyalty API'),
  ('api.loyalty:delete', 'api.loyalty', 'delete', 'api', 'Loyalty API'),
  ('api.loyalty:approve', 'api.loyalty', 'approve', 'api', 'Loyalty API'),
  ('api.loyalty:export', 'api.loyalty', 'export', 'api', 'Loyalty API'),
  ('api.loyalty:manage', 'api.loyalty', 'manage', 'api', 'Loyalty API'),
  ('api.reporting:view', 'api.reporting', 'view', 'report', 'Reporting API'),
  ('api.reporting:create', 'api.reporting', 'create', 'report', 'Reporting API'),
  ('api.reporting:update', 'api.reporting', 'update', 'report', 'Reporting API'),
  ('api.reporting:delete', 'api.reporting', 'delete', 'report', 'Reporting API'),
  ('api.reporting:approve', 'api.reporting', 'approve', 'report', 'Reporting API'),
  ('api.reporting:export', 'api.reporting', 'export', 'report', 'Reporting API'),
  ('api.reporting:manage', 'api.reporting', 'manage', 'report', 'Reporting API'),
  ('api.analytics:view', 'api.analytics', 'view', 'report', 'Analytics API'),
  ('api.analytics:create', 'api.analytics', 'create', 'report', 'Analytics API'),
  ('api.analytics:update', 'api.analytics', 'update', 'report', 'Analytics API'),
  ('api.analytics:delete', 'api.analytics', 'delete', 'report', 'Analytics API'),
  ('api.analytics:approve', 'api.analytics', 'approve', 'report', 'Analytics API'),
  ('api.analytics:export', 'api.analytics', 'export', 'report', 'Analytics API'),
  ('api.analytics:manage', 'api.analytics', 'manage', 'report', 'Analytics API'),
  ('api.workflow:view', 'api.workflow', 'view', 'operation', 'Workflow API'),
  ('api.workflow:create', 'api.workflow', 'create', 'operation', 'Workflow API'),
  ('api.workflow:update', 'api.workflow', 'update', 'operation', 'Workflow API'),
  ('api.workflow:delete', 'api.workflow', 'delete', 'operation', 'Workflow API'),
  ('api.workflow:approve', 'api.workflow', 'approve', 'operation', 'Workflow API'),
  ('api.workflow:export', 'api.workflow', 'export', 'operation', 'Workflow API'),
  ('api.workflow:manage', 'api.workflow', 'manage', 'operation', 'Workflow API'),
  ('api.ai:view', 'api.ai', 'view', 'operation', 'AI Models API'),
  ('api.ai:create', 'api.ai', 'create', 'operation', 'AI Models API'),
  ('api.ai:update', 'api.ai', 'update', 'operation', 'AI Models API'),
  ('api.ai:delete', 'api.ai', 'delete', 'operation', 'AI Models API'),
  ('api.ai:approve', 'api.ai', 'approve', 'operation', 'AI Models API'),
  ('api.ai:export', 'api.ai', 'export', 'operation', 'AI Models API'),
  ('api.ai:manage', 'api.ai', 'manage', 'operation', 'AI Models API'),
  ('api.patient_portal:view', 'api.patient_portal', 'view', 'api', 'Patient Portal API'),
  ('api.patient_portal:create', 'api.patient_portal', 'create', 'api', 'Patient Portal API'),
  ('api.patient_portal:update', 'api.patient_portal', 'update', 'api', 'Patient Portal API'),
  ('api.patient_portal:delete', 'api.patient_portal', 'delete', 'api', 'Patient Portal API'),
  ('api.patient_portal:approve', 'api.patient_portal', 'approve', 'api', 'Patient Portal API'),
  ('api.patient_portal:export', 'api.patient_portal', 'export', 'api', 'Patient Portal API'),
  ('api.patient_portal:manage', 'api.patient_portal', 'manage', 'api', 'Patient Portal API'),
  ('api.platform_admin:view', 'api.platform_admin', 'view', 'operation', 'Platform Admin API'),
  ('api.platform_admin:create', 'api.platform_admin', 'create', 'operation', 'Platform Admin API'),
  ('api.platform_admin:update', 'api.platform_admin', 'update', 'operation', 'Platform Admin API'),
  ('api.platform_admin:delete', 'api.platform_admin', 'delete', 'operation', 'Platform Admin API'),
  ('api.platform_admin:approve', 'api.platform_admin', 'approve', 'operation', 'Platform Admin API'),
  ('api.platform_admin:export', 'api.platform_admin', 'export', 'operation', 'Platform Admin API'),
  ('api.platform_admin:manage', 'api.platform_admin', 'manage', 'operation', 'Platform Admin API'),
  ('api.tenant:view', 'api.tenant', 'view', 'api', 'Tenant API'),
  ('api.tenant:create', 'api.tenant', 'create', 'api', 'Tenant API'),
  ('api.tenant:update', 'api.tenant', 'update', 'api', 'Tenant API'),
  ('api.tenant:delete', 'api.tenant', 'delete', 'api', 'Tenant API'),
  ('api.tenant:approve', 'api.tenant', 'approve', 'api', 'Tenant API'),
  ('api.tenant:export', 'api.tenant', 'export', 'api', 'Tenant API'),
  ('api.tenant:manage', 'api.tenant', 'manage', 'api', 'Tenant API')
ON CONFLICT (id) DO UPDATE SET resource_name = EXCLUDED.resource_name;

-- Role ↔ Permission assignments
INSERT INTO "RolePermission" (role_key, permission_id) VALUES
  ('super_admin', 'api.identity:view'),
  ('owner', 'api.identity:view'),
  ('general_manager', 'api.identity:view'),
  ('super_admin', 'api.identity:create'),
  ('owner', 'api.identity:create'),
  ('general_manager', 'api.identity:create'),
  ('super_admin', 'api.identity:update'),
  ('owner', 'api.identity:update'),
  ('super_admin', 'api.identity:delete'),
  ('super_admin', 'api.identity:approve'),
  ('owner', 'api.identity:approve'),
  ('super_admin', 'api.identity:export'),
  ('owner', 'api.identity:export'),
  ('super_admin', 'api.identity:manage'),
  ('owner', 'api.identity:manage'),
  ('super_admin', 'api.patients:view'),
  ('owner', 'api.patients:view'),
  ('general_manager', 'api.patients:view'),
  ('doctor', 'api.patients:view'),
  ('dentist', 'api.patients:view'),
  ('specialist', 'api.patients:view'),
  ('nurse', 'api.patients:view'),
  ('assistant', 'api.patients:view'),
  ('receptionist', 'api.patients:view'),
  ('super_admin', 'api.patients:create'),
  ('owner', 'api.patients:create'),
  ('general_manager', 'api.patients:create'),
  ('receptionist', 'api.patients:create'),
  ('assistant', 'api.patients:create'),
  ('super_admin', 'api.patients:update'),
  ('owner', 'api.patients:update'),
  ('general_manager', 'api.patients:update'),
  ('doctor', 'api.patients:update'),
  ('dentist', 'api.patients:update'),
  ('specialist', 'api.patients:update'),
  ('nurse', 'api.patients:update'),
  ('assistant', 'api.patients:update'),
  ('receptionist', 'api.patients:update'),
  ('super_admin', 'api.patients:delete'),
  ('owner', 'api.patients:delete'),
  ('super_admin', 'api.patients:approve'),
  ('owner', 'api.patients:approve'),
  ('general_manager', 'api.patients:approve'),
  ('super_admin', 'api.patients:export'),
  ('owner', 'api.patients:export'),
  ('general_manager', 'api.patients:export'),
  ('doctor', 'api.patients:export'),
  ('dentist', 'api.patients:export'),
  ('specialist', 'api.patients:export'),
  ('super_admin', 'api.patients:manage'),
  ('owner', 'api.patients:manage'),
  ('general_manager', 'api.patients:manage'),
  ('super_admin', 'api.scheduling:view'),
  ('owner', 'api.scheduling:view'),
  ('general_manager', 'api.scheduling:view'),
  ('doctor', 'api.scheduling:view'),
  ('dentist', 'api.scheduling:view'),
  ('specialist', 'api.scheduling:view'),
  ('nurse', 'api.scheduling:view'),
  ('assistant', 'api.scheduling:view'),
  ('receptionist', 'api.scheduling:view'),
  ('patient', 'api.scheduling:view'),
  ('super_admin', 'api.scheduling:create'),
  ('owner', 'api.scheduling:create'),
  ('general_manager', 'api.scheduling:create'),
  ('receptionist', 'api.scheduling:create'),
  ('assistant', 'api.scheduling:create'),
  ('patient', 'api.scheduling:create'),
  ('super_admin', 'api.scheduling:update'),
  ('owner', 'api.scheduling:update'),
  ('general_manager', 'api.scheduling:update'),
  ('receptionist', 'api.scheduling:update'),
  ('assistant', 'api.scheduling:update'),
  ('doctor', 'api.scheduling:update'),
  ('dentist', 'api.scheduling:update'),
  ('specialist', 'api.scheduling:update'),
  ('super_admin', 'api.scheduling:delete'),
  ('owner', 'api.scheduling:delete'),
  ('general_manager', 'api.scheduling:delete'),
  ('receptionist', 'api.scheduling:delete'),
  ('super_admin', 'api.scheduling:approve'),
  ('owner', 'api.scheduling:approve'),
  ('general_manager', 'api.scheduling:approve'),
  ('super_admin', 'api.scheduling:export'),
  ('owner', 'api.scheduling:export'),
  ('general_manager', 'api.scheduling:export'),
  ('receptionist', 'api.scheduling:export'),
  ('super_admin', 'api.scheduling:manage'),
  ('owner', 'api.scheduling:manage'),
  ('general_manager', 'api.scheduling:manage'),
  ('super_admin', 'api.queue:view'),
  ('owner', 'api.queue:view'),
  ('general_manager', 'api.queue:view'),
  ('receptionist', 'api.queue:view'),
  ('assistant', 'api.queue:view'),
  ('doctor', 'api.queue:view'),
  ('dentist', 'api.queue:view'),
  ('specialist', 'api.queue:view'),
  ('nurse', 'api.queue:view'),
  ('super_admin', 'api.queue:create'),
  ('owner', 'api.queue:create'),
  ('general_manager', 'api.queue:create'),
  ('receptionist', 'api.queue:create'),
  ('assistant', 'api.queue:create'),
  ('super_admin', 'api.queue:update'),
  ('owner', 'api.queue:update'),
  ('general_manager', 'api.queue:update'),
  ('receptionist', 'api.queue:update'),
  ('assistant', 'api.queue:update'),
  ('super_admin', 'api.queue:delete'),
  ('owner', 'api.queue:delete'),
  ('general_manager', 'api.queue:delete'),
  ('super_admin', 'api.queue:approve'),
  ('owner', 'api.queue:approve'),
  ('general_manager', 'api.queue:approve'),
  ('super_admin', 'api.queue:export'),
  ('owner', 'api.queue:export'),
  ('general_manager', 'api.queue:export'),
  ('super_admin', 'api.queue:manage'),
  ('owner', 'api.queue:manage'),
  ('general_manager', 'api.queue:manage'),
  ('super_admin', 'api.emr:view'),
  ('owner', 'api.emr:view'),
  ('general_manager', 'api.emr:view'),
  ('doctor', 'api.emr:view'),
  ('dentist', 'api.emr:view'),
  ('specialist', 'api.emr:view'),
  ('nurse', 'api.emr:view'),
  ('assistant', 'api.emr:view'),
  ('super_admin', 'api.emr:create'),
  ('owner', 'api.emr:create'),
  ('general_manager', 'api.emr:create'),
  ('doctor', 'api.emr:create'),
  ('dentist', 'api.emr:create'),
  ('specialist', 'api.emr:create'),
  ('nurse', 'api.emr:create'),
  ('super_admin', 'api.emr:update'),
  ('owner', 'api.emr:update'),
  ('general_manager', 'api.emr:update'),
  ('doctor', 'api.emr:update'),
  ('dentist', 'api.emr:update'),
  ('specialist', 'api.emr:update'),
  ('nurse', 'api.emr:update'),
  ('super_admin', 'api.emr:delete'),
  ('owner', 'api.emr:delete'),
  ('super_admin', 'api.emr:approve'),
  ('owner', 'api.emr:approve'),
  ('general_manager', 'api.emr:approve'),
  ('doctor', 'api.emr:approve'),
  ('dentist', 'api.emr:approve'),
  ('specialist', 'api.emr:approve'),
  ('super_admin', 'api.emr:export'),
  ('owner', 'api.emr:export'),
  ('general_manager', 'api.emr:export'),
  ('doctor', 'api.emr:export'),
  ('dentist', 'api.emr:export'),
  ('specialist', 'api.emr:export'),
  ('super_admin', 'api.emr:manage'),
  ('owner', 'api.emr:manage'),
  ('general_manager', 'api.emr:manage'),
  ('super_admin', 'api.dental:view'),
  ('owner', 'api.dental:view'),
  ('general_manager', 'api.dental:view'),
  ('dentist', 'api.dental:view'),
  ('doctor', 'api.dental:view'),
  ('assistant', 'api.dental:view'),
  ('super_admin', 'api.dental:create'),
  ('owner', 'api.dental:create'),
  ('general_manager', 'api.dental:create'),
  ('dentist', 'api.dental:create'),
  ('assistant', 'api.dental:create'),
  ('super_admin', 'api.dental:update'),
  ('owner', 'api.dental:update'),
  ('general_manager', 'api.dental:update'),
  ('dentist', 'api.dental:update'),
  ('assistant', 'api.dental:update'),
  ('super_admin', 'api.dental:delete'),
  ('owner', 'api.dental:delete'),
  ('super_admin', 'api.dental:approve'),
  ('owner', 'api.dental:approve'),
  ('general_manager', 'api.dental:approve'),
  ('dentist', 'api.dental:approve'),
  ('super_admin', 'api.dental:export'),
  ('owner', 'api.dental:export'),
  ('general_manager', 'api.dental:export'),
  ('dentist', 'api.dental:export'),
  ('super_admin', 'api.dental:manage'),
  ('owner', 'api.dental:manage'),
  ('general_manager', 'api.dental:manage'),
  ('super_admin', 'api.beauty:view'),
  ('owner', 'api.beauty:view'),
  ('general_manager', 'api.beauty:view'),
  ('specialist', 'api.beauty:view'),
  ('assistant', 'api.beauty:view'),
  ('receptionist', 'api.beauty:view'),
  ('super_admin', 'api.beauty:create'),
  ('owner', 'api.beauty:create'),
  ('general_manager', 'api.beauty:create'),
  ('specialist', 'api.beauty:create'),
  ('assistant', 'api.beauty:create'),
  ('super_admin', 'api.beauty:update'),
  ('owner', 'api.beauty:update'),
  ('general_manager', 'api.beauty:update'),
  ('specialist', 'api.beauty:update'),
  ('assistant', 'api.beauty:update'),
  ('super_admin', 'api.beauty:delete'),
  ('owner', 'api.beauty:delete'),
  ('super_admin', 'api.beauty:approve'),
  ('owner', 'api.beauty:approve'),
  ('general_manager', 'api.beauty:approve'),
  ('super_admin', 'api.beauty:export'),
  ('owner', 'api.beauty:export'),
  ('general_manager', 'api.beauty:export'),
  ('super_admin', 'api.beauty:manage'),
  ('owner', 'api.beauty:manage'),
  ('general_manager', 'api.beauty:manage'),
  ('super_admin', 'api.inventory:view'),
  ('owner', 'api.inventory:view'),
  ('general_manager', 'api.inventory:view'),
  ('inventory_manager', 'api.inventory:view'),
  ('assistant', 'api.inventory:view'),
  ('accountant', 'api.inventory:view'),
  ('super_admin', 'api.inventory:create'),
  ('owner', 'api.inventory:create'),
  ('general_manager', 'api.inventory:create'),
  ('inventory_manager', 'api.inventory:create'),
  ('super_admin', 'api.inventory:update'),
  ('owner', 'api.inventory:update'),
  ('general_manager', 'api.inventory:update'),
  ('inventory_manager', 'api.inventory:update'),
  ('assistant', 'api.inventory:update'),
  ('super_admin', 'api.inventory:delete'),
  ('owner', 'api.inventory:delete'),
  ('general_manager', 'api.inventory:delete'),
  ('super_admin', 'api.inventory:approve'),
  ('owner', 'api.inventory:approve'),
  ('general_manager', 'api.inventory:approve'),
  ('inventory_manager', 'api.inventory:approve'),
  ('super_admin', 'api.inventory:export'),
  ('owner', 'api.inventory:export'),
  ('general_manager', 'api.inventory:export'),
  ('inventory_manager', 'api.inventory:export'),
  ('accountant', 'api.inventory:export'),
  ('super_admin', 'api.inventory:manage'),
  ('owner', 'api.inventory:manage'),
  ('general_manager', 'api.inventory:manage'),
  ('inventory_manager', 'api.inventory:manage'),
  ('super_admin', 'api.billing:view'),
  ('owner', 'api.billing:view'),
  ('general_manager', 'api.billing:view'),
  ('accountant', 'api.billing:view'),
  ('super_admin', 'api.billing:create'),
  ('owner', 'api.billing:create'),
  ('general_manager', 'api.billing:create'),
  ('accountant', 'api.billing:create'),
  ('super_admin', 'api.billing:update'),
  ('owner', 'api.billing:update'),
  ('general_manager', 'api.billing:update'),
  ('accountant', 'api.billing:update'),
  ('super_admin', 'api.billing:delete'),
  ('owner', 'api.billing:delete'),
  ('super_admin', 'api.billing:approve'),
  ('owner', 'api.billing:approve'),
  ('general_manager', 'api.billing:approve'),
  ('accountant', 'api.billing:approve'),
  ('super_admin', 'api.billing:export'),
  ('owner', 'api.billing:export'),
  ('general_manager', 'api.billing:export'),
  ('accountant', 'api.billing:export'),
  ('super_admin', 'api.billing:manage'),
  ('owner', 'api.billing:manage'),
  ('general_manager', 'api.billing:manage'),
  ('super_admin', 'api.commission:view'),
  ('owner', 'api.commission:view'),
  ('general_manager', 'api.commission:view'),
  ('accountant', 'api.commission:view'),
  ('super_admin', 'api.commission:create'),
  ('owner', 'api.commission:create'),
  ('general_manager', 'api.commission:create'),
  ('accountant', 'api.commission:create'),
  ('super_admin', 'api.commission:update'),
  ('owner', 'api.commission:update'),
  ('general_manager', 'api.commission:update'),
  ('accountant', 'api.commission:update'),
  ('super_admin', 'api.commission:delete'),
  ('owner', 'api.commission:delete'),
  ('super_admin', 'api.commission:approve'),
  ('owner', 'api.commission:approve'),
  ('general_manager', 'api.commission:approve'),
  ('accountant', 'api.commission:approve'),
  ('super_admin', 'api.commission:export'),
  ('owner', 'api.commission:export'),
  ('general_manager', 'api.commission:export'),
  ('accountant', 'api.commission:export'),
  ('super_admin', 'api.commission:manage'),
  ('owner', 'api.commission:manage'),
  ('general_manager', 'api.commission:manage'),
  ('super_admin', 'api.subscription:view'),
  ('owner', 'api.subscription:view'),
  ('general_manager', 'api.subscription:view'),
  ('accountant', 'api.subscription:view'),
  ('super_admin', 'api.subscription:create'),
  ('owner', 'api.subscription:create'),
  ('general_manager', 'api.subscription:create'),
  ('super_admin', 'api.subscription:update'),
  ('owner', 'api.subscription:update'),
  ('general_manager', 'api.subscription:update'),
  ('super_admin', 'api.subscription:delete'),
  ('owner', 'api.subscription:delete'),
  ('super_admin', 'api.subscription:approve'),
  ('owner', 'api.subscription:approve'),
  ('general_manager', 'api.subscription:approve'),
  ('super_admin', 'api.subscription:export'),
  ('owner', 'api.subscription:export'),
  ('general_manager', 'api.subscription:export'),
  ('accountant', 'api.subscription:export'),
  ('super_admin', 'api.subscription:manage'),
  ('owner', 'api.subscription:manage'),
  ('super_admin', 'api.notifications:view'),
  ('owner', 'api.notifications:view'),
  ('general_manager', 'api.notifications:view'),
  ('doctor', 'api.notifications:view'),
  ('dentist', 'api.notifications:view'),
  ('specialist', 'api.notifications:view'),
  ('nurse', 'api.notifications:view'),
  ('assistant', 'api.notifications:view'),
  ('receptionist', 'api.notifications:view'),
  ('accountant', 'api.notifications:view'),
  ('inventory_manager', 'api.notifications:view'),
  ('patient', 'api.notifications:view'),
  ('super_admin', 'api.notifications:create'),
  ('owner', 'api.notifications:create'),
  ('general_manager', 'api.notifications:create'),
  ('receptionist', 'api.notifications:create'),
  ('assistant', 'api.notifications:create'),
  ('super_admin', 'api.notifications:update'),
  ('owner', 'api.notifications:update'),
  ('general_manager', 'api.notifications:update'),
  ('doctor', 'api.notifications:update'),
  ('dentist', 'api.notifications:update'),
  ('specialist', 'api.notifications:update'),
  ('nurse', 'api.notifications:update'),
  ('assistant', 'api.notifications:update'),
  ('receptionist', 'api.notifications:update'),
  ('accountant', 'api.notifications:update'),
  ('inventory_manager', 'api.notifications:update'),
  ('patient', 'api.notifications:update'),
  ('super_admin', 'api.notifications:delete'),
  ('owner', 'api.notifications:delete'),
  ('super_admin', 'api.notifications:approve'),
  ('owner', 'api.notifications:approve'),
  ('general_manager', 'api.notifications:approve'),
  ('super_admin', 'api.notifications:export'),
  ('owner', 'api.notifications:export'),
  ('general_manager', 'api.notifications:export'),
  ('accountant', 'api.notifications:export'),
  ('super_admin', 'api.notifications:manage'),
  ('owner', 'api.notifications:manage'),
  ('general_manager', 'api.notifications:manage'),
  ('super_admin', 'api.audit:view'),
  ('owner', 'api.audit:view'),
  ('general_manager', 'api.audit:view'),
  ('accountant', 'api.audit:view'),
  ('super_admin', 'api.audit:create'),
  ('owner', 'api.audit:create'),
  ('general_manager', 'api.audit:create'),
  ('super_admin', 'api.audit:update'),
  ('super_admin', 'api.audit:delete'),
  ('super_admin', 'api.audit:approve'),
  ('owner', 'api.audit:approve'),
  ('super_admin', 'api.audit:export'),
  ('owner', 'api.audit:export'),
  ('general_manager', 'api.audit:export'),
  ('accountant', 'api.audit:export'),
  ('super_admin', 'api.audit:manage'),
  ('super_admin', 'api.loyalty:view'),
  ('owner', 'api.loyalty:view'),
  ('general_manager', 'api.loyalty:view'),
  ('doctor', 'api.loyalty:view'),
  ('dentist', 'api.loyalty:view'),
  ('specialist', 'api.loyalty:view'),
  ('nurse', 'api.loyalty:view'),
  ('assistant', 'api.loyalty:view'),
  ('receptionist', 'api.loyalty:view'),
  ('patient', 'api.loyalty:view'),
  ('super_admin', 'api.loyalty:create'),
  ('owner', 'api.loyalty:create'),
  ('general_manager', 'api.loyalty:create'),
  ('receptionist', 'api.loyalty:create'),
  ('assistant', 'api.loyalty:create'),
  ('super_admin', 'api.loyalty:update'),
  ('owner', 'api.loyalty:update'),
  ('general_manager', 'api.loyalty:update'),
  ('assistant', 'api.loyalty:update'),
  ('receptionist', 'api.loyalty:update'),
  ('patient', 'api.loyalty:update'),
  ('super_admin', 'api.loyalty:delete'),
  ('owner', 'api.loyalty:delete'),
  ('super_admin', 'api.loyalty:approve'),
  ('owner', 'api.loyalty:approve'),
  ('general_manager', 'api.loyalty:approve'),
  ('super_admin', 'api.loyalty:export'),
  ('owner', 'api.loyalty:export'),
  ('general_manager', 'api.loyalty:export'),
  ('accountant', 'api.loyalty:export'),
  ('super_admin', 'api.loyalty:manage'),
  ('owner', 'api.loyalty:manage'),
  ('general_manager', 'api.loyalty:manage'),
  ('super_admin', 'api.reporting:view'),
  ('owner', 'api.reporting:view'),
  ('general_manager', 'api.reporting:view'),
  ('accountant', 'api.reporting:view'),
  ('doctor', 'api.reporting:view'),
  ('dentist', 'api.reporting:view'),
  ('specialist', 'api.reporting:view'),
  ('super_admin', 'api.reporting:create'),
  ('owner', 'api.reporting:create'),
  ('general_manager', 'api.reporting:create'),
  ('accountant', 'api.reporting:create'),
  ('super_admin', 'api.reporting:update'),
  ('owner', 'api.reporting:update'),
  ('general_manager', 'api.reporting:update'),
  ('accountant', 'api.reporting:update'),
  ('super_admin', 'api.reporting:delete'),
  ('owner', 'api.reporting:delete'),
  ('super_admin', 'api.reporting:approve'),
  ('owner', 'api.reporting:approve'),
  ('general_manager', 'api.reporting:approve'),
  ('super_admin', 'api.reporting:export'),
  ('owner', 'api.reporting:export'),
  ('general_manager', 'api.reporting:export'),
  ('accountant', 'api.reporting:export'),
  ('doctor', 'api.reporting:export'),
  ('dentist', 'api.reporting:export'),
  ('specialist', 'api.reporting:export'),
  ('super_admin', 'api.reporting:manage'),
  ('owner', 'api.reporting:manage'),
  ('general_manager', 'api.reporting:manage'),
  ('super_admin', 'api.analytics:view'),
  ('owner', 'api.analytics:view'),
  ('general_manager', 'api.analytics:view'),
  ('doctor', 'api.analytics:view'),
  ('dentist', 'api.analytics:view'),
  ('specialist', 'api.analytics:view'),
  ('accountant', 'api.analytics:view'),
  ('inventory_manager', 'api.analytics:view'),
  ('super_admin', 'api.analytics:create'),
  ('owner', 'api.analytics:create'),
  ('general_manager', 'api.analytics:create'),
  ('accountant', 'api.analytics:create'),
  ('super_admin', 'api.analytics:update'),
  ('owner', 'api.analytics:update'),
  ('general_manager', 'api.analytics:update'),
  ('accountant', 'api.analytics:update'),
  ('super_admin', 'api.analytics:delete'),
  ('owner', 'api.analytics:delete'),
  ('super_admin', 'api.analytics:approve'),
  ('owner', 'api.analytics:approve'),
  ('general_manager', 'api.analytics:approve'),
  ('super_admin', 'api.analytics:export'),
  ('owner', 'api.analytics:export'),
  ('general_manager', 'api.analytics:export'),
  ('accountant', 'api.analytics:export'),
  ('doctor', 'api.analytics:export'),
  ('dentist', 'api.analytics:export'),
  ('specialist', 'api.analytics:export'),
  ('inventory_manager', 'api.analytics:export'),
  ('super_admin', 'api.analytics:manage'),
  ('owner', 'api.analytics:manage'),
  ('general_manager', 'api.analytics:manage'),
  ('super_admin', 'api.workflow:view'),
  ('owner', 'api.workflow:view'),
  ('general_manager', 'api.workflow:view'),
  ('doctor', 'api.workflow:view'),
  ('dentist', 'api.workflow:view'),
  ('specialist', 'api.workflow:view'),
  ('nurse', 'api.workflow:view'),
  ('assistant', 'api.workflow:view'),
  ('receptionist', 'api.workflow:view'),
  ('super_admin', 'api.workflow:create'),
  ('owner', 'api.workflow:create'),
  ('general_manager', 'api.workflow:create'),
  ('super_admin', 'api.workflow:update'),
  ('owner', 'api.workflow:update'),
  ('general_manager', 'api.workflow:update'),
  ('assistant', 'api.workflow:update'),
  ('receptionist', 'api.workflow:update'),
  ('super_admin', 'api.workflow:delete'),
  ('owner', 'api.workflow:delete'),
  ('general_manager', 'api.workflow:delete'),
  ('super_admin', 'api.workflow:approve'),
  ('owner', 'api.workflow:approve'),
  ('general_manager', 'api.workflow:approve'),
  ('super_admin', 'api.workflow:export'),
  ('owner', 'api.workflow:export'),
  ('general_manager', 'api.workflow:export'),
  ('super_admin', 'api.workflow:manage'),
  ('owner', 'api.workflow:manage'),
  ('general_manager', 'api.workflow:manage'),
  ('super_admin', 'api.ai:view'),
  ('owner', 'api.ai:view'),
  ('general_manager', 'api.ai:view'),
  ('specialist', 'api.ai:view'),
  ('doctor', 'api.ai:view'),
  ('super_admin', 'api.ai:create'),
  ('owner', 'api.ai:create'),
  ('general_manager', 'api.ai:create'),
  ('specialist', 'api.ai:create'),
  ('super_admin', 'api.ai:update'),
  ('owner', 'api.ai:update'),
  ('general_manager', 'api.ai:update'),
  ('specialist', 'api.ai:update'),
  ('super_admin', 'api.ai:delete'),
  ('owner', 'api.ai:delete'),
  ('super_admin', 'api.ai:approve'),
  ('owner', 'api.ai:approve'),
  ('general_manager', 'api.ai:approve'),
  ('super_admin', 'api.ai:export'),
  ('owner', 'api.ai:export'),
  ('general_manager', 'api.ai:export'),
  ('super_admin', 'api.ai:manage'),
  ('owner', 'api.ai:manage'),
  ('general_manager', 'api.ai:manage'),
  ('super_admin', 'api.patient_portal:view'),
  ('owner', 'api.patient_portal:view'),
  ('general_manager', 'api.patient_portal:view'),
  ('receptionist', 'api.patient_portal:view'),
  ('assistant', 'api.patient_portal:view'),
  ('patient', 'api.patient_portal:view'),
  ('super_admin', 'api.patient_portal:create'),
  ('owner', 'api.patient_portal:create'),
  ('general_manager', 'api.patient_portal:create'),
  ('receptionist', 'api.patient_portal:create'),
  ('assistant', 'api.patient_portal:create'),
  ('patient', 'api.patient_portal:create'),
  ('super_admin', 'api.patient_portal:update'),
  ('owner', 'api.patient_portal:update'),
  ('general_manager', 'api.patient_portal:update'),
  ('receptionist', 'api.patient_portal:update'),
  ('assistant', 'api.patient_portal:update'),
  ('patient', 'api.patient_portal:update'),
  ('super_admin', 'api.patient_portal:delete'),
  ('owner', 'api.patient_portal:delete'),
  ('general_manager', 'api.patient_portal:delete'),
  ('receptionist', 'api.patient_portal:delete'),
  ('super_admin', 'api.patient_portal:approve'),
  ('owner', 'api.patient_portal:approve'),
  ('general_manager', 'api.patient_portal:approve'),
  ('super_admin', 'api.patient_portal:export'),
  ('owner', 'api.patient_portal:export'),
  ('general_manager', 'api.patient_portal:export'),
  ('super_admin', 'api.patient_portal:manage'),
  ('owner', 'api.patient_portal:manage'),
  ('general_manager', 'api.patient_portal:manage'),
  ('super_admin', 'api.platform_admin:view'),
  ('super_admin', 'api.platform_admin:create'),
  ('super_admin', 'api.platform_admin:update'),
  ('super_admin', 'api.platform_admin:delete'),
  ('super_admin', 'api.platform_admin:approve'),
  ('super_admin', 'api.platform_admin:export'),
  ('super_admin', 'api.platform_admin:manage'),
  ('super_admin', 'api.tenant:view'),
  ('owner', 'api.tenant:view'),
  ('super_admin', 'api.tenant:create'),
  ('owner', 'api.tenant:create'),
  ('super_admin', 'api.tenant:update'),
  ('owner', 'api.tenant:update'),
  ('super_admin', 'api.tenant:delete'),
  ('super_admin', 'api.tenant:approve'),
  ('owner', 'api.tenant:approve'),
  ('super_admin', 'api.tenant:export'),
  ('owner', 'api.tenant:export'),
  ('super_admin', 'api.tenant:manage'),
  ('owner', 'api.tenant:manage')
ON CONFLICT (role_key, permission_id) DO NOTHING;
