import type { ImportExportRegistrationInput } from '../domain/import-export-registration.contracts';
import { IMPORT_EXPORT_PERMISSION_RESOURCE } from '../import-export.constants';

/**
 * Phase 42b — static catalog baseline.
 * Every entry is disabled / inactive / no adapter — intentional.
 * Platform discovers WHAT could exist; nothing is executable.
 */
export const STATIC_IMPORT_EXPORT_CATALOG: readonly ImportExportRegistrationInput[] = [
  {
    typeId: 'users-import',
    displayName: 'Users Import',
    category: 'identity',
    direction: 'import',
    ownerModule: 'users',
    requiredPermission: { resource: IMPORT_EXPORT_PERMISSION_RESOURCE, action: 'create' },
    requiredLicense: 'allowDataImport',
    tenantScope: 'tenant',
    branchScope: 'tenant',
    supportsDryRun: true,
    supportsPreview: true,
    supportedFormats: ['csv', 'xlsx'],
    version: '1.0.0',
    featureFlag: null,
    status: 'disabled',
    registrationKind: 'importer',
  },
  {
    typeId: 'users-export',
    displayName: 'Users Export',
    category: 'identity',
    direction: 'export',
    ownerModule: 'users',
    requiredPermission: { resource: IMPORT_EXPORT_PERMISSION_RESOURCE, action: 'export' },
    requiredLicense: 'allowDataExport',
    tenantScope: 'tenant',
    branchScope: 'tenant',
    supportsDryRun: false,
    supportsPreview: true,
    supportedFormats: ['csv', 'xlsx'],
    version: '1.0.0',
    featureFlag: null,
    status: 'disabled',
    registrationKind: 'exporter',
  },
  {
    typeId: 'inventory-import',
    displayName: 'Inventory Import',
    category: 'inventory',
    direction: 'import',
    ownerModule: 'inventory',
    requiredPermission: { resource: IMPORT_EXPORT_PERMISSION_RESOURCE, action: 'create' },
    requiredLicense: 'allowDataImport',
    tenantScope: 'tenant',
    branchScope: 'branch',
    supportsDryRun: true,
    supportsPreview: true,
    supportedFormats: ['csv', 'xlsx'],
    version: '1.0.0',
    featureFlag: null,
    status: 'disabled',
    registrationKind: 'importer',
  },
  {
    typeId: 'inventory-export',
    displayName: 'Inventory Export',
    category: 'inventory',
    direction: 'export',
    ownerModule: 'inventory',
    requiredPermission: { resource: IMPORT_EXPORT_PERMISSION_RESOURCE, action: 'export' },
    requiredLicense: 'allowDataExport',
    tenantScope: 'tenant',
    branchScope: 'branch',
    supportsDryRun: false,
    supportsPreview: true,
    supportedFormats: ['csv', 'xlsx'],
    version: '1.0.0',
    featureFlag: null,
    status: 'disabled',
    registrationKind: 'exporter',
  },
  {
    typeId: 'invoice-export',
    displayName: 'Invoice Export',
    category: 'billing',
    direction: 'export',
    ownerModule: 'billing',
    requiredPermission: { resource: IMPORT_EXPORT_PERMISSION_RESOURCE, action: 'export' },
    requiredLicense: 'allowDataExport',
    tenantScope: 'tenant',
    branchScope: 'branch',
    supportsDryRun: false,
    supportsPreview: true,
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    version: '1.0.0',
    featureFlag: null,
    status: 'inactive',
    registrationKind: 'exporter',
  },
  {
    typeId: 'patient-demographics-export',
    displayName: 'Patient Demographics Export',
    category: 'clinical',
    direction: 'export',
    ownerModule: 'patients',
    requiredPermission: { resource: IMPORT_EXPORT_PERMISSION_RESOURCE, action: 'export' },
    requiredLicense: 'allowDataExport',
    tenantScope: 'tenant',
    branchScope: 'branch',
    supportsDryRun: false,
    supportsPreview: true,
    supportedFormats: ['csv', 'xlsx'],
    version: '1.0.0',
    featureFlag: null,
    status: 'inactive',
    registrationKind: 'exporter',
  },
  {
    typeId: 'reporting-export',
    displayName: 'Reporting Export',
    category: 'reporting',
    direction: 'export',
    ownerModule: 'reporting',
    requiredPermission: { resource: IMPORT_EXPORT_PERMISSION_RESOURCE, action: 'export' },
    requiredLicense: 'allowDataExport',
    tenantScope: 'tenant',
    branchScope: 'tenant',
    supportsDryRun: false,
    supportsPreview: false,
    supportedFormats: ['csv', 'xlsx', 'pdf'],
    version: '1.0.0',
    featureFlag: null,
    status: 'disabled',
    registrationKind: 'exporter',
  },
] as const;
