import type { AiPromptCategoryId } from './ai-prompt-categories.config';

export interface AiPromptSeedDef {
  category: AiPromptCategoryId;
  titleEn: string;
  titleAr: string;
  bodyEn: string;
  bodyAr: string;
  favorite?: boolean;
  roles?: string[];
}

export const AI_PROMPT_DEFAULTS: AiPromptSeedDef[] = [
  {
    category: 'medical',
    titleEn: 'Summarize this patient chart',
    titleAr: 'لخّص ملف هذا المريض',
    bodyEn: 'Summarize this patient chart including allergies, medications, and recent visits.',
    bodyAr: 'لخّص ملف هذا المريض بما في ذلك الحساسية والأدوية والزيارات الأخيرة.',
    favorite: true,
    roles: ['doctor', 'nurse'],
  },
  {
    category: 'medical',
    titleEn: 'Generate SOAP note draft',
    titleAr: 'أنشئ مسودة SOAP',
    bodyEn: 'Generate a SOAP note draft from the current encounter context.',
    bodyAr: 'أنشئ مسودة SOAP من سياق الزيارة الحالية.',
    roles: ['doctor', 'nurse'],
  },
  {
    category: 'medical',
    titleEn: 'Highlight clinical risk indicators',
    titleAr: 'أبرز مؤشرات الخطر',
    bodyEn: 'Highlight clinical risk indicators for this patient based on available context.',
    bodyAr: 'أبرز مؤشرات الخطر السريرية لهذا المريض بناءً على السياق المتاح.',
    roles: ['doctor', 'nurse'],
  },
  {
    category: 'dental',
    titleEn: 'Explain dental chart findings',
    titleAr: 'اشرح مخطط الأسنان',
    bodyEn: 'Explain dental chart findings and highlight urgent treatment needs.',
    bodyAr: 'اشرح نتائج مخطط الأسنان وأبرز احتياجات العلاج العاجلة.',
    favorite: true,
    roles: ['dentist'],
  },
  {
    category: 'dental',
    titleEn: 'Suggest treatment plan options',
    titleAr: 'اقترح خطة علاج',
    bodyEn: 'Suggest treatment plan options based on the current dental chart.',
    bodyAr: 'اقترح خيارات خطة العلاج بناءً على مخطط الأسنان الحالي.',
    roles: ['dentist'],
  },
  {
    category: 'dental',
    titleEn: 'Summarize periodontal status',
    titleAr: 'لخّص حالة اللثة',
    bodyEn: 'Summarize periodontal status and recommend follow-up care.',
    bodyAr: 'لخّص حالة اللثة واقترح رعاية المتابعة.',
    roles: ['dentist'],
  },
  {
    category: 'beauty',
    titleEn: 'Plan next beauty session',
    titleAr: 'خطط الجلسة التالية',
    bodyEn: 'Plan the next beauty session based on prior treatments and goals.',
    bodyAr: 'خطط الجلسة التجميلية التالية بناءً على العلاجات والأهداف السابقة.',
    favorite: true,
    roles: ['specialist'],
  },
  {
    category: 'beauty',
    titleEn: 'Summarize treatment progress',
    titleAr: 'لخّص التقدم',
    bodyEn: 'Summarize treatment progress across recent beauty sessions.',
    bodyAr: 'لخّص تقدم العلاج عبر الجلسات التجميلية الأخيرة.',
    roles: ['specialist'],
  },
  {
    category: 'beauty',
    titleEn: 'Recommend follow-up interval',
    titleAr: 'اقترح متابعة',
    bodyEn: 'Recommend an appropriate follow-up interval for this beauty treatment plan.',
    bodyAr: 'اقترح فترة متابعة مناسبة لخطة العلاج التجميلي.',
    roles: ['specialist'],
  },
  {
    category: 'reception',
    titleEn: "Optimize tomorrow's schedule",
    titleAr: 'حسّن جدول الغد',
    bodyEn: "Optimize tomorrow's appointment schedule and flag conflicts.",
    bodyAr: 'حسّن جدول مواعيد الغد وأبرز التعارضات.',
    favorite: true,
    roles: ['receptionist'],
  },
  {
    category: 'reception',
    titleEn: 'Find empty appointment slots',
    titleAr: 'اعثر على مواعيد فارغة',
    bodyEn: 'Find empty appointment slots for the next seven days by provider.',
    bodyAr: 'اعثر على مواعيد فارغة للأيام السبعة القادمة حسب مقدم الخدمة.',
    roles: ['receptionist'],
  },
  {
    category: 'reception',
    titleEn: 'Analyze no-show risk',
    titleAr: 'حلل مخاطر عدم الحضور',
    bodyEn: 'Analyze no-show risk for upcoming appointments and suggest mitigations.',
    bodyAr: 'حلل مخاطر عدم الحضور للمواعيد القادمة واقترح إجراءات تخفيف.',
    roles: ['receptionist'],
  },
  {
    category: 'billing',
    titleEn: 'List outstanding invoices',
    titleAr: 'اعرض الفواتير المعلقة',
    bodyEn: 'List outstanding invoices and summarize aging buckets.',
    bodyAr: 'اعرض الفواتير المعلقة ولخّص فئات التأخير.',
    roles: ['accountant', 'cashier'],
  },
  {
    category: 'billing',
    titleEn: 'Summarize revenue this month',
    titleAr: 'لخّص إيرادات الشهر',
    bodyEn: 'Summarize revenue this month and compare to the prior period.',
    bodyAr: 'لخّص إيرادات هذا الشهر وقارنها بالفترة السابقة.',
    favorite: true,
    roles: ['accountant', 'cashier'],
  },
  {
    category: 'billing',
    titleEn: 'Explain this invoice',
    titleAr: 'اشرح هذه الفاتورة',
    bodyEn: 'Explain this invoice in plain language for staff or patient communication.',
    bodyAr: 'اشرح هذه الفاتورة بلغة مبسطة للتواصل مع الموظفين أو المريض.',
    roles: ['accountant', 'cashier'],
  },
  {
    category: 'inventory',
    titleEn: 'Predict low stock items',
    titleAr: 'توقع نقص المخزون',
    bodyEn: 'Predict low stock items and suggest reorder quantities.',
    bodyAr: 'توقع أصناف المخزون المنخفضة واقترح كميات إعادة الطلب.',
    favorite: true,
    roles: ['inventory_manager'],
  },
  {
    category: 'inventory',
    titleEn: 'Suggest purchase orders',
    titleAr: 'اقترح أوامر شراء',
    bodyEn: 'Suggest purchase orders based on consumption trends and lead times.',
    bodyAr: 'اقترح أوامر شراء بناءً على اتجاهات الاستهلاك وأوقات التوريد.',
    roles: ['inventory_manager'],
  },
  {
    category: 'inventory',
    titleEn: 'Flag near-expiry inventory',
    titleAr: 'أبرز قرب انتهاء الصلاحية',
    bodyEn: 'Flag inventory items nearing expiry and recommend disposition actions.',
    bodyAr: 'أبرز أصناف المخزون قريبة انتهاء الصلاحية واقترح إجراءات التصرف.',
    roles: ['inventory_manager'],
  },
  {
    category: 'analytics',
    titleEn: 'Explain dashboard KPIs',
    titleAr: 'اشرح مؤشرات اللوحة',
    bodyEn: 'Explain the current analytics dashboard KPIs in plain language.',
    bodyAr: 'اشرح مؤشرات لوحة التحليلات الحالية بلغة مبسطة.',
    favorite: true,
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'analytics',
    titleEn: 'Explain recent trends',
    titleAr: 'اشرح الاتجاهات',
    bodyEn: 'Explain recent trends visible on the analytics dashboard.',
    bodyAr: 'اشرح الاتجاهات الأخيرة الظاهرة على لوحة التحليلات.',
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'analytics',
    titleEn: 'Recommend growth actions',
    titleAr: 'اقترح نمواً',
    bodyEn: 'Recommend growth actions based on current analytics performance.',
    bodyAr: 'اقترح إجراءات نمو بناءً على أداء التحليلات الحالي.',
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'workflow',
    titleEn: 'Identify workflow bottlenecks',
    titleAr: 'حدد اختناقات سير العمل',
    bodyEn: 'Identify workflow bottlenecks and suggest automation improvements.',
    bodyAr: 'حدد اختناقات سير العمل واقترح تحسينات الأتمتة.',
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'workflow',
    titleEn: 'Review SLA compliance',
    titleAr: 'راجع الالتزام بـ SLA',
    bodyEn: 'Review SLA compliance across active workflow instances.',
    bodyAr: 'راجع الالتزام بـ SLA عبر حالات سير العمل النشطة.',
    favorite: true,
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'workflow',
    titleEn: 'Suggest automation rules',
    titleAr: 'اقترح أتمتة',
    bodyEn: 'Suggest automation rules to reduce manual workflow steps.',
    bodyAr: 'اقترح قواعد أتمتة لتقليل خطوات سير العمل اليدوية.',
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'reporting',
    titleEn: 'Generate revenue report',
    titleAr: 'تقرير الإيرادات',
    bodyEn: 'Generate a revenue report for the selected period and compare branches.',
    bodyAr: 'أنشئ تقرير إيرادات للفترة المحددة وقارن بين الفروع.',
    favorite: true,
    roles: ['owner', 'accountant'],
  },
  {
    category: 'reporting',
    titleEn: 'Show appointments last month',
    titleAr: 'مواعيد الشهر الماضي',
    bodyEn: 'Show appointments from last month grouped by status and branch.',
    bodyAr: 'اعرض مواعيد الشهر الماضي مجمعة حسب الحالة والفرع.',
    roles: ['owner', 'accountant'],
  },
  {
    category: 'reporting',
    titleEn: 'Compare branch performance',
    titleAr: 'قارن الفروع',
    bodyEn: 'Compare branch performance across key operational metrics.',
    bodyAr: 'قارن أداء الفروع عبر المؤشرات التشغيلية الرئيسية.',
    roles: ['owner', 'accountant'],
  },
  {
    category: 'management',
    titleEn: 'Executive clinic overview',
    titleAr: 'نظرة تنفيذية',
    bodyEn: 'Provide an executive clinic overview with operational highlights.',
    bodyAr: 'قدّم نظرة تنفيذية على العيادة مع أبرز النقاط التشغيلية.',
    favorite: true,
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'management',
    titleEn: 'Staff utilization summary',
    titleAr: 'ملخص استخدام الموظفين',
    bodyEn: 'Summarize staff utilization and scheduling efficiency.',
    bodyAr: 'لخّص استخدام الموظفين وكفاءة الجدولة.',
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'management',
    titleEn: 'Performance highlights',
    titleAr: 'أبرز الأداء',
    bodyEn: 'Highlight clinic performance wins and areas needing attention.',
    bodyAr: 'أبرز نقاط قوة أداء العيادة والمجالات التي تحتاج اهتماماً.',
    roles: ['owner', 'general_manager'],
  },
  {
    category: 'admin',
    titleEn: 'Review deployed AI models',
    titleAr: 'راجع النماذج المنشورة',
    bodyEn: 'Review deployed AI models and their validation status.',
    bodyAr: 'راجع نماذج الذكاء الاصطناعي المنشورة وحالة التحقق منها.',
    roles: ['owner'],
  },
  {
    category: 'admin',
    titleEn: 'Show AI usage by tenant',
    titleAr: 'استخدام الذكاء الاصطناعي',
    bodyEn: 'Summarize AI usage, token consumption, and active users for this tenant.',
    bodyAr: 'لخّص استخدام الذكاء الاصطناعي واستهلاك الرموز والمستخدمين النشطين لهذا المستأجر.',
    favorite: true,
    roles: ['owner'],
  },
  {
    category: 'admin',
    titleEn: 'Explain rate limits',
    titleAr: 'اشرح حدود المعدل',
    bodyEn: 'Explain current AI rate limits and subscription quotas for this tenant.',
    bodyAr: 'اشرح حدود معدل الذكاء الاصطناعي وحصص الاشتراك لهذا المستأجر.',
    roles: ['owner'],
  },
];
