-- Application role for RLS-enforced integration tests (no BYPASSRLS).
CREATE ROLE booking_app LOGIN PASSWORD 'booking_app' NOSUPERUSER NOBYPASSRLS;
GRANT CONNECT ON DATABASE booking_test TO booking_app;
GRANT USAGE ON SCHEMA public TO booking_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO booking_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO booking_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO booking_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO booking_app;
