/**
 * Phase 45b — built-in metric descriptors (OD-METRICS, OD-SLO, OD-API-OBS, OD-QUEUE-OBS, OD-HUB-OBS, OD-DB).
 */
import type { MetricDescriptor } from './metrics.types';

const DEFAULT_HISTOGRAM_MS = [5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000] as const;

export const BUILTIN_METRIC_DESCRIPTORS: readonly MetricDescriptor[] = [
  {
    name: 'observability.api.requests',
    type: 'counter',
    unit: '{request}',
    description: 'API requests by method and status class',
    allowedLabels: ['tenant_id', 'service', 'component', 'method', 'status_class'],
    scope: 'tenant',
    dataClass: 'ops_tenant',
    maxSeries: 400,
    retentionDays: 14,
  },
  {
    name: 'observability.api.errors',
    type: 'counter',
    unit: '{error}',
    description: 'API errors by coarse error class',
    allowedLabels: ['tenant_id', 'service', 'component', 'error_class', 'status_class'],
    scope: 'tenant',
    dataClass: 'ops_tenant',
    maxSeries: 400,
    retentionDays: 14,
  },
  {
    name: 'observability.api.latency_ms',
    type: 'histogram',
    unit: 'ms',
    description: 'API latency distribution in milliseconds',
    allowedLabels: ['tenant_id', 'service', 'component', 'method', 'status_class'],
    scope: 'tenant',
    dataClass: 'ops_tenant',
    maxSeries: 200,
    retentionDays: 14,
    histogramBounds: DEFAULT_HISTOGRAM_MS,
    sampleRatio: 1,
  },
  {
    name: 'observability.health.ready',
    type: 'gauge',
    unit: '1',
    description: 'Platform ready signal (1 ready, 0 not ready) — platform scope',
    allowedLabels: ['service', 'component'],
    scope: 'platform',
    dataClass: 'ops_public',
    maxSeries: 20,
    retentionDays: 14,
  },
  {
    name: 'observability.queue.depth',
    type: 'gauge',
    unit: '1',
    description: 'Queue depth by frozen queue name',
    allowedLabels: ['queue', 'service', 'component'],
    scope: 'platform',
    dataClass: 'ops_platform',
    maxSeries: 64,
    retentionDays: 14,
  },
  {
    name: 'observability.queue.failures',
    type: 'counter',
    unit: '{job}',
    description: 'Queue job failures by queue and outcome',
    allowedLabels: ['queue', 'outcome', 'service', 'component'],
    scope: 'platform',
    dataClass: 'ops_platform',
    maxSeries: 128,
    retentionDays: 14,
  },
  {
    name: 'observability.hub.job_failures',
    type: 'counter',
    unit: '{job}',
    description: 'Hub job failures by hub id',
    allowedLabels: ['hub', 'outcome', 'service', 'component', 'tenant_id'],
    scope: 'tenant',
    dataClass: 'ops_tenant',
    maxSeries: 200,
    retentionDays: 14,
  },
  {
    name: 'observability.db.pool_saturation',
    type: 'gauge',
    unit: '1',
    description: 'Database pool saturation ratio 0–1 (no SQL text)',
    allowedLabels: ['dependency', 'service', 'component'],
    scope: 'platform',
    dataClass: 'ops_platform',
    maxSeries: 32,
    retentionDays: 14,
  },
  {
    name: 'observability.cache.hit_ratio',
    type: 'gauge',
    unit: '1',
    description: 'Cache hit ratio 0–1',
    allowedLabels: ['dependency', 'service', 'component'],
    scope: 'platform',
    dataClass: 'ops_platform',
    maxSeries: 32,
    retentionDays: 14,
  },
  {
    name: 'observability.alerts.fired',
    type: 'counter',
    unit: '{alert}',
    description: 'Reserved for 45e alert fires; registered for catalog continuity',
    allowedLabels: ['service', 'component', 'outcome'],
    scope: 'platform',
    dataClass: 'ops_platform',
    maxSeries: 64,
    retentionDays: 14,
  },
  {
    name: 'observability.exporter.dropped',
    type: 'counter',
    unit: '1',
    description: 'Telemetry observations dropped by pipeline safeguards',
    allowedLabels: ['service', 'component', 'outcome'],
    scope: 'platform',
    dataClass: 'ops_platform',
    maxSeries: 32,
    retentionDays: 14,
  },
  {
    name: 'observability.pipeline.rejected',
    type: 'counter',
    unit: '1',
    description: 'Internal diagnostic: rejected observations by outcome class',
    allowedLabels: ['service', 'component', 'outcome', 'error_class'],
    scope: 'platform',
    dataClass: 'ops_platform',
    maxSeries: 64,
    retentionDays: 7,
  },
] as const;
