import type { CanonicalBrandAssetSlot } from './white-label-types';

export const CANONICAL_BRAND_ASSET_SLOTS: readonly CanonicalBrandAssetSlot[] = [
  {
    slotId: 'logo-light',
    labelKey: 'whitelabel.assets.logoLight',
    descriptionKey: 'whitelabel.assets.logoLightDesc',
    allowedMimeTypes: ['image/svg+xml', 'image/png', 'image/webp'],
    maxByteSize: 512 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 10,
  },
  {
    slotId: 'logo-dark',
    labelKey: 'whitelabel.assets.logoDark',
    descriptionKey: 'whitelabel.assets.logoDarkDesc',
    allowedMimeTypes: ['image/svg+xml', 'image/png', 'image/webp'],
    maxByteSize: 512 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 20,
  },
  {
    slotId: 'favicon',
    labelKey: 'whitelabel.assets.favicon',
    descriptionKey: 'whitelabel.assets.faviconDesc',
    allowedMimeTypes: ['image/x-icon', 'image/png'],
    maxByteSize: 64 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 30,
  },
  {
    slotId: 'splash',
    labelKey: 'whitelabel.assets.splash',
    descriptionKey: 'whitelabel.assets.splashDesc',
    allowedMimeTypes: ['image/png'],
    maxByteSize: 1024 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 40,
  },
  {
    slotId: 'loading-mark',
    labelKey: 'whitelabel.assets.loadingMark',
    descriptionKey: 'whitelabel.assets.loadingMarkDesc',
    allowedMimeTypes: ['image/svg+xml', 'image/png'],
    maxByteSize: 128 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 50,
  },
  {
    slotId: 'login-hero',
    labelKey: 'whitelabel.assets.loginHero',
    descriptionKey: 'whitelabel.assets.loginHeroDesc',
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxByteSize: 2 * 1024 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 60,
  },
  {
    slotId: 'email-header',
    labelKey: 'whitelabel.assets.emailHeader',
    descriptionKey: 'whitelabel.assets.emailHeaderDesc',
    allowedMimeTypes: ['image/png'],
    maxByteSize: 256 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 70,
  },
  {
    slotId: 'pdf-watermark',
    labelKey: 'whitelabel.assets.pdfWatermark',
    descriptionKey: 'whitelabel.assets.pdfWatermarkDesc',
    allowedMimeTypes: ['image/png'],
    maxByteSize: 256 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 80,
  },
  {
    slotId: 'portal-logo',
    labelKey: 'whitelabel.assets.portalLogo',
    descriptionKey: 'whitelabel.assets.portalLogoDesc',
    allowedMimeTypes: ['image/svg+xml', 'image/png', 'image/webp'],
    maxByteSize: 512 * 1024,
    requiresContentHash: true,
    requiresAssetVersion: true,
    cdnPathTemplate: '/c/{tenantId}/{slotId}/v{assetVersion}/{contentHash}.{ext}',
    sortOrder: 90,
  },
] as const;

export const CANONICAL_BRAND_ASSET_SLOT_COUNT = CANONICAL_BRAND_ASSET_SLOTS.length;

export const CANONICAL_BRAND_ASSET_SLOT_IDS = CANONICAL_BRAND_ASSET_SLOTS.map((slot) => slot.slotId);

export const CANONICAL_BRAND_ASSET_SLOT_ID_SET = new Set(CANONICAL_BRAND_ASSET_SLOT_IDS);
