import { WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION, type CanonicalWhiteLabelSurface } from './white-label-types';

export const CANONICAL_WHITE_LABEL_SURFACES: readonly CanonicalWhiteLabelSurface[] = [
  {
    surfaceId: 'settings-branding-core',
    localId: 'branding-core',
    moduleId: 'settings',
    surface: 'branding',
    categoryId: 'core-branding',
    requiredFeature: 'customBranding',
    settingsPath: '/settings/branding',
    deepLinkTemplate: '/settings/branding',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['appShell', 'pdf', 'email', 'export'],
    assetSlots: ['logo-light', 'logo-dark', 'favicon'],
    tokenGroups: ['color-primary', 'color-accent', 'color-surface'],
    layoutProfileId: 'clinical-default',
    localizationOptionIds: [],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.branding',
    descriptionKey: 'modules.settings.whiteLabel.brandingDesc',
    sortOrder: 10,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-branding-login',
    localId: 'branding-login',
    moduleId: 'settings',
    surface: 'loginPage',
    categoryId: 'advanced-theme',
    requiredFeature: 'whiteLabel',
    settingsPath: '/settings/branding#login',
    deepLinkTemplate: '/settings/branding#login',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['login', 'splash'],
    assetSlots: ['login-hero', 'logo-light', 'logo-dark'],
    tokenGroups: ['color-primary', 'color-surface'],
    layoutProfileId: 'minimal-login',
    localizationOptionIds: [],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.login',
    descriptionKey: 'modules.settings.whiteLabel.loginDesc',
    sortOrder: 20,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-custom-domain',
    localId: 'custom-domain',
    moduleId: 'settings',
    surface: 'customDomain',
    categoryId: 'identity-domain',
    requiredFeature: 'whiteLabel',
    settingsPath: '/settings/integrations#domain',
    deepLinkTemplate: '/settings/integrations#domain',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['routing', 'login', 'email'],
    assetSlots: [],
    tokenGroups: [],
    localizationOptionIds: [],
    defaultEnabled: false,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.customDomain',
    descriptionKey: 'modules.settings.whiteLabel.customDomainDesc',
    sortOrder: 30,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-theme-advanced',
    localId: 'theme-advanced',
    moduleId: 'settings',
    surface: 'theme',
    categoryId: 'advanced-theme',
    requiredFeature: 'customBranding',
    settingsPath: '/settings/branding#theme',
    deepLinkTemplate: '/settings/branding#theme',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['appShell', 'dashboard', 'analytics'],
    assetSlots: [],
    tokenGroups: ['color-primary', 'color-accent', 'color-semantic', 'color-surface', 'typography', 'radius', 'shadow', 'chart'],
    layoutProfileId: 'clinical-default',
    localizationOptionIds: [],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.theme',
    descriptionKey: 'modules.settings.whiteLabel.themeDesc',
    sortOrder: 40,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-layout-profile',
    localId: 'layout-profile',
    moduleId: 'settings',
    surface: 'layout',
    categoryId: 'advanced-theme',
    requiredFeature: 'customBranding',
    settingsPath: '/settings/branding#layout',
    deepLinkTemplate: '/settings/branding#layout',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['appShell', 'dashboard'],
    assetSlots: [],
    tokenGroups: ['spacing'],
    layoutProfileId: 'clinical-default',
    localizationOptionIds: [],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.layout',
    descriptionKey: 'modules.settings.whiteLabel.layoutDesc',
    sortOrder: 50,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-localization',
    localId: 'localization',
    moduleId: 'settings',
    surface: 'localization',
    categoryId: 'core-branding',
    requiredFeature: 'customBranding',
    settingsPath: '/settings/localization',
    deepLinkTemplate: '/settings/localization',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['appShell', 'pdf', 'export'],
    assetSlots: [],
    tokenGroups: ['typography'],
    localizationOptionIds: [
      'locale-en',
      'locale-ar',
      'date-format-iso',
      'date-format-us',
      'date-format-eu',
      'time-format-12h',
      'time-format-24h',
      'currency-display-code',
      'currency-display-symbol',
    ],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.localization',
    descriptionKey: 'modules.settings.whiteLabel.localizationDesc',
    sortOrder: 60,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-identity',
    localId: 'identity',
    moduleId: 'settings',
    surface: 'identity',
    categoryId: 'identity-domain',
    requiredFeature: 'customBranding',
    settingsPath: '/settings/profile',
    deepLinkTemplate: '/settings/profile',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['email', 'pdf', 'login', 'patientPortal'],
    assetSlots: ['logo-light', 'portal-logo'],
    tokenGroups: [],
    localizationOptionIds: ['currency-display-code', 'currency-display-symbol'],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.identity',
    descriptionKey: 'modules.settings.whiteLabel.identityDesc',
    sortOrder: 70,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-email-brand',
    localId: 'email-brand',
    moduleId: 'settings',
    surface: 'emailTemplate',
    categoryId: 'delivery-surfaces',
    requiredFeature: 'customBranding',
    settingsPath: '/settings/branding#email',
    deepLinkTemplate: '/settings/branding#email',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['email', 'notifications'],
    assetSlots: ['email-header', 'logo-light'],
    tokenGroups: ['color-primary', 'color-surface'],
    localizationOptionIds: ['locale-en', 'locale-ar'],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.email',
    descriptionKey: 'modules.settings.whiteLabel.emailDesc',
    sortOrder: 80,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-pdf-brand',
    localId: 'pdf-brand',
    moduleId: 'settings',
    surface: 'pdfTemplate',
    categoryId: 'delivery-surfaces',
    requiredFeature: 'customBranding',
    settingsPath: '/settings/branding#pdf',
    deepLinkTemplate: '/settings/branding#pdf',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['pdf', 'export', 'reporting', 'analytics'],
    assetSlots: ['logo-light', 'pdf-watermark'],
    tokenGroups: ['color-primary'],
    localizationOptionIds: ['date-format-iso', 'time-format-24h'],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.pdf',
    descriptionKey: 'modules.settings.whiteLabel.pdfDesc',
    sortOrder: 90,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    surfaceId: 'settings-portal-brand',
    localId: 'portal-brand',
    moduleId: 'settings',
    surface: 'patientPortal',
    categoryId: 'delivery-surfaces',
    requiredFeature: 'customBranding',
    settingsPath: '/settings/branding#portal',
    deepLinkTemplate: '/settings/branding#portal',
    adminResourceId: 'api.settings',
    adminAction: 'update',
    appliesTo: ['patientPortal'],
    assetSlots: ['portal-logo', 'logo-light'],
    tokenGroups: ['color-primary', 'color-accent', 'color-surface'],
    localizationOptionIds: ['locale-en', 'locale-ar'],
    defaultEnabled: true,
    rollbackBehavior: 'tenant-json',
    labelKey: 'modules.settings.whiteLabel.portal',
    descriptionKey: 'modules.settings.whiteLabel.portalDesc',
    sortOrder: 100,
    providerKey: 'whitelabel.builtin',
    schemaVersion: WHITE_LABEL_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_WHITE_LABEL_SURFACE_COUNT = CANONICAL_WHITE_LABEL_SURFACES.length;

export const CANONICAL_WHITE_LABEL_SURFACE_IDS = CANONICAL_WHITE_LABEL_SURFACES.map((surface) => surface.surfaceId);

export const CANONICAL_WHITE_LABEL_SURFACE_ID_SET = new Set(CANONICAL_WHITE_LABEL_SURFACE_IDS);

export const CANONICAL_WHITE_LABEL_SETTINGS_ROUTE_PATHS = [
  '/settings/branding',
  '/settings/localization',
  '/settings/integrations',
  '/settings/profile',
] as const;
