/**
 * Phase 45e — static dashboard catalog (OD-DASHBOARD).
 */
import type { DashboardDescriptor } from '../domain/dashboard.types';

export const STATIC_DASHBOARD_CATALOG: readonly DashboardDescriptor[] = [
  {
    id: 'operational_summary',
    title: 'Operational Summary',
    description: 'Cross-pipeline operational snapshot',
    category: 'summary',
    scope: 'shared',
    deepLinks: ['/settings/observability', '/health/ready'],
    schemaVersion: '45e',
  },
  {
    id: 'platform_health',
    title: 'Platform Health',
    description: 'Live/ready composition and contributor status',
    category: 'health',
    scope: 'platform',
    deepLinks: ['/health/live', '/health/ready', '/observability/health'],
    schemaVersion: '45e',
  },
  {
    id: 'metrics_overview',
    title: 'Metrics Overview',
    description: 'MVP SLI metric series counts and diagnostics',
    category: 'metrics',
    scope: 'shared',
    requiresSubFlag: 'metrics',
    deepLinks: ['/observability/metrics/catalog', '/metrics'],
    schemaVersion: '45e',
  },
  {
    id: 'logging_overview',
    title: 'Logging Overview',
    description: 'Structured log volume and correlation health',
    category: 'logging',
    scope: 'shared',
    requiresSubFlag: 'logging',
    deepLinks: ['/observability/logs/diagnostics'],
    schemaVersion: '45e',
  },
  {
    id: 'tracing_overview',
    title: 'Tracing Overview',
    description: 'Span volume and sampling diagnostics',
    category: 'tracing',
    scope: 'shared',
    requiresSubFlag: 'tracing',
    deepLinks: ['/observability/traces/diagnostics'],
    schemaVersion: '45e',
  },
  {
    id: 'queue_overview',
    title: 'Queue Overview',
    description: 'Queue depth and failure operational signals',
    category: 'queue',
    scope: 'shared',
    deepLinks: ['/settings/observability?panel=queue'],
    schemaVersion: '45e',
  },
  {
    id: 'background_jobs_overview',
    title: 'Background Jobs Overview',
    description: 'Job failure and throughput operational signals',
    category: 'jobs',
    scope: 'shared',
    deepLinks: ['/settings/observability?panel=jobs'],
    schemaVersion: '45e',
  },
  {
    id: 'database_health',
    title: 'Database Health',
    description: 'Pool saturation and dependency health surface',
    category: 'database',
    scope: 'platform',
    deepLinks: ['/settings/observability?panel=database'],
    schemaVersion: '45e',
  },
  {
    id: 'cache_health',
    title: 'Cache Health',
    description: 'Cache hit-ratio operational surface',
    category: 'cache',
    scope: 'platform',
    deepLinks: ['/settings/observability?panel=cache'],
    schemaVersion: '45e',
  },
  {
    id: 'export_storage_health',
    title: 'Export & Storage Health',
    description: 'Telemetry store/export port status',
    category: 'export_storage',
    scope: 'platform',
    deepLinks: ['/observability/health'],
    schemaVersion: '45e',
  },
  {
    id: 'tenant_operational',
    title: 'Tenant Operational Dashboard',
    description: 'Tenant-scoped operational status (licensed + sub-flag)',
    category: 'tenant',
    scope: 'tenant',
    requiresSubFlag: 'tenantDashboard',
    deepLinks: ['/settings/observability?scope=tenant'],
    schemaVersion: '45e',
  },
  {
    id: 'platform_operational',
    title: 'Platform Operational Dashboard',
    description: 'Platform-wide ops hub summary',
    category: 'platform',
    scope: 'platform',
    deepLinks: [
      '/settings/observability',
      '/settings/backup-restore',
      '/settings/import-export',
      '/settings/api-integrations',
    ],
    schemaVersion: '45e',
  },
] as const;
