/**
 * Phase 45e — MVP alert rule catalog (OD-ALERTS). Conservative defaults.
 */
import type { AlertRuleDefinition } from '../domain/alert.types';

export const STATIC_ALERT_RULE_CATALOG: readonly AlertRuleDefinition[] = [
  {
    id: 'api_error_rate_high',
    name: 'API error rate high',
    description: 'Fires when observability.api.errors exceeds threshold',
    severity: 'warning',
    category: 'errors',
    condition: 'threshold',
    signal: 'observability.api.errors',
    threshold: 10,
    comparator: 'gte',
    tenantScoped: true,
    enabled: true,
    groupBy: ['tenantId', 'signal'],
    schemaVersion: '45e',
  },
  {
    id: 'api_latency_high',
    name: 'API latency high',
    description: 'Fires when latency gauge/histogram signal exceeds threshold',
    severity: 'warning',
    category: 'latency',
    condition: 'threshold',
    signal: 'observability.api.latency_ms',
    threshold: 2000,
    comparator: 'gte',
    tenantScoped: true,
    enabled: true,
    groupBy: ['tenantId', 'signal'],
    schemaVersion: '45e',
  },
  {
    id: 'queue_depth_high',
    name: 'Queue depth high',
    description: 'Fires when queue depth exceeds capacity threshold',
    severity: 'warning',
    category: 'queue',
    condition: 'threshold',
    signal: 'observability.queue.depth',
    threshold: 100,
    comparator: 'gte',
    tenantScoped: false,
    enabled: true,
    groupBy: ['signal'],
    schemaVersion: '45e',
  },
  {
    id: 'queue_failures_high',
    name: 'Queue failures high',
    description: 'Fires when queue failures exceed threshold',
    severity: 'critical',
    category: 'queue',
    condition: 'threshold',
    signal: 'observability.queue.failures',
    threshold: 5,
    comparator: 'gte',
    tenantScoped: false,
    enabled: true,
    groupBy: ['signal'],
    schemaVersion: '45e',
  },
  {
    id: 'health_ready_absent',
    name: 'Health ready signal absent',
    description: 'Absence-of-signal for readiness metric',
    severity: 'critical',
    category: 'availability',
    condition: 'absence',
    signal: 'observability.health.ready',
    absenceWindowMs: 120_000,
    tenantScoped: false,
    enabled: true,
    groupBy: ['signal'],
    schemaVersion: '45e',
  },
  {
    id: 'hub_job_failures',
    name: 'Hub job failures',
    description: 'Fires when hub job failure metric exceeds threshold',
    severity: 'warning',
    category: 'dependency',
    condition: 'threshold',
    signal: 'observability.hub.job_failures',
    threshold: 3,
    comparator: 'gte',
    tenantScoped: false,
    enabled: true,
    groupBy: ['signal'],
    schemaVersion: '45e',
  },
  {
    id: 'exporter_dropped',
    name: 'Exporter dropped samples',
    description: 'Fires when exporter drop counter exceeds threshold',
    severity: 'info',
    category: 'pipeline',
    condition: 'threshold',
    signal: 'observability.exporter.dropped',
    threshold: 1,
    comparator: 'gte',
    tenantScoped: false,
    enabled: true,
    groupBy: ['signal'],
    schemaVersion: '45e',
  },
] as const;
