/**
 * Phase 45a — static catalog baseline (parity only; never runtime authority).
 * Signal domains / extension kinds — all disabled / non-executable.
 */
import type { ObservabilityRegistrationMetadata } from '../domain/observability-registration.contracts';
import { SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV } from '../observability.constants';

export const STATIC_OBSERVABILITY_CATALOG: readonly ObservabilityRegistrationMetadata[] =
  [
    {
      typeId: 'sli-api-availability',
      displayName: 'API availability SLI',
      category: 'sli',
      ownerModule: 'observability',
      registrationKind: 'signalDomain',
      status: 'disabled',
      requiredLicense: 'allowObservability',
      featureFlag: SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV,
      version: '45a.0',
      adapterAttached: false,
      executable: false,
    },
    {
      typeId: 'sli-api-latency',
      displayName: 'API latency SLI',
      category: 'sli',
      ownerModule: 'observability',
      registrationKind: 'signalDomain',
      status: 'disabled',
      requiredLicense: 'allowObservability',
      featureFlag: SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV,
      version: '45a.0',
      adapterAttached: false,
      executable: false,
    },
    {
      typeId: 'sli-queue-saturation',
      displayName: 'Queue saturation SLI',
      category: 'sli',
      ownerModule: 'observability',
      registrationKind: 'signalDomain',
      status: 'disabled',
      requiredLicense: 'allowObservability',
      featureFlag: SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV,
      version: '45a.0',
      adapterAttached: false,
      executable: false,
    },
    {
      typeId: 'hub-import-export',
      displayName: 'Import/Export hub contributor',
      category: 'hub',
      ownerModule: 'import-export',
      registrationKind: 'healthContributor',
      status: 'inactive',
      requiredLicense: 'allowObservability',
      featureFlag: SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV,
      version: '45a.0',
      adapterAttached: false,
      executable: false,
    },
    {
      typeId: 'hub-backup-restore',
      displayName: 'Backup & Restore hub contributor',
      category: 'hub',
      ownerModule: 'backup-restore',
      registrationKind: 'healthContributor',
      status: 'inactive',
      requiredLicense: 'allowObservability',
      featureFlag: SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV,
      version: '45a.0',
      adapterAttached: false,
      executable: false,
    },
    {
      typeId: 'hub-integrations',
      displayName: 'Integrations hub contributor',
      category: 'hub',
      ownerModule: 'integrations',
      registrationKind: 'healthContributor',
      status: 'inactive',
      requiredLicense: 'allowObservability',
      featureFlag: SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV,
      version: '45a.0',
      adapterAttached: false,
      executable: false,
    },
    {
      typeId: 'storage-port',
      displayName: 'Telemetry storage port',
      category: 'port',
      ownerModule: 'observability',
      registrationKind: 'storageAdapter',
      status: 'disabled',
      requiredLicense: 'allowObservability',
      featureFlag: SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV,
      version: '45a.0',
      adapterAttached: false,
      executable: false,
    },
    {
      typeId: 'export-port',
      displayName: 'Telemetry export port',
      category: 'port',
      ownerModule: 'observability',
      registrationKind: 'exportAdapter',
      status: 'disabled',
      requiredLicense: 'allowObservability',
      featureFlag: SYSTEM_MONITORING_OBSERVABILITY_ENABLED_ENV,
      version: '45a.0',
      adapterAttached: false,
      executable: false,
    },
  ] as const;

/** Explicit: static catalog is never runtime authority. */
export const STATIC_OBSERVABILITY_CATALOG_IS_RUNTIME_AUTHORITY = false;
