import {
  ACTIVITY_BUILTIN_PROVIDER_KEY,
  ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  type ActivityCategoryId,
  type ActivitySeverity,
  type CanonicalActivityType,
} from './activity-types';
import type { LicensedModuleId } from '../types';

type TypeInput = {
  activityTypeId: string;
  localId: string;
  moduleId: LicensedModuleId;
  categoryId: ActivityCategoryId;
  defaultSeverity: ActivitySeverity;
  labelKey: string;
  descriptionKey: string;
  resourceId: string;
  deepLinkTemplate: string;
  feedIds: readonly string[];
  producerEntityType: string;
  branchScoped?: boolean;
  crossBranchAllowed?: boolean;
  supportsCorrelation?: boolean;
  supportsCausation?: boolean;
  supportsParentActivity?: boolean;
  supportsBatch?: boolean;
  orderingScope?: 'tenant' | 'branch' | 'feed';
  retentionPolicyId?: string;
  redactFields?: readonly string[];
  icon?: string;
  sortOrder: number;
};

function defineType(input: TypeInput): CanonicalActivityType {
  return {
    activityTypeId: input.activityTypeId,
    eventTypeId: input.activityTypeId,
    localId: input.localId,
    moduleId: input.moduleId,
    activityKind: 'type',
    categoryId: input.categoryId,
    defaultSeverity: input.defaultSeverity,
    labelKey: input.labelKey,
    descriptionKey: input.descriptionKey,
    icon: input.icon,
    resourceId: input.resourceId,
    actions: ['view'],
    branchScoped: input.branchScoped ?? true,
    crossBranchAllowed: input.crossBranchAllowed ?? false,
    deepLinkTemplate: input.deepLinkTemplate,
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    feedIds: input.feedIds,
    producerEntityType: input.producerEntityType,
    eventVersion: '1.0.0',
    schemaVersion: '1',
    projectionVersion: '1',
    supportsCorrelation: input.supportsCorrelation ?? true,
    supportsCausation: input.supportsCausation ?? true,
    supportsParentActivity: input.supportsParentActivity ?? false,
    supportsBatch: input.supportsBatch ?? false,
    orderingScope: input.orderingScope ?? 'feed',
    retentionPolicyId: input.retentionPolicyId ?? 'hot-90d',
    redactFields: input.redactFields,
    sortOrder: input.sortOrder,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  };
}

/** Builtin module-owned activity types — aligned to Phase 38 §5.2 sources. */
export const CANONICAL_ACTIVITY_TYPES: readonly CanonicalActivityType[] = [
  defineType({
    activityTypeId: 'patient.registered',
    localId: 'patient-registered',
    moduleId: 'patients',
    categoryId: 'clinical',
    defaultSeverity: 'success',
    labelKey: 'activity.type.patient.registered',
    descriptionKey: 'activity.type.patient.registered.description',
    resourceId: 'api.patients',
    deepLinkTemplate: '/patients/:patientId?activity=patient.registered',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'patient',
    sortOrder: 10,
  }),
  defineType({
    activityTypeId: 'patient.updated',
    localId: 'patient-updated',
    moduleId: 'patients',
    categoryId: 'clinical',
    defaultSeverity: 'info',
    labelKey: 'activity.type.patient.updated',
    descriptionKey: 'activity.type.patient.updated.description',
    resourceId: 'api.patients',
    deepLinkTemplate: '/patients/:patientId?activity=patient.updated',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'patient',
    redactFields: ['nationalId', 'phone'],
    sortOrder: 20,
  }),
  defineType({
    activityTypeId: 'patient.portalInvited',
    localId: 'patient-portal-invited',
    moduleId: 'patients',
    categoryId: 'communication',
    defaultSeverity: 'info',
    labelKey: 'activity.type.patient.portalInvited',
    descriptionKey: 'activity.type.patient.portalInvited.description',
    resourceId: 'api.patients',
    deepLinkTemplate: '/patients/:patientId?activity=patient.portalInvited',
    feedIds: ['global', 'mine'],
    producerEntityType: 'patient',
    sortOrder: 30,
  }),
  defineType({
    activityTypeId: 'appointment.booked',
    localId: 'appointment-booked',
    moduleId: 'scheduling',
    categoryId: 'operational',
    defaultSeverity: 'success',
    labelKey: 'activity.type.appointment.booked',
    descriptionKey: 'activity.type.appointment.booked.description',
    resourceId: 'api.scheduling',
    deepLinkTemplate: '/appointments/:appointmentId?activity=appointment.booked',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'appointment',
    sortOrder: 40,
  }),
  defineType({
    activityTypeId: 'appointment.rescheduled',
    localId: 'appointment-rescheduled',
    moduleId: 'scheduling',
    categoryId: 'operational',
    defaultSeverity: 'warning',
    labelKey: 'activity.type.appointment.rescheduled',
    descriptionKey: 'activity.type.appointment.rescheduled.description',
    resourceId: 'api.scheduling',
    deepLinkTemplate: '/appointments/:appointmentId?activity=appointment.rescheduled',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'appointment',
    supportsParentActivity: true,
    sortOrder: 50,
  }),
  defineType({
    activityTypeId: 'appointment.cancelled',
    localId: 'appointment-cancelled',
    moduleId: 'scheduling',
    categoryId: 'operational',
    defaultSeverity: 'warning',
    labelKey: 'activity.type.appointment.cancelled',
    descriptionKey: 'activity.type.appointment.cancelled.description',
    resourceId: 'api.scheduling',
    deepLinkTemplate: '/appointments/:appointmentId?activity=appointment.cancelled',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'appointment',
    sortOrder: 60,
  }),
  defineType({
    activityTypeId: 'appointment.checkedIn',
    localId: 'appointment-checked-in',
    moduleId: 'scheduling',
    categoryId: 'operational',
    defaultSeverity: 'success',
    labelKey: 'activity.type.appointment.checkedIn',
    descriptionKey: 'activity.type.appointment.checkedIn.description',
    resourceId: 'api.scheduling',
    deepLinkTemplate: '/appointments/:appointmentId?activity=appointment.checkedIn',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'appointment',
    sortOrder: 70,
  }),
  defineType({
    activityTypeId: 'queue.ticketCalled',
    localId: 'queue-ticket-called',
    moduleId: 'queue',
    categoryId: 'operational',
    defaultSeverity: 'info',
    labelKey: 'activity.type.queue.ticketCalled',
    descriptionKey: 'activity.type.queue.ticketCalled.description',
    resourceId: 'api.queue',
    deepLinkTemplate: '/queue/:ticketId?activity=queue.ticketCalled',
    feedIds: ['global', 'mine'],
    producerEntityType: 'queueTicket',
    sortOrder: 80,
  }),
  defineType({
    activityTypeId: 'queue.completed',
    localId: 'queue-completed',
    moduleId: 'queue',
    categoryId: 'operational',
    defaultSeverity: 'success',
    labelKey: 'activity.type.queue.completed',
    descriptionKey: 'activity.type.queue.completed.description',
    resourceId: 'api.queue',
    deepLinkTemplate: '/queue/:ticketId?activity=queue.completed',
    feedIds: ['global', 'mine'],
    producerEntityType: 'queueTicket',
    sortOrder: 90,
  }),
  defineType({
    activityTypeId: 'emr.encounterClosed',
    localId: 'emr-encounter-closed',
    moduleId: 'emr',
    categoryId: 'clinical',
    defaultSeverity: 'success',
    labelKey: 'activity.type.emr.encounterClosed',
    descriptionKey: 'activity.type.emr.encounterClosed.description',
    resourceId: 'api.emr',
    deepLinkTemplate: '/encounters/:encounterId?activity=emr.encounterClosed',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'encounter',
    redactFields: ['clinicalNotes'],
    sortOrder: 100,
  }),
  defineType({
    activityTypeId: 'emr.prescriptionIssued',
    localId: 'emr-prescription-issued',
    moduleId: 'emr',
    categoryId: 'clinical',
    defaultSeverity: 'info',
    labelKey: 'activity.type.emr.prescriptionIssued',
    descriptionKey: 'activity.type.emr.prescriptionIssued.description',
    resourceId: 'api.emr',
    deepLinkTemplate: '/encounters/:encounterId?activity=emr.prescriptionIssued',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'prescription',
    redactFields: ['medicationName'],
    sortOrder: 110,
  }),
  defineType({
    activityTypeId: 'dental.treatmentPlanApproved',
    localId: 'dental-treatment-plan-approved',
    moduleId: 'dental',
    categoryId: 'clinical',
    defaultSeverity: 'success',
    labelKey: 'activity.type.dental.treatmentPlanApproved',
    descriptionKey: 'activity.type.dental.treatmentPlanApproved.description',
    resourceId: 'api.dental',
    deepLinkTemplate: '/dental/plans/:planId?activity=dental.treatmentPlanApproved',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'treatmentPlan',
    sortOrder: 120,
  }),
  defineType({
    activityTypeId: 'beauty.sessionCompleted',
    localId: 'beauty-session-completed',
    moduleId: 'beauty',
    categoryId: 'clinical',
    defaultSeverity: 'success',
    labelKey: 'activity.type.beauty.sessionCompleted',
    descriptionKey: 'activity.type.beauty.sessionCompleted.description',
    resourceId: 'api.beauty',
    deepLinkTemplate: '/beauty/sessions/:sessionId?activity=beauty.sessionCompleted',
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'beautySession',
    sortOrder: 130,
  }),
  defineType({
    activityTypeId: 'inventory.lowStock',
    localId: 'inventory-low-stock',
    moduleId: 'inventory',
    categoryId: 'inventory',
    defaultSeverity: 'warning',
    labelKey: 'activity.type.inventory.lowStock',
    descriptionKey: 'activity.type.inventory.lowStock.description',
    resourceId: 'api.inventory',
    deepLinkTemplate: '/inventory/items/:itemId?activity=inventory.lowStock',
    feedIds: ['global', 'inventory', 'mine'],
    producerEntityType: 'inventoryItem',
    sortOrder: 140,
  }),
  defineType({
    activityTypeId: 'inventory.received',
    localId: 'inventory-received',
    moduleId: 'inventory',
    categoryId: 'inventory',
    defaultSeverity: 'success',
    labelKey: 'activity.type.inventory.received',
    descriptionKey: 'activity.type.inventory.received.description',
    resourceId: 'api.inventory',
    deepLinkTemplate: '/inventory/receipts/:receiptId?activity=inventory.received',
    feedIds: ['global', 'inventory', 'mine'],
    producerEntityType: 'inventoryReceipt',
    supportsBatch: true,
    sortOrder: 150,
  }),
  defineType({
    activityTypeId: 'inventory.countClosed',
    localId: 'inventory-count-closed',
    moduleId: 'inventory',
    categoryId: 'inventory',
    defaultSeverity: 'info',
    labelKey: 'activity.type.inventory.countClosed',
    descriptionKey: 'activity.type.inventory.countClosed.description',
    resourceId: 'api.inventory',
    deepLinkTemplate: '/inventory/counts/:countId?activity=inventory.countClosed',
    feedIds: ['global', 'inventory', 'mine'],
    producerEntityType: 'stockCount',
    supportsBatch: true,
    sortOrder: 160,
  }),
  defineType({
    activityTypeId: 'invoice.created',
    localId: 'invoice-created',
    moduleId: 'billing',
    categoryId: 'financial',
    defaultSeverity: 'info',
    labelKey: 'activity.type.invoice.created',
    descriptionKey: 'activity.type.invoice.created.description',
    resourceId: 'api.billing',
    deepLinkTemplate: '/billing/invoices/:invoiceId?activity=invoice.created',
    feedIds: ['global', 'financial', 'mine'],
    producerEntityType: 'invoice',
    retentionPolicyId: 'hot-365d',
    sortOrder: 170,
  }),
  defineType({
    activityTypeId: 'payment.received',
    localId: 'payment-received',
    moduleId: 'billing',
    categoryId: 'financial',
    defaultSeverity: 'success',
    labelKey: 'activity.type.payment.received',
    descriptionKey: 'activity.type.payment.received.description',
    resourceId: 'api.billing',
    deepLinkTemplate: '/billing/payments/:paymentId?activity=payment.received',
    feedIds: ['global', 'financial', 'mine'],
    producerEntityType: 'payment',
    retentionPolicyId: 'hot-365d',
    sortOrder: 180,
  }),
  defineType({
    activityTypeId: 'refund.issued',
    localId: 'refund-issued',
    moduleId: 'billing',
    categoryId: 'financial',
    defaultSeverity: 'warning',
    labelKey: 'activity.type.refund.issued',
    descriptionKey: 'activity.type.refund.issued.description',
    resourceId: 'api.billing',
    deepLinkTemplate: '/billing/refunds/:refundId?activity=refund.issued',
    feedIds: ['global', 'financial', 'mine'],
    producerEntityType: 'refund',
    retentionPolicyId: 'hot-365d',
    sortOrder: 190,
  }),
  defineType({
    activityTypeId: 'report.generated',
    localId: 'report-generated',
    moduleId: 'reporting',
    categoryId: 'system',
    defaultSeverity: 'success',
    labelKey: 'activity.type.report.generated',
    descriptionKey: 'activity.type.report.generated.description',
    resourceId: 'api.reporting',
    deepLinkTemplate: '/reports/:reportId?activity=report.generated',
    feedIds: ['global', 'mine'],
    producerEntityType: 'reportRun',
    branchScoped: false,
    crossBranchAllowed: true,
    sortOrder: 200,
  }),
  defineType({
    activityTypeId: 'analytics.runFinished',
    localId: 'analytics-run-finished',
    moduleId: 'analytics',
    categoryId: 'system',
    defaultSeverity: 'info',
    labelKey: 'activity.type.analytics.runFinished',
    descriptionKey: 'activity.type.analytics.runFinished.description',
    resourceId: 'api.analytics',
    deepLinkTemplate: '/analytics?activity=analytics.runFinished',
    feedIds: ['global', 'mine'],
    producerEntityType: 'analyticsRun',
    branchScoped: false,
    crossBranchAllowed: true,
    sortOrder: 210,
  }),
  defineType({
    activityTypeId: 'workflow.automationFired',
    localId: 'workflow-automation-fired',
    moduleId: 'workflow',
    categoryId: 'workflow',
    defaultSeverity: 'info',
    labelKey: 'activity.type.workflow.automationFired',
    descriptionKey: 'activity.type.workflow.automationFired.description',
    resourceId: 'api.workflow',
    deepLinkTemplate: '/workflows/:runId?activity=workflow.automationFired',
    feedIds: ['global', 'mine'],
    producerEntityType: 'workflowRun',
    supportsCorrelation: true,
    sortOrder: 220,
  }),
  defineType({
    activityTypeId: 'workflow.automationFailed',
    localId: 'workflow-automation-failed',
    moduleId: 'workflow',
    categoryId: 'workflow',
    defaultSeverity: 'critical',
    labelKey: 'activity.type.workflow.automationFailed',
    descriptionKey: 'activity.type.workflow.automationFailed.description',
    resourceId: 'api.workflow',
    deepLinkTemplate: '/workflows/:runId?activity=workflow.automationFailed',
    feedIds: ['global', 'mine'],
    producerEntityType: 'workflowRun',
    supportsCorrelation: true,
    sortOrder: 230,
  }),
  defineType({
    activityTypeId: 'ai.toolInvoked',
    localId: 'ai-tool-invoked',
    moduleId: 'ai',
    categoryId: 'ai',
    defaultSeverity: 'info',
    labelKey: 'activity.type.ai.toolInvoked',
    descriptionKey: 'activity.type.ai.toolInvoked.description',
    resourceId: 'api.ai',
    deepLinkTemplate: '/ai?activity=ai.toolInvoked',
    feedIds: ['global', 'mine'],
    producerEntityType: 'aiToolCall',
    redactFields: ['prompt', 'response'],
    branchScoped: false,
    sortOrder: 240,
  }),
  defineType({
    activityTypeId: 'settings.hoursChanged',
    localId: 'settings-hours-changed',
    moduleId: 'settings',
    categoryId: 'administrative',
    defaultSeverity: 'info',
    labelKey: 'activity.type.settings.hoursChanged',
    descriptionKey: 'activity.type.settings.hoursChanged.description',
    resourceId: 'api.settings',
    deepLinkTemplate: '/settings/hours?activity=settings.hoursChanged',
    feedIds: ['global', 'mine'],
    producerEntityType: 'clinicHours',
    branchScoped: true,
    sortOrder: 250,
  }),
  defineType({
    activityTypeId: 'branding.published',
    localId: 'branding-published',
    moduleId: 'settings',
    categoryId: 'branding',
    defaultSeverity: 'success',
    labelKey: 'activity.type.branding.published',
    descriptionKey: 'activity.type.branding.published.description',
    resourceId: 'api.settings',
    deepLinkTemplate: '/settings/branding?activity=branding.published',
    feedIds: ['global', 'mine'],
    producerEntityType: 'brandingPublish',
    branchScoped: false,
    sortOrder: 260,
  }),
  defineType({
    activityTypeId: 'branch.created',
    localId: 'branch-created',
    moduleId: 'settings',
    categoryId: 'branch',
    defaultSeverity: 'success',
    labelKey: 'activity.type.branch.created',
    descriptionKey: 'activity.type.branch.created.description',
    resourceId: 'api.settings',
    deepLinkTemplate: '/settings/branches/:branchId?activity=branch.created',
    feedIds: ['global', 'branch', 'mine'],
    producerEntityType: 'branch',
    branchScoped: false,
    crossBranchAllowed: true,
    orderingScope: 'tenant',
    sortOrder: 270,
  }),
  defineType({
    activityTypeId: 'branch.accessRevoked',
    localId: 'branch-access-revoked',
    moduleId: 'settings',
    categoryId: 'branch',
    defaultSeverity: 'warning',
    labelKey: 'activity.type.branch.accessRevoked',
    descriptionKey: 'activity.type.branch.accessRevoked.description',
    resourceId: 'api.settings',
    deepLinkTemplate: '/settings/branches/:branchId?activity=branch.accessRevoked',
    feedIds: ['global', 'branch', 'security', 'mine'],
    producerEntityType: 'branchAccess',
    branchScoped: false,
    crossBranchAllowed: true,
    sortOrder: 280,
  }),
  defineType({
    activityTypeId: 'user.invited',
    localId: 'user-invited',
    moduleId: 'userManagement',
    categoryId: 'administrative',
    defaultSeverity: 'info',
    labelKey: 'activity.type.user.invited',
    descriptionKey: 'activity.type.user.invited.description',
    resourceId: 'api.identity',
    deepLinkTemplate: '/settings/users/:userId?activity=user.invited',
    feedIds: ['global', 'mine'],
    producerEntityType: 'user',
    branchScoped: false,
    sortOrder: 290,
  }),
  defineType({
    activityTypeId: 'user.roleChanged',
    localId: 'user-role-changed',
    moduleId: 'userManagement',
    categoryId: 'administrative',
    defaultSeverity: 'warning',
    labelKey: 'activity.type.user.roleChanged',
    descriptionKey: 'activity.type.user.roleChanged.description',
    resourceId: 'api.identity',
    deepLinkTemplate: '/settings/users/:userId?activity=user.roleChanged',
    feedIds: ['global', 'security', 'mine'],
    producerEntityType: 'user',
    branchScoped: false,
    sortOrder: 300,
  }),
  defineType({
    activityTypeId: 'security.failedLogin',
    localId: 'security-failed-login',
    moduleId: 'notifications',
    categoryId: 'security',
    defaultSeverity: 'critical',
    labelKey: 'activity.type.security.failedLogin',
    descriptionKey: 'activity.type.security.failedLogin.description',
    resourceId: 'api.identity',
    deepLinkTemplate: '/settings/security?activity=security.failedLogin',
    feedIds: ['global', 'security'],
    producerEntityType: 'authAttempt',
    branchScoped: false,
    retentionPolicyId: 'hot-730d',
    sortOrder: 310,
  }),
  defineType({
    activityTypeId: 'licensing.graceEntered',
    localId: 'licensing-grace-entered',
    moduleId: 'notifications',
    categoryId: 'licensing',
    defaultSeverity: 'warning',
    labelKey: 'activity.type.licensing.graceEntered',
    descriptionKey: 'activity.type.licensing.graceEntered.description',
    resourceId: 'api.subscription',
    deepLinkTemplate: '/settings/subscription?activity=licensing.graceEntered',
    feedIds: ['global', 'security'],
    producerEntityType: 'subscription',
    branchScoped: false,
    retentionPolicyId: 'hot-730d',
    sortOrder: 320,
  }),
  defineType({
    activityTypeId: 'module.lifecycleChanged',
    localId: 'module-lifecycle-changed',
    moduleId: 'dashboard',
    categoryId: 'system',
    defaultSeverity: 'info',
    labelKey: 'activity.type.module.lifecycleChanged',
    descriptionKey: 'activity.type.module.lifecycleChanged.description',
    resourceId: 'api.identity',
    deepLinkTemplate: '/settings/modules?activity=module.lifecycleChanged',
    feedIds: ['global'],
    producerEntityType: 'moduleLifecycle',
    branchScoped: false,
    sortOrder: 330,
  }),
] as const;

export const CANONICAL_ACTIVITY_TYPE_COUNT = CANONICAL_ACTIVITY_TYPES.length;

export const CANONICAL_ACTIVITY_TYPE_IDS = CANONICAL_ACTIVITY_TYPES.map((t) => t.activityTypeId);
