import {
  ACTIVITY_BUILTIN_PROVIDER_KEY,
  ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  type CanonicalActivityType,
} from './activity-types';

/**
 * Cross-module activity types owned by specialty modules
 * (parallel to CANONICAL_CROSS_MODULE_ANALYTICS).
 */
export const CANONICAL_CROSS_MODULE_ACTIVITY: readonly CanonicalActivityType[] = [
  {
    activityTypeId: 'dental.procedureCompleted',
    eventTypeId: 'dental.procedureCompleted',
    localId: 'dental-procedure-completed',
    moduleId: 'dental',
    activityKind: 'type',
    categoryId: 'clinical',
    defaultSeverity: 'success',
    labelKey: 'activity.type.dental.procedureCompleted',
    descriptionKey: 'activity.type.dental.procedureCompleted.description',
    resourceId: 'api.dental',
    actions: ['view'],
    branchScoped: true,
    crossBranchAllowed: false,
    deepLinkTemplate: '/dental/procedures/:procedureId?activity=dental.procedureCompleted',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    feedIds: ['global', 'clinical', 'mine'],
    producerEntityType: 'dentalProcedure',
    eventVersion: '1.0.0',
    schemaVersion: '1',
    projectionVersion: '1',
    supportsCorrelation: true,
    supportsCausation: true,
    supportsParentActivity: true,
    supportsBatch: false,
    orderingScope: 'feed',
    retentionPolicyId: 'hot-180d',
    sortOrder: 400,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    activityTypeId: 'commission.payoutPosted',
    eventTypeId: 'commission.payoutPosted',
    localId: 'commission-payout-posted',
    moduleId: 'commission',
    activityKind: 'type',
    categoryId: 'financial',
    defaultSeverity: 'success',
    labelKey: 'activity.type.commission.payoutPosted',
    descriptionKey: 'activity.type.commission.payoutPosted.description',
    resourceId: 'api.commission',
    actions: ['view'],
    branchScoped: true,
    crossBranchAllowed: false,
    deepLinkTemplate: '/billing/commission/:payoutId?activity=commission.payoutPosted',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    feedIds: ['global', 'financial', 'mine'],
    producerEntityType: 'commissionPayout',
    eventVersion: '1.0.0',
    schemaVersion: '1',
    projectionVersion: '1',
    supportsCorrelation: true,
    supportsCausation: true,
    supportsParentActivity: false,
    supportsBatch: true,
    orderingScope: 'feed',
    retentionPolicyId: 'hot-365d',
    sortOrder: 410,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    activityTypeId: 'loyalty.rewardEarned',
    eventTypeId: 'loyalty.rewardEarned',
    localId: 'loyalty-reward-earned',
    moduleId: 'loyalty',
    activityKind: 'type',
    categoryId: 'financial',
    defaultSeverity: 'success',
    labelKey: 'activity.type.loyalty.rewardEarned',
    descriptionKey: 'activity.type.loyalty.rewardEarned.description',
    resourceId: 'api.loyalty',
    actions: ['view'],
    branchScoped: true,
    crossBranchAllowed: false,
    deepLinkTemplate: '/billing/loyalty/:rewardId?activity=loyalty.rewardEarned',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    feedIds: ['global', 'financial', 'mine'],
    producerEntityType: 'loyaltyReward',
    eventVersion: '1.0.0',
    schemaVersion: '1',
    projectionVersion: '1',
    supportsCorrelation: true,
    supportsCausation: true,
    supportsParentActivity: false,
    supportsBatch: false,
    orderingScope: 'feed',
    retentionPolicyId: 'hot-180d',
    sortOrder: 420,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_CROSS_MODULE_ACTIVITY_COUNT = CANONICAL_CROSS_MODULE_ACTIVITY.length;
