import {
  ACTIVITY_BUILTIN_PROVIDER_KEY,
  ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  type CanonicalActivityFeed,
} from './activity-types';

/**
 * Canonical activity feeds with complete ownership metadata (Phase 38 §8 / §26).
 * Owned by notifications module for discoverability until a dedicated Activity module exists.
 */
export const CANONICAL_ACTIVITY_FEEDS: readonly CanonicalActivityFeed[] = [
  {
    feedId: 'global',
    localId: 'feed-global',
    moduleId: 'notifications',
    activityKind: 'feed',
    ownerModuleId: 'platform',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    visibility: 'activity.visibility.authenticated',
    licensing: 'module-access',
    resourceId: 'api.notifications',
    actions: ['view', 'export'],
    branchScope: 'cross-branch',
    retentionPolicy: 'hot-90d',
    archivePolicy: 'archive-after-hot',
    labelKey: 'activity.feed.global',
    descriptionKey: 'activity.feed.global.description',
    route: '/activity/feeds/global',
    deepLinkTemplate: '/activity?feed=global',
    sortOrder: 0,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    feedId: 'clinical',
    localId: 'feed-clinical',
    moduleId: 'notifications',
    activityKind: 'feed',
    ownerModuleId: 'platform',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    visibility: 'activity.visibility.clinical',
    licensing: 'clinical-modules',
    resourceId: 'api.emr',
    actions: ['view'],
    branchScope: 'branch',
    retentionPolicy: 'hot-180d',
    archivePolicy: 'archive-after-hot',
    categoryFilter: ['clinical'],
    labelKey: 'activity.feed.clinical',
    descriptionKey: 'activity.feed.clinical.description',
    route: '/activity/feeds/clinical',
    deepLinkTemplate: '/activity?feed=clinical',
    sortOrder: 10,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    feedId: 'financial',
    localId: 'feed-financial',
    moduleId: 'notifications',
    activityKind: 'feed',
    ownerModuleId: 'platform',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    visibility: 'activity.visibility.financial',
    licensing: 'billing-module',
    resourceId: 'api.billing',
    actions: ['view', 'export'],
    branchScope: 'branch',
    retentionPolicy: 'hot-365d',
    archivePolicy: 'archive-after-hot',
    categoryFilter: ['financial'],
    labelKey: 'activity.feed.financial',
    descriptionKey: 'activity.feed.financial.description',
    route: '/activity/feeds/financial',
    deepLinkTemplate: '/activity?feed=financial',
    sortOrder: 20,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    feedId: 'security',
    localId: 'feed-security',
    moduleId: 'notifications',
    activityKind: 'feed',
    ownerModuleId: 'platform',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    visibility: 'activity.visibility.security',
    licensing: 'owner-gm',
    resourceId: 'api.identity',
    actions: ['view', 'export'],
    branchScope: 'tenant',
    retentionPolicy: 'hot-730d',
    archivePolicy: 'legal-hold-compatible',
    categoryFilter: ['security', 'licensing'],
    labelKey: 'activity.feed.security',
    descriptionKey: 'activity.feed.security.description',
    route: '/activity/feeds/security',
    deepLinkTemplate: '/activity?feed=security',
    sortOrder: 30,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    feedId: 'inventory',
    localId: 'feed-inventory',
    moduleId: 'notifications',
    activityKind: 'feed',
    ownerModuleId: 'platform',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    visibility: 'activity.visibility.inventory',
    licensing: 'inventory-module',
    resourceId: 'api.inventory',
    actions: ['view'],
    branchScope: 'branch',
    retentionPolicy: 'hot-90d',
    archivePolicy: 'archive-after-hot',
    categoryFilter: ['inventory'],
    labelKey: 'activity.feed.inventory',
    descriptionKey: 'activity.feed.inventory.description',
    route: '/activity/feeds/inventory',
    deepLinkTemplate: '/activity?feed=inventory',
    sortOrder: 40,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    feedId: 'branch',
    localId: 'feed-branch',
    moduleId: 'notifications',
    activityKind: 'feed',
    ownerModuleId: 'platform',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    visibility: 'activity.visibility.branch',
    licensing: 'multi-branch',
    resourceId: 'api.settings',
    actions: ['view'],
    branchScope: 'cross-branch',
    retentionPolicy: 'hot-180d',
    archivePolicy: 'archive-after-hot',
    categoryFilter: ['branch'],
    labelKey: 'activity.feed.branch',
    descriptionKey: 'activity.feed.branch.description',
    route: '/activity/feeds/branch',
    deepLinkTemplate: '/activity?feed=branch',
    sortOrder: 50,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    feedId: 'mine',
    localId: 'feed-mine',
    moduleId: 'notifications',
    activityKind: 'feed',
    ownerModuleId: 'platform',
    providerKey: ACTIVITY_BUILTIN_PROVIDER_KEY,
    visibility: 'activity.visibility.actor-self',
    licensing: 'authenticated',
    resourceId: 'api.notifications',
    actions: ['view'],
    branchScope: 'cross-branch',
    retentionPolicy: 'hot-90d',
    archivePolicy: 'archive-after-hot',
    labelKey: 'activity.feed.mine',
    descriptionKey: 'activity.feed.mine.description',
    route: '/activity/feeds/mine',
    deepLinkTemplate: '/activity?feed=mine',
    sortOrder: 60,
    contributionSchemaVersion: ACTIVITY_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_ACTIVITY_FEED_COUNT = CANONICAL_ACTIVITY_FEEDS.length;

export const CANONICAL_ACTIVITY_FEED_IDS = CANONICAL_ACTIVITY_FEEDS.map((f) => f.feedId);
