import {
  JOURNEY_BUILTIN_PROVIDER_KEY,
  JOURNEY_CONTRIBUTION_SCHEMA_VERSION,
  type CanonicalJourneyTransition,
  type JourneyFailureBehavior,
  type JourneyRetryPolicy,
  type JourneyStageId,
  type JourneyTransitionType,
} from './journey-types';
import type { LicensedModuleId } from '../types';

type TransitionInput = {
  transitionId: string;
  fromStageId: JourneyStageId;
  toStageId: JourneyStageId;
  transitionType: JourneyTransitionType;
  ownerModuleId: LicensedModuleId;
  permissionResource: string;
  requiredGuardIds?: readonly string[];
  requiredApprovalIds?: readonly string[];
  automationRuleIds?: readonly string[];
  retry?: JourneyRetryPolicy;
  failureBehavior?: JourneyFailureBehavior;
  allowedCycle?: boolean;
  sortOrder: number;
};

function defineTransition(input: TransitionInput): CanonicalJourneyTransition {
  const localId = `transition-${input.transitionId}`;
  return {
    transitionId: input.transitionId,
    localId,
    journeyKind: 'transition',
    fromStageId: input.fromStageId,
    toStageId: input.toStageId,
    transitionType: input.transitionType,
    moduleId: input.ownerModuleId,
    ownerModuleId: input.ownerModuleId,
    providerKey: JOURNEY_BUILTIN_PROVIDER_KEY,
    permissionResource: input.permissionResource,
    permissionAction: 'update',
    requiredGuardIds: input.requiredGuardIds ?? [],
    requiredApprovalIds: input.requiredApprovalIds ?? [],
    automationRuleIds: input.automationRuleIds ?? [],
    allowedBranchScope: 'branch',
    retry: input.retry ?? { maxAttempts: 3, backoff: 'exponential', failClosed: true },
    failureBehavior: input.failureBehavior ?? { strategy: 'fail-closed', failClosed: true },
    schemaVersion: '1',
    labelKey: `journey.transition.${input.transitionId}`,
    descriptionKey: `journey.transition.${input.transitionId}.description`,
    deepLinkTemplate: `/journey?transition=${input.transitionId}`,
    sortOrder: input.sortOrder,
    contributionSchemaVersion: JOURNEY_CONTRIBUTION_SCHEMA_VERSION,
    allowedCycle: input.allowedCycle,
  };
}

/**
 * Canonical patient journey transitions — Phase 40a foundation (22 transitions).
 * Zero runtime behavior: registry metadata only. From/to must reference canonical stages.
 */
export const CANONICAL_JOURNEY_TRANSITIONS: readonly CanonicalJourneyTransition[] = [
  defineTransition({
    transitionId: 'qualify-lead',
    fromStageId: 'lead',
    toStageId: 'prospect',
    transitionType: 'happy-path',
    ownerModuleId: 'patients',
    permissionResource: 'api.patients',
    requiredGuardIds: ['consent-captured'],
    sortOrder: 10,
  }),
  defineTransition({
    transitionId: 'register-patient',
    fromStageId: 'prospect',
    toStageId: 'registration',
    transitionType: 'happy-path',
    ownerModuleId: 'patients',
    permissionResource: 'api.patients',
    requiredGuardIds: ['consent-captured'],
    automationRuleIds: ['on-patient-registered-task'],
    sortOrder: 20,
  }),
  defineTransition({
    transitionId: 'capture-history',
    fromStageId: 'registration',
    toStageId: 'medical-history',
    transitionType: 'happy-path',
    ownerModuleId: 'patients',
    permissionResource: 'api.patients',
    requiredGuardIds: ['patient-registered'],
    sortOrder: 30,
  }),
  defineTransition({
    transitionId: 'book-appointment',
    fromStageId: 'medical-history',
    toStageId: 'appointment',
    transitionType: 'happy-path',
    ownerModuleId: 'emr',
    permissionResource: 'api.emr',
    requiredGuardIds: ['medical-history-complete'],
    automationRuleIds: ['on-appointment-created-remind'],
    allowedCycle: true,
    sortOrder: 40,
  }),
  defineTransition({
    transitionId: 'check-in-patient',
    fromStageId: 'appointment',
    toStageId: 'check-in',
    transitionType: 'happy-path',
    ownerModuleId: 'scheduling',
    permissionResource: 'api.scheduling',
    requiredGuardIds: ['appointment-confirmed'],
    automationRuleIds: ['on-checkin-verify'],
    sortOrder: 50,
  }),
  defineTransition({
    transitionId: 'enqueue',
    fromStageId: 'check-in',
    toStageId: 'waiting-queue',
    transitionType: 'happy-path',
    ownerModuleId: 'scheduling',
    permissionResource: 'api.scheduling',
    requiredGuardIds: ['appointment-confirmed'],
    sortOrder: 60,
  }),
  defineTransition({
    transitionId: 'start-consultation',
    fromStageId: 'waiting-queue',
    toStageId: 'consultation',
    transitionType: 'happy-path',
    ownerModuleId: 'queue',
    permissionResource: 'api.queue',
    requiredGuardIds: ['clinician-assigned'],
    sortOrder: 70,
  }),
  defineTransition({
    transitionId: 'record-diagnosis',
    fromStageId: 'consultation',
    toStageId: 'diagnosis',
    transitionType: 'happy-path',
    ownerModuleId: 'emr',
    permissionResource: 'api.emr',
    requiredGuardIds: ['clinician-assigned'],
    automationRuleIds: ['on-ai-next-step-advisory'],
    sortOrder: 80,
  }),
  defineTransition({
    transitionId: 'approve-plan',
    fromStageId: 'diagnosis',
    toStageId: 'treatment-plan',
    transitionType: 'happy-path',
    ownerModuleId: 'emr',
    permissionResource: 'api.emr',
    requiredGuardIds: ['diagnosis-recorded'],
    requiredApprovalIds: ['treatment-plan-consent'],
    automationRuleIds: ['on-plan-approved-schedule'],
    sortOrder: 90,
  }),
  defineTransition({
    transitionId: 'execute-procedure',
    fromStageId: 'treatment-plan',
    toStageId: 'procedures',
    transitionType: 'happy-path',
    ownerModuleId: 'dental',
    permissionResource: 'api.dental',
    requiredGuardIds: ['treatment-plan-approved'],
    automationRuleIds: ['on-procedure-inventory-signal'],
    sortOrder: 100,
  }),
  defineTransition({
    transitionId: 'order-lab',
    fromStageId: 'diagnosis',
    toStageId: 'laboratory',
    transitionType: 'parallel',
    ownerModuleId: 'emr',
    permissionResource: 'api.emr',
    requiredGuardIds: ['diagnosis-recorded'],
    sortOrder: 110,
  }),
  defineTransition({
    transitionId: 'order-imaging',
    fromStageId: 'diagnosis',
    toStageId: 'imaging',
    transitionType: 'parallel',
    ownerModuleId: 'emr',
    permissionResource: 'api.emr',
    requiredGuardIds: ['diagnosis-recorded'],
    sortOrder: 120,
  }),
  defineTransition({
    transitionId: 'issue-rx',
    fromStageId: 'diagnosis',
    toStageId: 'prescription',
    transitionType: 'parallel',
    ownerModuleId: 'emr',
    permissionResource: 'api.emr',
    requiredGuardIds: ['diagnosis-recorded'],
    sortOrder: 130,
  }),
  defineTransition({
    transitionId: 'generate-invoice',
    fromStageId: 'procedures',
    toStageId: 'billing',
    transitionType: 'happy-path',
    ownerModuleId: 'emr',
    permissionResource: 'api.emr',
    requiredGuardIds: [],
    automationRuleIds: ['on-invoice-collect'],
    sortOrder: 140,
  }),
  defineTransition({
    transitionId: 'collect-payment',
    fromStageId: 'billing',
    toStageId: 'payment',
    transitionType: 'happy-path',
    ownerModuleId: 'billing',
    permissionResource: 'api.billing',
    requiredGuardIds: ['invoice-issued'],
    automationRuleIds: ['on-payment-followup'],
    sortOrder: 150,
  }),
  defineTransition({
    transitionId: 'schedule-follow-up',
    fromStageId: 'payment',
    toStageId: 'follow-up',
    transitionType: 'happy-path',
    ownerModuleId: 'billing',
    permissionResource: 'api.billing',
    requiredGuardIds: ['payment-status-valid'],
    sortOrder: 160,
  }),
  defineTransition({
    transitionId: 'enroll-recall',
    fromStageId: 'follow-up',
    toStageId: 'recall',
    transitionType: 'happy-path',
    ownerModuleId: 'scheduling',
    permissionResource: 'api.scheduling',
    requiredGuardIds: ['follow-up-due'],
    allowedCycle: true,
    sortOrder: 170,
  }),
  defineTransition({
    transitionId: 'enter-ltc',
    fromStageId: 'diagnosis',
    toStageId: 'long-term-care',
    transitionType: 'side-path',
    ownerModuleId: 'emr',
    permissionResource: 'api.emr',
    requiredGuardIds: ['diagnosis-recorded'],
    sortOrder: 180,
  }),
  defineTransition({
    transitionId: 'discharge-episode',
    fromStageId: 'follow-up',
    toStageId: 'discharge',
    transitionType: 'happy-path',
    ownerModuleId: 'scheduling',
    permissionResource: 'api.scheduling',
    requiredGuardIds: ['payment-status-valid'],
    requiredApprovalIds: ['discharge-with-balance'],
    automationRuleIds: ['on-discharge-recall'],
    sortOrder: 190,
  }),
  defineTransition({
    transitionId: 'reactivate',
    fromStageId: 'discharge',
    toStageId: 're-activation',
    transitionType: 'reactivation',
    ownerModuleId: 'patients',
    permissionResource: 'api.patients',
    requiredGuardIds: ['patient-registered', 'branch-accessible'],
    allowedCycle: true,
    sortOrder: 200,
  }),
  defineTransition({
    transitionId: 'cancel-appointment',
    fromStageId: 'appointment',
    toStageId: 'discharge',
    transitionType: 'cancel',
    ownerModuleId: 'scheduling',
    permissionResource: 'api.scheduling',
    requiredGuardIds: [],
    failureBehavior: { strategy: 'compensate', failClosed: true },
    sortOrder: 210,
  }),
  defineTransition({
    transitionId: 'mark-no-show',
    fromStageId: 'appointment',
    toStageId: 'recall',
    transitionType: 'cancel',
    ownerModuleId: 'scheduling',
    permissionResource: 'api.scheduling',
    requiredGuardIds: [],
    automationRuleIds: ['on-queue-sla-escalate'],
    failureBehavior: { strategy: 'compensate', failClosed: true },
    sortOrder: 220,
  }),
] as const;

export const CANONICAL_JOURNEY_TRANSITION_COUNT = CANONICAL_JOURNEY_TRANSITIONS.length;
export const CANONICAL_JOURNEY_TRANSITION_IDS = CANONICAL_JOURNEY_TRANSITIONS.map((t) => t.transitionId);
