import { ANALYTICS_CONTRIBUTION_SCHEMA_VERSION, type CanonicalAnalyticsWidget } from './analytics-types';

/** Builder palette widgets — each primaryMetricId must exist in canonical-analytics-metrics.ts */
export const CANONICAL_ANALYTICS_WIDGETS: readonly CanonicalAnalyticsWidget[] = [
  {
    widgetCatalogId: 'revenueTrend',
    analyticsId: 'widget.revenueTrend',
    localId: 'revenueTrend',
    moduleId: 'analytics',
    analyticsKind: 'widget',
    categoryId: 'financial',
    dataDomain: 'financial',
    classification: 'financial',
    titleKey: 'analytics.sections.revenue',
    descriptionKey: 'analytics.builder.widgets.revenue',
    primaryMetricId: 'revenue_total',
    metricIds: ['revenue_total'],
    visualizationTypes: ['area'],
    chartType: 'area',
    size: 'large',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 0,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'appointmentTrend',
    analyticsId: 'widget.appointmentTrend',
    localId: 'appointmentTrend',
    moduleId: 'analytics',
    analyticsKind: 'widget',
    categoryId: 'operations',
    dataDomain: 'operations',
    classification: 'operational',
    titleKey: 'analytics.sections.appointments',
    descriptionKey: 'analytics.builder.widgets.appointments',
    primaryMetricId: 'appointment_count',
    metricIds: ['appointment_count'],
    visualizationTypes: ['bar'],
    chartType: 'bar',
    size: 'medium',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 10,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'patientGrowth',
    analyticsId: 'widget.patientGrowth',
    localId: 'patientGrowth',
    moduleId: 'analytics',
    analyticsKind: 'widget',
    categoryId: 'patients',
    dataDomain: 'patients',
    classification: 'operational',
    titleKey: 'analytics.patients.growthTitle',
    descriptionKey: 'analytics.builder.widgets.patients',
    primaryMetricId: 'patient_count',
    metricIds: ['patient_count'],
    visualizationTypes: ['line'],
    chartType: 'line',
    size: 'medium',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 20,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'collectionGauge',
    analyticsId: 'widget.collectionGauge',
    localId: 'collectionGauge',
    moduleId: 'analytics',
    analyticsKind: 'widget',
    categoryId: 'financial',
    dataDomain: 'financial',
    classification: 'financial',
    titleKey: 'dashboard.health.collection',
    descriptionKey: 'analytics.builder.widgets.collection',
    primaryMetricId: 'collection_rate',
    metricIds: ['collection_rate'],
    visualizationTypes: ['gauge'],
    chartType: 'gauge',
    size: 'small',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 30,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'utilizationGauge',
    analyticsId: 'widget.utilizationGauge',
    localId: 'utilizationGauge',
    moduleId: 'analytics',
    analyticsKind: 'widget',
    categoryId: 'operations',
    dataDomain: 'operations',
    classification: 'operational',
    titleKey: 'dashboard.health.utilization',
    descriptionKey: 'analytics.builder.widgets.utilization',
    primaryMetricId: 'utilization_rate',
    metricIds: ['utilization_rate'],
    visualizationTypes: ['gauge'],
    chartType: 'gauge',
    size: 'small',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 40,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'branchComparison',
    analyticsId: 'widget.branchComparison',
    localId: 'branchComparison',
    moduleId: 'analytics',
    analyticsKind: 'widget',
    categoryId: 'branches',
    dataDomain: 'branches',
    classification: 'operational',
    titleKey: 'analytics.sections.branches',
    descriptionKey: 'analytics.builder.widgets.branches',
    primaryMetricId: 'branch_revenue',
    metricIds: ['branch_revenue'],
    visualizationTypes: ['bar'],
    chartType: 'bar',
    size: 'large',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 50,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'providerPerformance',
    analyticsId: 'widget.providerPerformance',
    localId: 'providerPerformance',
    moduleId: 'analytics',
    analyticsKind: 'widget',
    categoryId: 'staff',
    dataDomain: 'staff',
    classification: 'operational',
    titleKey: 'analytics.sections.doctors',
    descriptionKey: 'analytics.builder.widgets.staff',
    primaryMetricId: 'staff_productivity',
    metricIds: ['staff_productivity'],
    visualizationTypes: ['bar'],
    chartType: 'bar',
    size: 'medium',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 60,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'inventoryHealth',
    analyticsId: 'widget.inventoryHealth',
    localId: 'inventoryHealth',
    moduleId: 'analytics',
    analyticsKind: 'widget',
    categoryId: 'inventory',
    dataDomain: 'inventory',
    classification: 'operational',
    titleKey: 'analytics.inventory.summaryTitle',
    descriptionKey: 'analytics.builder.widgets.inventory',
    primaryMetricId: 'inventory_stock_health',
    metricIds: ['inventory_stock_health'],
    visualizationTypes: ['pie'],
    chartType: 'pie',
    size: 'medium',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 70,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_ANALYTICS_WIDGET_COUNT = CANONICAL_ANALYTICS_WIDGETS.length;

export const CANONICAL_ANALYTICS_WIDGET_IDS = CANONICAL_ANALYTICS_WIDGETS.map((widget) => widget.widgetCatalogId);
