import { ANALYTICS_CONTRIBUTION_SCHEMA_VERSION, type CanonicalAnalyticsHub } from './analytics-types';

/** Analytics navigation hubs — must be declared on the analytics module only */
export const CANONICAL_ANALYTICS_HUBS: readonly CanonicalAnalyticsHub[] = [
  {
    hubId: 'catalog',
    analyticsId: 'hub.catalog',
    localId: 'catalog',
    moduleId: 'analytics',
    analyticsKind: 'hub',
    categoryId: 'platform.analytics',
    dataDomain: 'platform',
    classification: 'platform',
    titleKey: 'nav.analytics',
    descriptionKey: 'analytics.home.subtitle',
    route: '/analytics',
    deepLinkTemplate: '/analytics',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 0,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    hubId: 'builder',
    analyticsId: 'hub.builder',
    localId: 'builder',
    moduleId: 'analytics',
    analyticsKind: 'hub',
    categoryId: 'platform.builder',
    dataDomain: 'platform',
    classification: 'platform',
    titleKey: 'analytics.builder.title',
    descriptionKey: 'analytics.builder.subtitle',
    route: '/analytics/builder',
    deepLinkTemplate: '/analytics/builder',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    sortOrder: 10,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    hubId: 'export-center',
    analyticsId: 'hub.export-center',
    localId: 'export-center',
    moduleId: 'analytics',
    analyticsKind: 'hub',
    categoryId: 'platform.export',
    dataDomain: 'platform',
    classification: 'platform',
    titleKey: 'analytics.export.title',
    descriptionKey: 'analytics.export.subtitle',
    route: '/analytics/export',
    deepLinkTemplate: '/analytics/export',
    permissionAction: 'export',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    exportFormats: ['pdf', 'csv', 'excel', 'json'],
    sortOrder: 20,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_ANALYTICS_HUB_COUNT = CANONICAL_ANALYTICS_HUBS.length;

export const CANONICAL_ANALYTICS_HUB_IDS = CANONICAL_ANALYTICS_HUBS.map((hub) => hub.hubId);
