import type { CanonicalAnalyticsMetric } from './analytics-types';

const BUILTIN_PROVIDER = 'analytics.builtin' as const;
const ANALYTICS_FEATURE = 'analytics' as const;

/**
 * Canonical metric ID registry — highest authority in the analytics vocabulary hierarchy.
 * Widgets, domains, manifests, and STATIC_ANALYTICS_CATALOG must reference IDs declared here.
 * Every metric is fully self-describing (Phase 34a M1).
 */
export const CANONICAL_ANALYTICS_METRICS: readonly CanonicalAnalyticsMetric[] = [
  {
    metricId: 'revenue_total',
    labelKey: 'analytics.metrics.revenueTotal',
    descriptionKey: 'analytics.metrics.revenueTotal.desc',
    unit: 'currency',
    format: 'currency',
    precision: 2,
    scope: 'widget',
    categoryId: 'financial',
    dataDomain: 'financial',
    aggregation: 'sum',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'appointment_count',
    labelKey: 'analytics.metrics.appointmentCount',
    descriptionKey: 'analytics.metrics.appointmentCount.desc',
    unit: 'count',
    format: 'number',
    precision: 0,
    scope: 'widget',
    categoryId: 'operations',
    dataDomain: 'operations',
    aggregation: 'count',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
  {
    metricId: 'patient_count',
    labelKey: 'analytics.metrics.patientCount',
    descriptionKey: 'analytics.metrics.patientCount.desc',
    unit: 'count',
    format: 'number',
    precision: 0,
    scope: 'widget',
    categoryId: 'patients',
    dataDomain: 'patients',
    aggregation: 'count',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
  {
    metricId: 'collection_rate',
    labelKey: 'analytics.metrics.collectionRate',
    descriptionKey: 'analytics.metrics.collectionRate.desc',
    unit: 'percent',
    format: 'percent',
    precision: 1,
    scope: 'widget',
    categoryId: 'financial',
    dataDomain: 'financial',
    aggregation: 'rate',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'utilization_rate',
    labelKey: 'analytics.metrics.utilizationRate',
    descriptionKey: 'analytics.metrics.utilizationRate.desc',
    unit: 'percent',
    format: 'percent',
    precision: 1,
    scope: 'widget',
    categoryId: 'operations',
    dataDomain: 'operations',
    aggregation: 'rate',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
  {
    metricId: 'branch_revenue',
    labelKey: 'analytics.metrics.branchRevenue',
    descriptionKey: 'analytics.metrics.branchRevenue.desc',
    unit: 'currency',
    format: 'currency',
    precision: 2,
    scope: 'widget',
    categoryId: 'branches',
    dataDomain: 'branches',
    aggregation: 'sum',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'staff_productivity',
    labelKey: 'analytics.metrics.staffProductivity',
    descriptionKey: 'analytics.metrics.staffProductivity.desc',
    unit: 'score',
    format: 'number',
    precision: 1,
    scope: 'widget',
    categoryId: 'staff',
    dataDomain: 'staff',
    aggregation: 'avg',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
  {
    metricId: 'inventory_stock_health',
    labelKey: 'analytics.metrics.inventoryStockHealth',
    descriptionKey: 'analytics.metrics.inventoryStockHealth.desc',
    unit: 'ratio',
    format: 'percent',
    precision: 1,
    scope: 'widget',
    categoryId: 'inventory',
    dataDomain: 'inventory',
    aggregation: 'rate',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
  {
    metricId: 'dental.procedures',
    labelKey: 'modules.dental.analytics.procedures',
    descriptionKey: 'modules.dental.analytics.procedures.desc',
    unit: 'count',
    format: 'number',
    precision: 0,
    scope: 'cross-module',
    categoryId: 'dental',
    dataDomain: 'dental',
    aggregation: 'count',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'clinical',
  },
  {
    metricId: 'billing.revenue',
    labelKey: 'modules.billing.analytics.revenue',
    descriptionKey: 'modules.billing.analytics.revenue.desc',
    unit: 'currency',
    format: 'currency',
    precision: 2,
    scope: 'cross-module',
    categoryId: 'financial',
    dataDomain: 'financial',
    aggregation: 'sum',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'commission.payouts',
    labelKey: 'modules.commission.analytics.payouts',
    descriptionKey: 'modules.commission.analytics.payouts.desc',
    unit: 'currency',
    format: 'currency',
    precision: 2,
    scope: 'cross-module',
    categoryId: 'financial',
    dataDomain: 'financial',
    aggregation: 'sum',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'executive.revenueMonth',
    labelKey: 'analytics.kpis.revenueMonth',
    descriptionKey: 'analytics.kpis.revenueMonth.desc',
    unit: 'currency',
    format: 'currency',
    precision: 2,
    scope: 'domain-kpi',
    categoryId: 'executive',
    dataDomain: 'executive',
    aggregation: 'sum',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'executive.revenueToday',
    labelKey: 'analytics.kpis.revenueToday',
    descriptionKey: 'analytics.kpis.revenueToday.desc',
    unit: 'currency',
    format: 'currency',
    precision: 2,
    scope: 'domain-kpi',
    categoryId: 'executive',
    dataDomain: 'executive',
    aggregation: 'sum',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'executive.outstanding',
    labelKey: 'analytics.kpis.outstanding',
    descriptionKey: 'analytics.kpis.outstanding.desc',
    unit: 'currency',
    format: 'currency',
    precision: 2,
    scope: 'domain-kpi',
    categoryId: 'executive',
    dataDomain: 'executive',
    aggregation: 'sum',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'executive.appointmentsToday',
    labelKey: 'analytics.kpis.appointmentsToday',
    descriptionKey: 'analytics.kpis.appointmentsToday.desc',
    unit: 'count',
    format: 'number',
    precision: 0,
    scope: 'domain-kpi',
    categoryId: 'executive',
    dataDomain: 'executive',
    aggregation: 'count',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
  {
    metricId: 'executive.totalPatients',
    labelKey: 'analytics.kpis.totalPatients',
    descriptionKey: 'analytics.kpis.totalPatients.desc',
    unit: 'count',
    format: 'number',
    precision: 0,
    scope: 'domain-kpi',
    categoryId: 'executive',
    dataDomain: 'executive',
    aggregation: 'count',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
  {
    metricId: 'executive.newPatients',
    labelKey: 'analytics.kpis.newPatients',
    descriptionKey: 'analytics.kpis.newPatients.desc',
    unit: 'count',
    format: 'number',
    precision: 0,
    scope: 'domain-kpi',
    categoryId: 'executive',
    dataDomain: 'executive',
    aggregation: 'count',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
  {
    metricId: 'executive.collection',
    labelKey: 'analytics.kpis.collection',
    descriptionKey: 'analytics.kpis.collection.desc',
    unit: 'percent',
    format: 'percent',
    precision: 1,
    scope: 'domain-kpi',
    categoryId: 'executive',
    dataDomain: 'executive',
    aggregation: 'rate',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
    sensitivity: 'financial',
  },
  {
    metricId: 'executive.utilization',
    labelKey: 'analytics.kpis.utilization',
    descriptionKey: 'analytics.kpis.utilization.desc',
    unit: 'percent',
    format: 'percent',
    precision: 1,
    scope: 'domain-kpi',
    categoryId: 'executive',
    dataDomain: 'executive',
    aggregation: 'rate',
    providerKey: BUILTIN_PROVIDER,
    featureId: ANALYTICS_FEATURE,
  },
] as const;

export const CANONICAL_METRIC_IDS = CANONICAL_ANALYTICS_METRICS.map((metric) => metric.metricId);

export const CANONICAL_ANALYTICS_METRIC_COUNT = CANONICAL_ANALYTICS_METRICS.length;

export const CANONICAL_METRIC_ID_SET = new Set(CANONICAL_METRIC_IDS);

export function getCanonicalMetric(metricId: string): CanonicalAnalyticsMetric | undefined {
  return CANONICAL_ANALYTICS_METRICS.find((metric) => metric.metricId === metricId);
}
