import { ANALYTICS_CONTRIBUTION_SCHEMA_VERSION, type CanonicalAnalyticsDomain } from './analytics-types';

/** Domain views — metricIds must reference canonical-analytics-metrics.ts */
export const CANONICAL_ANALYTICS_DOMAINS: readonly CanonicalAnalyticsDomain[] = [
  {
    domainId: 'executive',
    analyticsId: 'executive',
    localId: 'executive',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'executive',
    dataDomain: 'executive',
    classification: 'operational',
    titleKey: 'analytics.domains.executive.title',
    descriptionKey: 'analytics.domains.executive.desc',
    iconKey: 'layout',
    route: '/analytics/executive',
    deepLinkTemplate: '/analytics/executive',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    metricIds: [
      'revenue_total',
      'appointment_count',
      'patient_count',
      'collection_rate',
      'utilization_rate',
      'executive.revenueMonth',
      'executive.revenueToday',
      'executive.outstanding',
      'executive.appointmentsToday',
      'executive.totalPatients',
      'executive.newPatients',
      'executive.collection',
      'executive.utilization',
    ],
    reportLinkIds: ['executive-dashboard', 'executive-export', 'custom-report'],
    dashboardWidgetIds: ['revenue-chart', 'appointment-trends', 'patient-growth', 'business-health'],
    filterProfile: 'all',
    sortOrder: 0,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'financial',
    analyticsId: 'financial',
    localId: 'financial',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'financial',
    dataDomain: 'financial',
    classification: 'financial',
    titleKey: 'analytics.domains.financial.title',
    descriptionKey: 'analytics.domains.financial.desc',
    iconKey: 'revenue',
    route: '/analytics/financial',
    deepLinkTemplate: '/analytics/financial',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    permissionResources: ['api.analytics', 'api.billing'],
    featureId: 'analytics',
    metricIds: ['revenue_total', 'collection_rate', 'billing.revenue'],
    reportLinkIds: ['revenue-summary', 'financial-export', 'revenue-export', 'subscription-overview'],
    filterProfile: 'revenue',
    sortOrder: 10,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'patients',
    analyticsId: 'patients',
    localId: 'patients',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'patients',
    dataDomain: 'patients',
    classification: 'operational',
    titleKey: 'analytics.domains.patients.title',
    descriptionKey: 'analytics.domains.patients.desc',
    iconKey: 'patients',
    route: '/analytics/patients',
    deepLinkTemplate: '/analytics/patients',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    metricIds: ['patient_count', 'executive.newPatients', 'executive.totalPatients'],
    reportLinkIds: ['patient-growth'],
    dashboardWidgetIds: ['patient-growth'],
    filterProfile: 'patients',
    sortOrder: 20,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'operations',
    analyticsId: 'operations',
    localId: 'operations',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'operations',
    dataDomain: 'operations',
    classification: 'operational',
    titleKey: 'analytics.domains.operations.title',
    descriptionKey: 'analytics.domains.operations.desc',
    iconKey: 'calendar',
    route: '/analytics/operations',
    deepLinkTemplate: '/analytics/operations',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    metricIds: ['appointment_count', 'utilization_rate', 'executive.appointmentsToday', 'executive.utilization'],
    reportLinkIds: ['appointment-summary', 'operational-export', 'system-usage'],
    dashboardWidgetIds: ['appointment-trends', 'today-appointments', 'queue-status'],
    filterProfile: 'appointments',
    sortOrder: 30,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'inventory',
    analyticsId: 'inventory',
    localId: 'inventory',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'inventory',
    dataDomain: 'inventory',
    classification: 'operational',
    titleKey: 'analytics.domains.inventory.title',
    descriptionKey: 'analytics.domains.inventory.desc',
    iconKey: 'inventory',
    route: '/analytics/inventory',
    deepLinkTemplate: '/analytics/inventory',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    permissionResources: ['api.analytics', 'api.inventory'],
    featureId: 'analytics',
    metricIds: ['inventory_stock_health'],
    dashboardWidgetIds: ['inventory-alerts', 'low-stock'],
    sortOrder: 40,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'clinical',
    analyticsId: 'clinical',
    localId: 'clinical',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'clinical',
    dataDomain: 'clinical',
    classification: 'clinical',
    titleKey: 'analytics.domains.clinical.title',
    descriptionKey: 'analytics.domains.clinical.desc',
    iconKey: 'clinical',
    route: '/analytics/clinical',
    deepLinkTemplate: '/analytics/clinical',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    permissionResources: ['api.analytics', 'api.emr'],
    featureId: 'analytics',
    metricIds: ['patient_count'],
    reportLinkIds: ['clinical-activity', 'patient-list-export'],
    sortOrder: 50,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'dental',
    analyticsId: 'dental',
    localId: 'dental',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'dental',
    dataDomain: 'dental',
    classification: 'clinical',
    titleKey: 'analytics.domains.dental.title',
    descriptionKey: 'analytics.domains.dental.desc',
    iconKey: 'dental',
    route: '/analytics/dental',
    deepLinkTemplate: '/analytics/dental',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    permissionResources: ['api.analytics', 'api.dental'],
    featureId: 'analytics',
    metricIds: ['dental.procedures'],
    sortOrder: 60,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'beauty',
    analyticsId: 'beauty',
    localId: 'beauty',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'beauty',
    dataDomain: 'beauty',
    classification: 'clinical',
    titleKey: 'analytics.domains.beauty.title',
    descriptionKey: 'analytics.domains.beauty.desc',
    iconKey: 'beauty',
    route: '/analytics/beauty',
    deepLinkTemplate: '/analytics/beauty',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    permissionResources: ['api.analytics', 'api.beauty'],
    featureId: 'analytics',
    metricIds: [],
    sortOrder: 70,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'staff',
    analyticsId: 'staff',
    localId: 'staff',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'staff',
    dataDomain: 'staff',
    classification: 'operational',
    titleKey: 'analytics.domains.staff.title',
    descriptionKey: 'analytics.domains.staff.desc',
    iconKey: 'staff',
    route: '/analytics/staff',
    deepLinkTemplate: '/analytics/staff',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    metricIds: ['staff_productivity'],
    reportLinkIds: ['doctor-productivity', 'department-performance'],
    dashboardWidgetIds: ['doctor-performance'],
    sortOrder: 80,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'branches',
    analyticsId: 'branches',
    localId: 'branches',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'branches',
    dataDomain: 'branches',
    classification: 'operational',
    titleKey: 'analytics.domains.branches.title',
    descriptionKey: 'analytics.domains.branches.desc',
    iconKey: 'branches',
    route: '/analytics/branches',
    deepLinkTemplate: '/analytics/branches',
    permissionAction: 'view',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    metricIds: ['branch_revenue'],
    reportLinkIds: ['branch-performance'],
    dashboardWidgetIds: ['branch-performance'],
    sortOrder: 90,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    domainId: 'forecasting',
    analyticsId: 'forecasting',
    localId: 'forecasting',
    moduleId: 'analytics',
    analyticsKind: 'domain',
    categoryId: 'forecasting',
    dataDomain: 'forecasting',
    classification: 'operational',
    titleKey: 'analytics.domains.forecasting.title',
    descriptionKey: 'analytics.domains.forecasting.desc',
    iconKey: 'forecast',
    route: '/analytics/forecasting',
    deepLinkTemplate: '/analytics/forecasting',
    permissionAction: 'create',
    permissionResource: 'api.analytics',
    featureId: 'analytics',
    metricIds: ['revenue_total', 'appointment_count', 'patient_count'],
    reportLinkIds: ['custom-report'],
    sortOrder: 100,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_ANALYTICS_DOMAIN_COUNT = CANONICAL_ANALYTICS_DOMAINS.length;

export const CANONICAL_ANALYTICS_DOMAIN_IDS = CANONICAL_ANALYTICS_DOMAINS.map((domain) => domain.domainId);
