import { ANALYTICS_CONTRIBUTION_SCHEMA_VERSION, type CanonicalAnalyticsWidget } from './analytics-types';

/** Cross-module analytics widget surfaces owned by specialty modules */
export const CANONICAL_CROSS_MODULE_ANALYTICS: readonly CanonicalAnalyticsWidget[] = [
  {
    widgetCatalogId: 'dental-procedures',
    analyticsId: 'dental.dental-procedures',
    localId: 'dental-procedures',
    moduleId: 'dental',
    analyticsKind: 'widget',
    categoryId: 'dental',
    dataDomain: 'dental',
    classification: 'clinical',
    titleKey: 'modules.dental.analytics.procedures',
    descriptionKey: 'modules.dental.analytics.procedures',
    primaryMetricId: 'dental.procedures',
    metricIds: ['dental.procedures'],
    visualizationTypes: ['bar'],
    chartType: 'bar',
    size: 'medium',
    permissionAction: 'view',
    permissionResource: 'api.dental',
    featureId: 'analytics',
    sortOrder: 0,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'billing-revenue',
    analyticsId: 'billing.billing-revenue',
    localId: 'billing-revenue',
    moduleId: 'billing',
    analyticsKind: 'widget',
    categoryId: 'financial',
    dataDomain: 'financial',
    classification: 'financial',
    titleKey: 'modules.billing.analytics.revenue',
    descriptionKey: 'modules.billing.analytics.revenue',
    primaryMetricId: 'billing.revenue',
    metricIds: ['billing.revenue'],
    visualizationTypes: ['area'],
    chartType: 'area',
    size: 'medium',
    permissionAction: 'view',
    permissionResource: 'api.billing',
    featureId: 'analytics',
    sortOrder: 0,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
  {
    widgetCatalogId: 'commission-payouts',
    analyticsId: 'commission.commission-payouts',
    localId: 'commission-payouts',
    moduleId: 'commission',
    analyticsKind: 'widget',
    categoryId: 'financial',
    dataDomain: 'financial',
    classification: 'financial',
    titleKey: 'modules.commission.analytics.payouts',
    descriptionKey: 'modules.commission.analytics.payouts',
    primaryMetricId: 'commission.payouts',
    metricIds: ['commission.payouts'],
    visualizationTypes: ['bar'],
    chartType: 'bar',
    size: 'medium',
    permissionAction: 'view',
    permissionResource: 'api.commission',
    featureId: 'analytics',
    sortOrder: 0,
    providerKey: 'analytics.builtin',
    schemaVersion: ANALYTICS_CONTRIBUTION_SCHEMA_VERSION,
  },
] as const;

export const CANONICAL_CROSS_MODULE_ANALYTICS_COUNT = CANONICAL_CROSS_MODULE_ANALYTICS.length;

export const CANONICAL_ANALYTICS_ENTRY_COUNT =
  11 + 8 + 3 + CANONICAL_CROSS_MODULE_ANALYTICS_COUNT;
