import {
  AUDIT_BUILTIN_PROVIDER_KEY,
  AUDIT_CONTRIBUTION_SCHEMA_VERSION,
  type AuditActionId,
  type AuditCategoryId,
  type AuditOutcomeId,
  type AuditRisk,
  type AuditSeverity,
  type CanonicalAuditEventType,
} from './audit-types';
import type { LicensedModuleId, PermissionAction } from '../types';

type TypeInput = {
  auditEventTypeId: string;
  localId: string;
  moduleId: LicensedModuleId;
  categoryId: AuditCategoryId;
  severity: AuditSeverity;
  risk: AuditRisk;
  action: AuditActionId;
  defaultOutcome?: AuditOutcomeId;
  resourceType: string;
  permissionResource?: string;
  permissionAction?: PermissionAction;
  branchScoped?: boolean;
  crossBranchAllowed?: boolean;
  retentionPolicyId?: string;
  redactionPolicyId?: string;
  integrityPolicyId?: string;
  exportPolicyId?: string;
  feedIds: readonly string[];
  legacyActionHint?: string;
  sortOrder: number;
};

function defineType(input: TypeInput): CanonicalAuditEventType {
  return {
    auditEventTypeId: input.auditEventTypeId,
    localId: input.localId,
    moduleId: input.moduleId,
    owningModuleId: input.moduleId,
    producerModuleId: input.moduleId,
    auditKind: 'type',
    categoryId: input.categoryId,
    severity: input.severity,
    risk: input.risk,
    action: input.action,
    defaultOutcome: input.defaultOutcome ?? 'success',
    resourceType: input.resourceType,
    permissionResource: input.permissionResource ?? 'api.audit',
    permissionAction: input.permissionAction ?? 'view',
    tenantScoped: true,
    branchScoped: input.branchScoped ?? true,
    crossBranchAllowed: input.crossBranchAllowed ?? false,
    retentionPolicyId: input.retentionPolicyId ?? 'retention.hot-365d',
    redactionPolicyId: input.redactionPolicyId ?? 'redaction.standard',
    integrityPolicyId: input.integrityPolicyId ?? 'integrity.hash-basic',
    exportPolicyId: input.exportPolicyId ?? 'export.redacted',
    labelKey: `audit.type.${input.auditEventTypeId}`,
    descriptionKey: `audit.type.${input.auditEventTypeId}.description`,
    deepLinkTemplate: `/settings/audit?type=${input.auditEventTypeId}`,
    providerKey: AUDIT_BUILTIN_PROVIDER_KEY,
    feedIds: input.feedIds,
    eventVersion: '1.0.0',
    schemaVersion: '1',
    legacyActionHint: input.legacyActionHint,
    sortOrder: input.sortOrder,
    contributionSchemaVersion: AUDIT_CONTRIBUTION_SCHEMA_VERSION,
  };
}

/**
 * Builtin module-owned audit event types — metadata mapping existing writers where known.
 * Does not alter AuditEntry writes (Phase 39a).
 */
export const CANONICAL_AUDIT_EVENT_TYPES: readonly CanonicalAuditEventType[] = [
  // —— userManagement / identity (existing writers) ——
  defineType({
    auditEventTypeId: 'identity.user.updated',
    localId: 'identity-user-updated',
    moduleId: 'userManagement',
    categoryId: 'user-management',
    severity: 'medium',
    risk: 'moderate',
    action: 'update',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'user-access-changes', 'my-actions'],
    legacyActionHint: 'identity.user.updated',
    sortOrder: 10,
  }),
  defineType({
    auditEventTypeId: 'identity.user.suspended',
    localId: 'identity-user-suspended',
    moduleId: 'userManagement',
    categoryId: 'user-management',
    severity: 'high',
    risk: 'high',
    action: 'suspend',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'user-access-changes', 'security', 'critical-events'],
    legacyActionHint: 'identity.user.suspended',
    sortOrder: 20,
  }),
  defineType({
    auditEventTypeId: 'identity.user.archived',
    localId: 'identity-user-archived',
    moduleId: 'userManagement',
    categoryId: 'user-management',
    severity: 'high',
    risk: 'high',
    action: 'archive',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'user-access-changes', 'administration'],
    legacyActionHint: 'identity.user.archived',
    sortOrder: 30,
  }),
  defineType({
    auditEventTypeId: 'identity.user.restored',
    localId: 'identity-user-restored',
    moduleId: 'userManagement',
    categoryId: 'user-management',
    severity: 'medium',
    risk: 'moderate',
    action: 'restore',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'user-access-changes', 'administration'],
    legacyActionHint: 'identity.user.restored',
    sortOrder: 40,
  }),
  defineType({
    auditEventTypeId: 'identity.user.locked',
    localId: 'identity-user-locked',
    moduleId: 'userManagement',
    categoryId: 'security',
    severity: 'high',
    risk: 'high',
    action: 'disable',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'security', 'user-access-changes', 'critical-events'],
    redactionPolicyId: 'redaction.security-elevated',
    legacyActionHint: 'identity.user.locked',
    sortOrder: 50,
  }),
  defineType({
    auditEventTypeId: 'identity.user.invited',
    localId: 'identity-user-invited',
    moduleId: 'userManagement',
    categoryId: 'user-management',
    severity: 'medium',
    risk: 'moderate',
    action: 'invite',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'user-access-changes', 'my-actions'],
    legacyActionHint: 'identity.user.invited',
    sortOrder: 60,
  }),
  defineType({
    auditEventTypeId: 'identity.user.deleted',
    localId: 'identity-user-deleted',
    moduleId: 'userManagement',
    categoryId: 'user-management',
    severity: 'critical',
    risk: 'severe',
    action: 'delete',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'user-access-changes', 'security', 'critical-events'],
    retentionPolicyId: 'retention.warm-7y',
    redactionPolicyId: 'redaction.security-elevated',
    legacyActionHint: 'identity.user.deleted',
    sortOrder: 70,
  }),
  defineType({
    auditEventTypeId: 'identity.user.session_revoked',
    localId: 'identity-user-session-revoked',
    moduleId: 'userManagement',
    categoryId: 'security',
    severity: 'high',
    risk: 'high',
    action: 'revoke',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'security', 'user-access-changes'],
    redactionPolicyId: 'redaction.security-elevated',
    legacyActionHint: 'identity.user.session_revoked',
    sortOrder: 80,
  }),
  defineType({
    auditEventTypeId: 'identity.user.password_reset_forced',
    localId: 'identity-user-password-reset-forced',
    moduleId: 'userManagement',
    categoryId: 'security',
    severity: 'high',
    risk: 'high',
    action: 'override',
    resourceType: 'identity.user',
    feedIds: ['all-authorized', 'security', 'user-access-changes', 'critical-events'],
    redactionPolicyId: 'redaction.security-elevated',
    exportPolicyId: 'export.denied',
    legacyActionHint: 'identity.user.password_reset_forced',
    sortOrder: 90,
  }),
  defineType({
    auditEventTypeId: 'identity.role.created',
    localId: 'identity-role-created',
    moduleId: 'userManagement',
    categoryId: 'authorization',
    severity: 'high',
    risk: 'high',
    action: 'create',
    resourceType: 'identity.role',
    feedIds: ['all-authorized', 'user-access-changes', 'administration', 'security'],
    legacyActionHint: 'identity.role.created',
    sortOrder: 100,
  }),
  defineType({
    auditEventTypeId: 'identity.role.updated',
    localId: 'identity-role-updated',
    moduleId: 'userManagement',
    categoryId: 'authorization',
    severity: 'high',
    risk: 'high',
    action: 'update',
    resourceType: 'identity.role',
    feedIds: ['all-authorized', 'user-access-changes', 'administration', 'security'],
    legacyActionHint: 'identity.role.updated',
    sortOrder: 110,
  }),

  // —— settings / licensing (LicenseAuditEvent mirror + settings) ——
  defineType({
    auditEventTypeId: 'licensing.module.denied',
    localId: 'licensing-module-denied',
    moduleId: 'settings',
    categoryId: 'licensing',
    severity: 'medium',
    risk: 'moderate',
    action: 'deny',
    defaultOutcome: 'denied',
    resourceType: 'licensing',
    feedIds: ['all-authorized', 'licensing-module-changes', 'failed-denied'],
    branchScoped: false,
    legacyActionHint: 'module.denied',
    sortOrder: 120,
  }),
  defineType({
    auditEventTypeId: 'licensing.feature.denied',
    localId: 'licensing-feature-denied',
    moduleId: 'settings',
    categoryId: 'licensing',
    severity: 'medium',
    risk: 'moderate',
    action: 'deny',
    defaultOutcome: 'denied',
    resourceType: 'licensing',
    feedIds: ['all-authorized', 'licensing-module-changes', 'failed-denied'],
    branchScoped: false,
    legacyActionHint: 'feature.denied',
    sortOrder: 130,
  }),
  defineType({
    auditEventTypeId: 'licensing.plan.changed',
    localId: 'licensing-plan-changed',
    moduleId: 'settings',
    categoryId: 'licensing',
    severity: 'high',
    risk: 'high',
    action: 'update',
    resourceType: 'licensing',
    feedIds: ['all-authorized', 'licensing-module-changes', 'administration', 'critical-events'],
    branchScoped: false,
    retentionPolicyId: 'retention.warm-7y',
    legacyActionHint: 'plan.upgrade',
    sortOrder: 140,
  }),
  defineType({
    auditEventTypeId: 'licensing.grace.started',
    localId: 'licensing-grace-started',
    moduleId: 'settings',
    categoryId: 'licensing',
    severity: 'high',
    risk: 'high',
    action: 'enable',
    resourceType: 'licensing',
    feedIds: ['all-authorized', 'licensing-module-changes', 'critical-events'],
    branchScoped: false,
    legacyActionHint: 'grace.started',
    sortOrder: 150,
  }),
  defineType({
    auditEventTypeId: 'licensing.suspension',
    localId: 'licensing-suspension',
    moduleId: 'settings',
    categoryId: 'licensing',
    severity: 'critical',
    risk: 'severe',
    action: 'suspend',
    resourceType: 'licensing',
    feedIds: ['all-authorized', 'licensing-module-changes', 'security', 'critical-events'],
    branchScoped: false,
    retentionPolicyId: 'retention.warm-7y',
    legacyActionHint: 'suspension',
    sortOrder: 160,
  }),
  defineType({
    auditEventTypeId: 'settings.audit.config_updated',
    localId: 'settings-audit-config-updated',
    moduleId: 'settings',
    categoryId: 'configuration',
    severity: 'high',
    risk: 'high',
    action: 'update',
    resourceType: 'settings.audit',
    feedIds: ['all-authorized', 'configuration-changes', 'administration', 'critical-events'],
    branchScoped: false,
    sortOrder: 170,
  }),
  defineType({
    auditEventTypeId: 'branch.policy.updated',
    localId: 'branch-policy-updated',
    moduleId: 'settings',
    categoryId: 'branch-administration',
    severity: 'medium',
    risk: 'moderate',
    action: 'update',
    resourceType: 'branch',
    feedIds: ['all-authorized', 'branch-audit', 'configuration-changes', 'administration'],
    sortOrder: 180,
  }),
  defineType({
    auditEventTypeId: 'whitelabel.published',
    localId: 'whitelabel-published',
    moduleId: 'settings',
    categoryId: 'white-label',
    severity: 'medium',
    risk: 'low',
    action: 'publish',
    resourceType: 'whitelabel',
    feedIds: ['all-authorized', 'configuration-changes', 'administration'],
    branchScoped: false,
    sortOrder: 190,
  }),

  // —— reporting ——
  defineType({
    auditEventTypeId: 'report.generated',
    localId: 'report-generated',
    moduleId: 'reporting',
    categoryId: 'reporting',
    severity: 'informational',
    risk: 'low',
    action: 'execute',
    resourceType: 'report',
    feedIds: ['all-authorized', 'my-actions'],
    legacyActionHint: 'report.generated',
    sortOrder: 200,
  }),
  defineType({
    auditEventTypeId: 'report.failed',
    localId: 'report-failed',
    moduleId: 'reporting',
    categoryId: 'reporting',
    severity: 'medium',
    risk: 'low',
    action: 'execute',
    defaultOutcome: 'failed',
    resourceType: 'report',
    feedIds: ['all-authorized', 'failed-denied', 'my-actions'],
    legacyActionHint: 'report.failed',
    sortOrder: 210,
  }),
  defineType({
    auditEventTypeId: 'report.shared',
    localId: 'report-shared',
    moduleId: 'reporting',
    categoryId: 'reporting',
    severity: 'medium',
    risk: 'moderate',
    action: 'grant',
    resourceType: 'report',
    feedIds: ['all-authorized', 'data-exports', 'my-actions'],
    legacyActionHint: 'report.shared',
    sortOrder: 220,
  }),
  defineType({
    auditEventTypeId: 'report.compliance_exported',
    localId: 'report-compliance-exported',
    moduleId: 'reporting',
    categoryId: 'data-export',
    severity: 'high',
    risk: 'high',
    action: 'export',
    resourceType: 'report',
    feedIds: ['all-authorized', 'data-exports', 'critical-events'],
    redactionPolicyId: 'redaction.security-elevated',
    exportPolicyId: 'export.authorized',
    integrityPolicyId: 'integrity.signed-export',
    permissionAction: 'export',
    sortOrder: 230,
  }),

  // —— ai ——
  defineType({
    auditEventTypeId: 'ai.inference.completed',
    localId: 'ai-inference-completed',
    moduleId: 'ai',
    categoryId: 'ai',
    severity: 'informational',
    risk: 'moderate',
    action: 'execute',
    resourceType: 'ai_conversation',
    feedIds: ['all-authorized', 'my-actions'],
    redactionPolicyId: 'redaction.phi-strict',
    legacyActionHint: 'ai.inference.completed',
    sortOrder: 240,
  }),
  defineType({
    auditEventTypeId: 'ai.admin.provider.updated',
    localId: 'ai-admin-provider-updated',
    moduleId: 'ai',
    categoryId: 'ai',
    severity: 'high',
    risk: 'high',
    action: 'update',
    resourceType: 'ai_tenant_settings',
    feedIds: ['all-authorized', 'configuration-changes', 'administration', 'critical-events'],
    redactionPolicyId: 'redaction.security-elevated',
    exportPolicyId: 'export.denied',
    legacyActionHint: 'ai.admin.provider.updated',
    sortOrder: 250,
  }),

  // —— workflow (existing writers still use notifications adapter — metadata only) ——
  defineType({
    auditEventTypeId: 'workflow.approval.approved',
    localId: 'workflow-approval-approved',
    moduleId: 'workflow',
    categoryId: 'workflow',
    severity: 'medium',
    risk: 'moderate',
    action: 'approve',
    resourceType: 'workflow',
    feedIds: ['all-authorized', 'administration', 'my-actions'],
    legacyActionHint: 'workflow.approval.approved',
    sortOrder: 260,
  }),
  defineType({
    auditEventTypeId: 'workflow.approval.rejected',
    localId: 'workflow-approval-rejected',
    moduleId: 'workflow',
    categoryId: 'workflow',
    severity: 'medium',
    risk: 'moderate',
    action: 'reject',
    defaultOutcome: 'denied',
    resourceType: 'workflow',
    feedIds: ['all-authorized', 'administration', 'failed-denied', 'my-actions'],
    legacyActionHint: 'workflow.approval.rejected',
    sortOrder: 270,
  }),
  defineType({
    auditEventTypeId: 'workflow.template.published',
    localId: 'workflow-template-published',
    moduleId: 'workflow',
    categoryId: 'workflow',
    severity: 'medium',
    risk: 'moderate',
    action: 'publish',
    resourceType: 'workflow',
    feedIds: ['all-authorized', 'configuration-changes', 'administration'],
    legacyActionHint: 'workflow.template.published',
    sortOrder: 280,
  }),
  defineType({
    auditEventTypeId: 'workflow.logs.exported',
    localId: 'workflow-logs-exported',
    moduleId: 'workflow',
    categoryId: 'data-export',
    severity: 'high',
    risk: 'high',
    action: 'export',
    resourceType: 'workflow',
    feedIds: ['all-authorized', 'data-exports', 'critical-events'],
    permissionAction: 'export',
    legacyActionHint: 'workflow.logs.exported',
    sortOrder: 290,
  }),

  // —— notifications ——
  defineType({
    auditEventTypeId: 'notifications.template.updated',
    localId: 'notifications-template-updated',
    moduleId: 'notifications',
    categoryId: 'configuration',
    severity: 'low',
    risk: 'low',
    action: 'update',
    resourceType: 'notifications.notification',
    feedIds: ['all-authorized', 'configuration-changes'],
    legacyActionHint: 'notifications.template.updated',
    sortOrder: 300,
  }),
  defineType({
    auditEventTypeId: 'notifications.automation.created',
    localId: 'notifications-automation-created',
    moduleId: 'notifications',
    categoryId: 'configuration',
    severity: 'medium',
    risk: 'moderate',
    action: 'create',
    resourceType: 'notifications.notification',
    feedIds: ['all-authorized', 'configuration-changes', 'administration'],
    legacyActionHint: 'notifications.automation.created',
    sortOrder: 310,
  }),
  defineType({
    auditEventTypeId: 'notifications.delivery.exported',
    localId: 'notifications-delivery-exported',
    moduleId: 'notifications',
    categoryId: 'data-export',
    severity: 'medium',
    risk: 'moderate',
    action: 'export',
    resourceType: 'notifications.notification',
    feedIds: ['all-authorized', 'data-exports'],
    permissionAction: 'export',
    legacyActionHint: 'notifications.delivery.exported',
    sortOrder: 320,
  }),

  // —— clinical / operational domains (canonical intent; writers may land in 39d) ——
  defineType({
    auditEventTypeId: 'patient.record.exported',
    localId: 'patient-record-exported',
    moduleId: 'patients',
    categoryId: 'patient-records',
    severity: 'critical',
    risk: 'severe',
    action: 'export',
    resourceType: 'patient',
    feedIds: ['all-authorized', 'clinical', 'data-exports', 'critical-events'],
    redactionPolicyId: 'redaction.phi-strict',
    retentionPolicyId: 'retention.warm-7y',
    permissionAction: 'export',
    sortOrder: 330,
  }),
  defineType({
    auditEventTypeId: 'appointment.cancelled',
    localId: 'appointment-cancelled',
    moduleId: 'scheduling',
    categoryId: 'scheduling',
    severity: 'medium',
    risk: 'low',
    action: 'delete',
    defaultOutcome: 'cancelled',
    resourceType: 'appointment',
    feedIds: ['all-authorized', 'clinical', 'my-actions'],
    sortOrder: 340,
  }),
  defineType({
    auditEventTypeId: 'encounter.signed',
    localId: 'encounter-signed',
    moduleId: 'emr',
    categoryId: 'clinical',
    severity: 'high',
    risk: 'high',
    action: 'sign',
    resourceType: 'encounter',
    feedIds: ['all-authorized', 'clinical', 'my-actions', 'critical-events'],
    redactionPolicyId: 'redaction.phi-strict',
    retentionPolicyId: 'retention.warm-7y',
    sortOrder: 350,
  }),
  defineType({
    auditEventTypeId: 'invoice.voided',
    localId: 'invoice-voided',
    moduleId: 'billing',
    categoryId: 'billing',
    severity: 'high',
    risk: 'high',
    action: 'override',
    resourceType: 'invoice',
    feedIds: ['all-authorized', 'financial', 'critical-events', 'my-actions'],
    redactionPolicyId: 'redaction.financial-strict',
    retentionPolicyId: 'retention.warm-7y',
    sortOrder: 360,
  }),
  defineType({
    auditEventTypeId: 'inventory.stock.adjusted',
    localId: 'inventory-stock-adjusted',
    moduleId: 'inventory',
    categoryId: 'inventory',
    severity: 'medium',
    risk: 'moderate',
    action: 'update',
    resourceType: 'inventory',
    feedIds: ['all-authorized', 'administration', 'my-actions'],
    sortOrder: 370,
  }),
  defineType({
    auditEventTypeId: 'queue.ticket.overridden',
    localId: 'queue-ticket-overridden',
    moduleId: 'queue',
    categoryId: 'queue',
    severity: 'medium',
    risk: 'moderate',
    action: 'override',
    resourceType: 'queue.ticket',
    feedIds: ['all-authorized', 'clinical', 'my-actions'],
    sortOrder: 380,
  }),
  defineType({
    auditEventTypeId: 'analytics.sensitive.viewed',
    localId: 'analytics-sensitive-viewed',
    moduleId: 'analytics',
    categoryId: 'analytics',
    severity: 'medium',
    risk: 'high',
    action: 'view',
    resourceType: 'analytics',
    feedIds: ['all-authorized', 'critical-events', 'my-actions'],
    redactionPolicyId: 'redaction.phi-strict',
    sortOrder: 390,
  }),
  defineType({
    auditEventTypeId: 'portal.account.activated',
    localId: 'portal-account-activated',
    moduleId: 'patientPortal',
    categoryId: 'privacy',
    severity: 'medium',
    risk: 'moderate',
    action: 'enable',
    resourceType: 'patient_portal',
    feedIds: ['all-authorized', 'user-access-changes', 'security'],
    redactionPolicyId: 'redaction.phi-strict',
    sortOrder: 400,
  }),
  defineType({
    auditEventTypeId: 'dental.chart.updated',
    localId: 'dental-chart-updated',
    moduleId: 'dental',
    categoryId: 'clinical',
    severity: 'medium',
    risk: 'high',
    action: 'update',
    resourceType: 'dental.chart',
    feedIds: ['all-authorized', 'clinical', 'my-actions'],
    redactionPolicyId: 'redaction.phi-strict',
    sortOrder: 410,
  }),
  defineType({
    auditEventTypeId: 'beauty.treatment.updated',
    localId: 'beauty-treatment-updated',
    moduleId: 'beauty',
    categoryId: 'clinical',
    severity: 'medium',
    risk: 'moderate',
    action: 'update',
    resourceType: 'beauty.treatment',
    feedIds: ['all-authorized', 'clinical', 'my-actions'],
    redactionPolicyId: 'redaction.phi-strict',
    sortOrder: 420,
  }),
] as const;

export const CANONICAL_AUDIT_EVENT_TYPE_COUNT = CANONICAL_AUDIT_EVENT_TYPES.length;
export const CANONICAL_AUDIT_EVENT_TYPE_IDS = CANONICAL_AUDIT_EVENT_TYPES.map((t) => t.auditEventTypeId);
